// Code generated by codegen/emit_graphql.py from Zora's OpenAPI spec. DO NOT EDIT.

package gateway

import (
	"context"

	"github.com/pgalyen1987/zora-coins-sdks/go/zora"
)

// callSDK runs the SDK method behind a root field. args has been decoded from the GraphQL
// arguments by the caller; the result is returned as the SDK typed it.
func callSDK(ctx context.Context, c *zora.Client, field string, args map[string]any) (any, error) {
	switch field {
	case "apiKey":
		return c.APIKey(ctx, str(args["apiKey"]))
	case "coin":
		return c.Coin(ctx, str(args["address"]), &zora.CoinParams{ChainID: integer(args["chainId"])})
	case "coinComments":
		return c.CoinComments(ctx, str(args["address"]), &zora.CoinCommentsParams{ChainID: integer(args["chainId"]), After: str(args["after"]), PageSize: integer(args["pageSize"])})
	case "coinHolders":
		return c.CoinHolders(ctx, str(args["address"]), &zora.CoinHoldersParams{ChainID: integer(args["chainId"]), After: str(args["after"]), PageSize: integer(args["pageSize"])})
	case "coinMergedComments":
		return c.CoinMergedComments(ctx, str(args["address"]), &zora.CoinMergedCommentsParams{ChainID: integer(args["chainId"]), After: str(args["after"]), PageSize: integer(args["pageSize"])})
	case "coinPriceHistory":
		return c.CoinPriceHistory(ctx, str(args["address"]), &zora.CoinPriceHistoryParams{ChainID: integer(args["chainId"])})
	case "coinSwaps":
		return c.CoinSwaps(ctx, str(args["address"]), &zora.CoinSwapsParams{ChainID: integer(args["chainId"]), After: str(args["after"]), PageSize: integer(args["pageSize"])})
	case "coins":
		var coins []*zora.CoinRefInput
		if err := remarshal(args["coins"], &coins); err != nil {
			return nil, err
		}
		return c.Coins(ctx, coins)
	case "coinsList":
		return c.CoinsList(ctx, &zora.CoinsListParams{PageSize: integer(args["pageSize"]), After: str(args["after"]), IncludeUSDCPrice: boolPtr(args["includeUSDCPrice"])})
	case "contentCoinPoolConfig":
		return c.ContentCoinPoolConfig(ctx, zora.CurrencyType(str(args["currencyType"])), &zora.ContentCoinPoolConfigParams{CreatorIdentifier: str(args["creatorIdentifier"])})
	case "creatorCoinPoolConfig":
		return c.CreatorCoinPoolConfig(ctx, &zora.CreatorCoinPoolConfigParams{TargetMarketCapUSD: integer(args["targetMarketCapUsd"])})
	case "creatorLivestreamComments":
		return c.CreatorLivestreamComments(ctx, str(args["address"]), &zora.CreatorLivestreamCommentsParams{ChainID: integer(args["chainId"]), After: str(args["after"]), PageSize: integer(args["pageSize"])})
	case "explore":
		return c.Explore(ctx, zora.ListType(str(args["listType"])), &zora.ExploreParams{PageSize: integer(args["pageSize"]), After: str(args["after"])})
	case "featuredCreators":
		return c.FeaturedCreators(ctx, &zora.FeaturedCreatorsParams{Year: integer(args["year"]), Week: integer(args["week"]), PageSize: integer(args["pageSize"]), After: str(args["after"])})
	case "latestLiveStreams":
		return c.LatestLiveStreams(ctx, &zora.LatestLiveStreamsParams{PageSize: integer(args["pageSize"]), After: str(args["after"])})
	case "profile":
		return c.Profile(ctx, str(args["identifier"]))
	case "profileBalances":
		return c.ProfileBalances(ctx, str(args["identifier"]), &zora.ProfileBalancesParams{PageSize: integer(args["pageSize"]), After: str(args["after"]), SortOption: zora.SortOption(str(args["sortOption"])), ExcludeHidden: boolPtr(args["excludeHidden"]), ChainIDs: ints(args["chainIds"])})
	case "profileBySocialHandle":
		return c.ProfileBySocialHandle(ctx, zora.Platform(str(args["platform"])), str(args["handle"]))
	case "profileCoins":
		return c.ProfileCoins(ctx, str(args["identifier"]), &zora.ProfileCoinsParams{PageSize: integer(args["pageSize"]), After: str(args["after"]), ChainIDs: ints(args["chainIds"]), PlatformReferrerAddress: strs(args["platformReferrerAddress"])})
	case "profileSocial":
		return c.ProfileSocial(ctx, str(args["identifier"]))
	case "search":
		return c.Search(ctx, str(args["text"]), &zora.SearchParams{EntityType: zora.EntityType(str(args["entityType"])), PageSize: integer(args["pageSize"]), After: str(args["after"])})
	case "tokenInfo":
		return c.TokenInfo(ctx, str(args["address"]), &zora.TokenInfoParams{ChainID: integer(args["chainId"])})
	case "topLiveStreams":
		return c.TopLiveStreams(ctx, &zora.TopLiveStreamsParams{PageSize: integer(args["pageSize"]), After: str(args["after"])})
	case "traderLeaderboard":
		return c.TraderLeaderboard(ctx, &zora.TraderLeaderboardParams{Week: integer(args["week"]), Year: integer(args["year"]), PageSize: integer(args["pageSize"]), After: str(args["after"])})
	case "trendCoin":
		return c.TrendCoin(ctx, str(args["ticker"]), &zora.TrendCoinParams{ChainID: integer(args["chainId"])})
	case "trendsByName":
		return c.TrendsByName(ctx, str(args["name"]), &zora.TrendsByNameParams{PageSize: integer(args["pageSize"]), After: str(args["after"])})
	case "walletTradeActivity":
		return c.WalletTradeActivity(ctx, str(args["identifier"]), &zora.WalletTradeActivityParams{After: str(args["after"]), PageSize: integer(args["pageSize"])})
	case "quote":
		var body zora.QuoteRequest
		if err := remarshal(args["input"], &body); err != nil {
			return nil, err
		}
		return c.Quote(ctx, &body)
	case "createContentCoin":
		var body zora.CreateContentCoinRequest
		if err := remarshal(args["input"], &body); err != nil {
			return nil, err
		}
		return c.CreateContentCoin(ctx, &body)
	case "createUploadJwt":
		var body zora.CreateUploadJWTRequest
		if err := remarshal(args["input"], &body); err != nil {
			return nil, err
		}
		return c.CreateUploadJWT(ctx, &body)
	}
	return nil, errUnknownField(field)
}
