// Code generated by codegen/emit_ts.py from Zora's OpenAPI spec. DO NOT EDIT.

/**
 * Every type the Zora Coins API returns or accepts. Response fields are all optional: the API returns
 * a different selection of a coin's fields from each endpoint, and leaves out some its own spec marks
 * required. Enum types also accept any string, so a value Zora adds later still type-checks.
 * @module
 */

/** What a coin represents: a creator, a piece of content, or a trend. */
export const CoinType = {
  Creator: "CREATOR",
  Content: "CONTENT",
  Trend: "TREND",
} as const;
/** What a coin represents: a creator, a piece of content, or a trend. */
export type CoinType = (typeof CoinType)[keyof typeof CoinType] | (string & {});

/** What a new content coin trades against. */
export const ContentCoinCurrency = {
  CreatorCoin: "CREATOR_COIN",
  Zora: "ZORA",
  Eth: "ETH",
  CreatorCoinOrZora: "CREATOR_COIN_OR_ZORA",
} as const;
/** What a new content coin trades against. */
export type ContentCoinCurrency = (typeof ContentCoinCurrency)[keyof typeof ContentCoinCurrency] | (string & {});

/** What a new coin's pool trades against. */
export const CurrencyType = {
  Eth: "ETH",
  Zora: "ZORA",
  CreatorCoin: "CREATOR_COIN",
  CreatorCoinOrZora: "CREATOR_COIN_OR_ZORA",
  CustomCoin: "CUSTOM_COIN",
} as const;
/** What a new coin's pool trades against. */
export type CurrencyType = (typeof CurrencyType)[keyof typeof CurrencyType] | (string & {});

/** What kind of thing a search result is. */
export const EntityType = {
  UserProfile: "USER_PROFILE",
  Content: "CONTENT",
  Trend: "TREND",
  Coin: "COIN",
} as const;
/** What kind of thing a search result is. */
export type EntityType = (typeof EntityType)[keyof typeof EntityType] | (string & {});

/** Whether a social account was linked or unlinked. */
export const EventType = {
  Link: "LINK",
  Unlink: "UNLINK",
} as const;
/** Whether a social account was linked or unlinked. */
export type EventType = (typeof EventType)[keyof typeof EventType] | (string & {});

/** Which Zora Explore list to fetch. */
export const ListType = {
  TopGainers: "TOP_GAINERS",
  TopVolume24h: "TOP_VOLUME_24H",
  MostValuable: "MOST_VALUABLE",
  MostValuableTrends: "MOST_VALUABLE_TRENDS",
  New: "NEW",
  NewTrends: "NEW_TRENDS",
  Old: "OLD",
  LastTraded: "LAST_TRADED",
  LastTradedUnique: "LAST_TRADED_UNIQUE",
  Featured: "FEATURED",
  FeaturedVideos: "FEATURED_VIDEOS",
  NewCreators: "NEW_CREATORS",
  MostValuableCreators: "MOST_VALUABLE_CREATORS",
  FeaturedCreators: "FEATURED_CREATORS",
  TopVolumeCreators24h: "TOP_VOLUME_CREATORS_24H",
  TopVolumeAll24h: "TOP_VOLUME_ALL_24H",
  NewAll: "NEW_ALL",
  TrendingPosts: "TRENDING_POSTS",
  TrendingTrends: "TRENDING_TRENDS",
  TrendingCreators: "TRENDING_CREATORS",
  TrendingAll: "TRENDING_ALL",
  TopVolumeTrends24h: "TOP_VOLUME_TRENDS_24H",
  MostValuableAll: "MOST_VALUABLE_ALL",
  TrendingAgents: "TRENDING_AGENTS",
  MostValuableAgents: "MOST_VALUABLE_AGENTS",
} as const;
/** Which Zora Explore list to fetch. */
export type ListType = (typeof ListType)[keyof typeof ListType] | (string & {});

/** How coin metadata is supplied. Only RAW_URI is supported. */
export const MetadataType = {
  RawUri: "RAW_URI",
} as const;
/** How coin metadata is supplied. Only RAW_URI is supported. */
export type MetadataType = (typeof MetadataType)[keyof typeof MetadataType] | (string & {});

/** A social network Zora profiles link to. */
export const Platform = {
  Twitter: "TWITTER",
  Tiktok: "TIKTOK",
  Farcaster: "FARCASTER",
  Instagram: "INSTAGRAM",
} as const;
/** A social network Zora profiles link to. */
export type Platform = (typeof Platform)[keyof typeof Platform] | (string & {});

/** How to order a profile's balances. */
export const SortOption = {
  Balance: "BALANCE",
  MarketCap: "MARKET_CAP",
  UsdValue: "USD_VALUE",
  PriceChange: "PRICE_CHANGE",
  MarketValueUsd: "MARKET_VALUE_USD",
} as const;
/** How to order a profile's balances. */
export type SortOption = (typeof SortOption)[keyof typeof SortOption] | (string & {});

/** The starting market cap tier for a new coin. */
export const StartingMarketCap = {
  Low: "LOW",
  High: "HIGH",
} as const;
/** The starting market cap tier for a new coin. */
export type StartingMarketCap = (typeof StartingMarketCap)[keyof typeof StartingMarketCap] | (string & {});

/** Whether a trade was a buy or a sell. */
export const SwapType = {
  Buy: "BUY",
  Sell: "SELL",
} as const;
/** Whether a trade was a buy or a sell. */
export type SwapType = (typeof SwapType)[keyof typeof SwapType] | (string & {});

/** Native ETH or an ERC-20. */
export const TokenType = {
  Eth: "eth",
  Erc20: "erc20",
} as const;
/** Native ETH or an ERC-20. */
export type TokenType = (typeof TokenType)[keyof typeof TokenType] | (string & {});

/** How a wallet linked to a profile is held. */
export const WalletType = {
  Privy: "PRIVY",
  External: "EXTERNAL",
  SmartWallet: "SMART_WALLET",
} as const;
/** How a wallet linked to a profile is held. */
export type WalletType = (typeof WalletType)[keyof typeof WalletType] | (string & {});

/** A Zora API object. */
export interface Amount {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** The currency (WETH, ZORA, USDC or a creator coin). */
  currencyAddress?: string | null;
  /** Amount in the currency's smallest unit, as an integer string. */
  amountRaw?: string | null;
  /** Amount in whole units of the currency. */
  amountDecimal?: number | null;
}

/** Whether an API key exists and is active. */
export interface ApiKey {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** The API key. */
  apiKey?: string | null;
  /** Whether the key is active. */
  isActive?: boolean | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface ApiKeyResponse {
  /** The API key. */
  apiKey?: ApiKey | null;
}

/** A Zora API object. */
export interface Avatar {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Resized preview of the image. */
  previewImage?: PreviewImage | null;
  /** Small avatar image URL. */
  small?: string | null;
  /** Medium avatar image URL. */
  medium?: string | null;
  /** BlurHash placeholder to show while the image loads. */
  blurhash?: string | null;
}

/** A transaction to send from the user's wallet: target (to), calldata and ETH value. */
export interface Call {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Calldata (0x hex). */
  data?: string | null;
  /** ETH to send with the transaction, in wei, as an integer string. */
  value?: string | null;
  /** Contract to send the transaction to. */
  target?: string | null;
  /** Same as target. */
  to?: string | null;
}

/** One coin a profile holds, with the balance and the coin itself. */
export interface CoinBalance {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Amount held, in the coin's smallest unit (18 decimals). */
  balance?: string | null;
  /** Amount held in the profile's own wallets, in the smallest unit (18 decimals). */
  walletBalance?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** What the holding is worth. */
  valuation?: Valuation | null;
  /** The coin. */
  coin?: Zora20Token | null;
}

/**
 * One page of CoinBalance results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface CoinBalanceConnection {
  /** Total number of items, where the API reports it. */
  count?: number | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: CoinBalanceEdge[] | null;
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
}

/** Wraps one CoinBalance in a page of results. */
export interface CoinBalanceEdge {
  /** The item. */
  node?: CoinBalance | null;
}

/** The compact form of a coin returned by the coins list. */
export interface CoinBasicInfo {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Creator, content or trend coin. */
  coinType?: CoinType | null;
  /** Price in USDC (≈ USD), as a decimal string. */
  priceUsdc?: string | null;
  /** Name of the coin. */
  entityName?: string | null;
  /** Display name. */
  name?: string | null;
  /** Ticker symbol. */
  symbol?: string | null;
  /** Metadata URI. */
  uri?: string | null;
  /** Contract address of the coin. */
  coinAddress?: string | null;
  /** Wallet that created the coin. */
  createdUserAddress?: string | null;
  /** Date with time (isoformat) */
  createdTimestamp?: string | null;
  /** True if Zora hides this from its own app. */
  platformBlocked?: boolean | null;
}

/**
 * One page of CoinBasicInfo results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface CoinBasicInfoConnection {
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: CoinBasicInfoEdge[] | null;
}

/** Wraps one CoinBasicInfo in a page of results. */
export interface CoinBasicInfoEdge {
  /** The item. */
  node?: CoinBasicInfo | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CoinCommentsResponse {
  /** The result. Client methods return this field directly. */
  zora20Token?: Zora20Token | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CoinHoldersResponse {
  /** The result. Client methods return this field directly. */
  zora20Token?: Zora20Token | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CoinMergedCommentsResponse {
  /** The result. Client methods return this field directly. */
  zora20Token?: Zora20Token | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CoinPriceHistoryResponse {
  /** The result. Client methods return this field directly. */
  zora20Token?: Zora20Token | null;
}

/** A coin to fetch with Coins: its chain and contract address. */
export interface CoinRefInput {
  /** Chain ID (8453 = Base). */
  chainId: number;
  /** Contract address of the coin. */
  collectionAddress: string;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CoinResponse {
  /** The result. Client methods return this field directly. */
  zora20Token?: Zora20Token | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CoinSwapsResponse {
  /** The result. Client methods return this field directly. */
  zora20Token?: Zora20Token | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CoinsListResponse {
  /** The result. Client methods return this field directly. */
  coinsBasicInfo?: CoinBasicInfoConnection | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CoinsResponse {
  /** The result. Client methods return this field directly. */
  zora20Tokens?: Zora20Token[] | null;
}

/** A comment in a coin's merged feed or on a live stream. */
export interface Comment {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** ID of the comment. */
  commentId?: string | null;
  /** Nonce the comment was signed or posted with. */
  nonce?: string | null;
  /** Wallet of the user who posted it. */
  userAddress?: string | null;
  /** Hash of the transaction that posted it onchain, if it was posted onchain. */
  txHash?: string | null;
  /** The comment text. */
  comment?: string | null;
  /** When it happened (Unix seconds). */
  timestamp?: number | null;
  /** Profile of the user who posted it. */
  userProfile?: UserProfile | null;
  /** Replies to this comment. */
  replies?: Replies | null;
  /** Contract of the coin the comment is on. */
  contractAddress?: string | null;
  /** The comment text. */
  text?: string | null;
  /** Date with time (isoformat) */
  commentedAt?: string | null;
  /** Onchain ID of the comment this replies to, if any. */
  replyToOnChainId?: string | null;
  /** Offchain ID of the comment this replies to, if any. */
  replyToOffChainId?: string | null;
  /** Sparks (Zora's likes) the comment received. */
  sparkCount?: number | null;
  /** The profile. */
  profile?: Profile | null;
  /** Globally unique ID. */
  id?: string | null;
}

/** One page of Comment results. `nodes(page)` lists them; PageInfo says how to get the next page. */
export interface CommentConnection {
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
  /** Total number of items, where the API reports it. */
  count?: number | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: CommentEdge[] | null;
}

/** Wraps one Comment in a page of results. */
export interface CommentEdge {
  /** The item. */
  node?: Comment | null;
  /** Cursor pointing at this item. */
  cursor?: string | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface ContentCoinPoolConfigResponse {
  /** The result. Client methods return this field directly. */
  contentCoinPoolConfig?: PoolConfig | null;
}

/** A content coin to create. Metadata must point at EIP-7572 JSON (ipfs:// or https://). */
export interface CreateContentCoinRequest {
  /** Wallet creating the coin. */
  creator: string;
  /** Display name. */
  name: string;
  /** Ticker symbol. */
  symbol: string;
  /** Where the coin's EIP-7572 metadata lives. */
  metadata: MetadataInput;
  /** The currency. */
  currency: ContentCoinCurrency;
  /** Chain ID (8453 = Base). */
  chainId?: number;
  /** Starting market cap tier. */
  startingMarketCap?: StartingMarketCap;
  /** Your app's address: it earns the platform referral share of this coin's trading fees for good. */
  platformReferrer?: string;
  /** More wallets allowed to manage the coin. */
  additionalOwners?: string[];
  /** Wallet to receive the creator's fee share instead of the creator. */
  payoutRecipientOverride?: string;
  /** Optional flag to enable smart wallet routing. Defaults to false if omitted. */
  enableSmartWalletRouting?: boolean;
}

/** The calls that create a content coin, and the address it will have. */
export interface CreateContentCoinResponse {
  /** Transactions to send from the creator's wallet, in order. */
  calls?: Call[] | null;
  /** The address the coin will have once created. */
  predictedCoinAddress?: string | null;
  /** The result. Client methods return this field directly. */
  backingCurrency?: string | null;
  /** The result. Client methods return this field directly. */
  usedSmartWalletRouting?: boolean | null;
}

/** Who the upload token is for. */
export interface CreateUploadJwtRequest {
  /** Wallet the upload token is for. */
  creatorAddress: string;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CreateUploadJwtResponse {
  /** The result. Client methods return this field directly. */
  createUploadJwtFromApiKey?: string | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CreatorCoinPoolConfigResponse {
  /** The result. Client methods return this field directly. */
  creatorCoinPoolConfig?: PoolConfig | null;
}

/** What a coin's creator has earned from trading fees, in one currency. */
export interface CreatorEarning {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** The amount. */
  amount?: Amount | null;
  /** The amount in USD. */
  amountUsd?: string | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface CreatorLivestreamCommentsResponse {
  /** The result. Client methods return this field directly. */
  zora20Token?: Zora20Token | null;
}

/** The profile of the creator behind a coin. */
export interface CreatorProfile {
  /** The profile kind, e.g. GraphQLAccountProfile. */
  __typename?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6). */
  handle?: string | null;
  /** True if Zora hides this from its own app. */
  platformBlocked?: boolean | null;
  /** Profile picture. */
  avatar?: Avatar | null;
  /** Linked social accounts: X, TikTok, Instagram, Farcaster. */
  socialAccounts?: SocialAccounts | null;
  /** The creator's own creator coin. */
  creatorCoin?: Zora20Token | null;
  /** The creator's live stream, if any. */
  liveStream?: LiveStream | null;
}

/** A Zora API object. */
export interface Currency {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Current USD price of one whole token, as a decimal string. */
  priceUsd?: string | null;
  /** Token decimals (18 for most, 6 for USDC). */
  decimals?: number | null;
  /** Display name. */
  name?: string | null;
  /** Ticker symbol. */
  symbol?: string | null;
  /** Token icon URL. */
  icon?: string | null;
}

/** A Zora API object. */
export interface CurrencyAmountWithPrice {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** USD price of one unit of the currency at the time of the swap. */
  priceUsdc?: string | null;
  /** Amount paid or received, in the pool's currency. */
  currencyAmount?: Amount | null;
  /** The amount in USD. */
  amountUsd?: string | null;
  /** Change in the currency's price over the last 24 hours. */
  priceDelta24h?: string | null;
}

/** A Zora API object. */
export interface Details {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Token address. */
  token?: string | null;
  /** The amount. */
  amount?: string | null;
  /** When the allowance expires (Unix seconds). */
  expiration?: number | null;
  /** Nonce the comment was signed or posted with. */
  nonce?: number | null;
}

/** A Zora API object. */
export interface DetailsInput {
  /** Token address. */
  token: string;
  /** The amount. */
  amount: string;
  /** When the allowance expires (Unix seconds). */
  expiration: number;
  /** Nonce the comment was signed or posted with. */
  nonce: number;
}

/** ERC-20 metadata and price for any token. */
export interface Erc20Token {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** The token's symbol, decimals and USD price. */
  currency?: Currency | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface ExploreResponse {
  /** The result. Client methods return this field directly. */
  exploreList?: Zora20TokenConnection | null;
}

/** A Zora API object. */
export interface ExternalWallet {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** ENS name of the wallet, if it has one. */
  ensName?: string | null;
  /** Wallet address. */
  walletAddress?: string | null;
}

/** A creator featured on the weekly leaderboard. */
export interface FeaturedCreator {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6). */
  handle?: string | null;
}

/**
 * One page of FeaturedCreator results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface FeaturedCreatorConnection {
  /** Total number of items, where the API reports it. */
  count?: number | null;
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: FeaturedCreatorEdge[] | null;
}

/** Wraps one FeaturedCreator in a page of results. */
export interface FeaturedCreatorEdge {
  /** The item. */
  node?: FeaturedCreator | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface FeaturedCreatorsResponse {
  /** The result. Client methods return this field directly. */
  traderLeaderboardFeaturedCreators?: FeaturedCreatorConnection | null;
}

/** A Zora API object. */
export interface Followers {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Total number of items, where the API reports it. */
  count?: number | null;
}

/** A Zora API object. */
export interface Instagram {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Username on that network. */
  username?: string | null;
  /** Display name on that network. */
  displayName?: string | null;
  /** Followers on that network. */
  followerCount?: number | null;
  /** Globally unique ID. */
  id?: string | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface LatestLiveStreamsResponse {
  /** The result. Client methods return this field directly. */
  latestLiveStreams?: LiveStreamConnection | null;
}

/** Wraps one LinkedWallet in a page of results. */
export interface LinkedWalletEdge {
  /** The item. */
  node?: PublicWallet | null;
}

/** A Zora API object. */
export interface LinkedWallets {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: LinkedWalletEdge[] | null;
}

/** A creator's live stream. */
export interface LiveStream {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Comments. */
  comments?: CommentConnection | null;
  /** Globally unique ID. */
  id?: string | null;
  /** Whether the stream is live right now. */
  isOnline?: boolean | null;
  /** Whether the key is active. */
  isActive?: boolean | null;
  /** People watching right now. */
  concurrentViewers?: number | null;
  /** Still thumbnail image URL. */
  staticThumbnailUrl?: string | null;
  /** Animated thumbnail URL. */
  animatedThumbnailUrl?: string | null;
  /** Profile of the creator. */
  creatorProfile?: CreatorProfile | null;
}

/**
 * One page of LiveStream results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface LiveStreamConnection {
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: LiveStreamEdge[] | null;
}

/** Wraps one LiveStream in a page of results. */
export interface LiveStreamEdge {
  /** The item. */
  node?: LiveStream | null;
}

/** A Zora API object. */
export interface MaxSwappable {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Raw amount of the currency, in wei. Not formatted with decimals */
  amountRaw?: string | null;
  /** Amount of the currency, in float format accounting for currency decimals */
  amountDecimal?: number | null;
}

/** The image, video or other media attached to a coin. */
export interface MediaContent {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** MIME type of the original media. */
  mimeType?: string | null;
  /** The original media file (often ipfs://). */
  originalUri?: string | null;
  /** Resized previews served over https. */
  previewImage?: PreviewImage | null;
  /** Short video preview URL. */
  videoPreviewUrl?: string | null;
  /** HLS stream URL of the video. */
  videoHlsUrl?: string | null;
}

/** A Zora API object. */
export interface MetadataInput {
  /** eth for native ETH, erc20 for a token (which then needs an address). */
  type: MetadataType;
  /** Metadata URI. */
  uri: string;
}

/** A Zora API object. */
export interface OwnerProfile {
  /** GraphQLAccountProfile for a Zora account, GraphQLWalletProfile for a bare wallet. */
  __typename?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6). */
  handle?: string | null;
  /** True if Zora hides this from its own app. */
  platformBlocked?: boolean | null;
  /** Profile picture. */
  avatar?: Avatar | null;
}

/**
 * Where a page sits in a paginated list. Pass EndCursor as After to get the next page while
 * HasNextPage is true.
 */
export interface PageInfo {
  /** Cursor to pass as After for the next page. */
  endCursor?: string | null;
  /** Whether another page follows. */
  hasNextPage?: boolean | null;
  /** Cursor of the first item on this page. */
  startCursor?: string | null;
}

/** A Zora API object. */
export interface Permit {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** When the signature stops being valid (Unix seconds). */
  sigDeadline?: string | null;
  /** Contract allowed to spend the tokens. */
  spender?: string | null;
  /** What the permit allows: token, amount, expiry, nonce. */
  details?: Details | null;
}

/** A Zora API object. */
export interface PermitInput {
  /** What the permit allows: token, amount, expiry, nonce. */
  details: DetailsInput;
  /** Contract allowed to spend the tokens. */
  spender: string;
  /** When the signature stops being valid (Unix seconds). */
  sigDeadline: string;
}

/**
 * The pool configuration Zora uses to launch a coin: encoded config plus the currency it pairs
 * with.
 */
export interface PoolConfig {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** The pool configuration, ABI-encoded as the coin factory expects it. */
  encodedConfig?: string | null;
  /** The currency. */
  currency?: string | null;
  /** Lower tick of each liquidity position the pool starts with. */
  lowerTicks?: number[] | null;
  /** Upper tick of each liquidity position the pool starts with. */
  upperTicks?: number[] | null;
  /** Number of price-discovery liquidity positions per range. */
  numDiscoveryPositions?: number[] | null;
  /** Share of supply placed in each discovery range, in 18-decimal fixed point. */
  maxDiscoverySupplyShares?: string[] | null;
}

/** The currency a coin's pool trades against (ZORA, ETH, USDC or a creator coin). */
export interface PoolCurrencyToken {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Contract address (lowercase 0x hex). */
  address?: string | null;
  /** Display name. */
  name?: string | null;
  /** Token decimals (18 for most, 6 for USDC). */
  decimals?: number | null;
}

/** A Zora API object. */
export interface PreviewImage {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** BlurHash placeholder to show while the image loads. */
  blurhash?: string | null;
  /** Medium preview image URL. */
  medium?: string | null;
  /** Small preview image URL. */
  small?: string | null;
}

/** The price of a coin at a moment in time. */
export interface PricePoint {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Start of the interval (ISO 8601, UTC). */
  timestamp?: string | null;
  /** Price at the end of the interval, in USD. */
  closePrice?: string | null;
}

/**
 * A Zora profile: handle, avatar, linked wallets, creator coin, and (depending on the call) the
 * coins it created or holds.
 */
export interface Profile {
  /** The profile kind, e.g. GraphQLAccountProfile. */
  __typename?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6). */
  handle?: string | null;
  /** Profile picture. */
  avatar?: Avatar | null;
  /** True if Zora hides this from its own app. */
  platformBlocked?: boolean | null;
  /** Linked social accounts: X, TikTok, Instagram, Farcaster. */
  socialAccounts?: SocialAccounts | null;
  /** The creator's own creator coin. */
  creatorCoin?: Zora20Token | null;
  /** Username on that network. */
  username?: string | null;
  /** When it was created (ISO 8601, UTC). */
  createdAt?: string | null;
  /** Display name on that network. */
  displayName?: string | null;
  /** Profile bio. */
  bio?: string | null;
  /** Website on the profile. */
  website?: string | null;
  /** The profile's primary public wallet. */
  publicWallet?: PublicWallet | null;
  /** Wallets linked to the profile. */
  linkedWallets?: LinkedWallets | null;
  /** Coins the profile holds (only filled by the profile-balances endpoint). */
  coinBalances?: CoinBalanceConnection | null;
  /** Coins the profile created (only filled by the profile-coins endpoint). */
  createdCoins?: Zora20TokenConnection | null;
  /** How many times the handle has been changed. */
  usernameChangesCount?: number | null;
  /** An external wallet linked to the profile. */
  externalWallet?: ExternalWallet | null;
  /** Who follows this profile. */
  followers?: Followers | null;
  /** Who this profile follows. */
  following?: Followers | null;
  /** History of social accounts being linked and unlinked. */
  socialAccountLinkedEvents?: SocialAccountLinkedEvents | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface ProfileBalancesResponse {
  /** The profile. */
  profile?: Profile | null;
}

/** A Zora API object. */
export interface ProfileBySocialHandle {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6). */
  handle?: string | null;
  /** True if Zora hides this from its own app. */
  platformBlocked?: boolean | null;
  /** Profile picture. */
  avatar?: Avatar | null;
  /** Linked social accounts: X, TikTok, Instagram, Farcaster. */
  socialAccounts?: SocialAccounts | null;
  /** The creator's own creator coin. */
  creatorCoin?: Zora20Token | null;
  /** Username on that network. */
  username?: string | null;
  /** Display name on that network. */
  displayName?: string | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface ProfileBySocialHandleResponse {
  /** The result. Client methods return this field directly. */
  profileBySocialHandle?: ProfileBySocialHandle | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface ProfileCoinsResponse {
  /** The profile. */
  profile?: Profile | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface ProfileResponse {
  /** The profile. */
  profile?: Profile | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface ProfileSocialResponse {
  /** The profile. */
  profile?: Profile | null;
}

/** A Zora API object. */
export interface PublicWallet {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Wallet address. */
  walletAddress?: string | null;
  /** How the wallet is held (Privy, external, smart wallet). */
  walletType?: WalletType | null;
}

/** What a trade is expected to return. */
export interface Quote {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Expected output, in the output token's smallest unit. */
  amountOut?: string | null;
  /** Slippage tolerance the quote was built with (0.05 = 5%). */
  slippage?: number | null;
  /** The token being sold. */
  tokenIn?: TokenSpec | null;
}

/**
 * A trade to quote. TokenIn, TokenOut, AmountIn and Sender are required; Recipient defaults to
 * Sender and Slippage to 0.05.
 */
export interface QuoteRequest {
  /** Address that earns the trade referral reward for routing this trade. */
  referrer?: string;
  /** Permit2 signatures, when selling an ERC-20 without a prior approval. */
  signatures?: SignatureInput[];
  /** How long a Permit2 signature stays valid, in seconds. */
  permitActiveSeconds?: number;
  /** Chain ID (8453 = Base). */
  chainId?: number;
  /** What to buy. Use ETH() or ERC20(address). */
  tokenOut: TokenSpecInput;
  /** What to sell. Use ETH() or ERC20(address). */
  tokenIn: TokenSpecInput;
  /** Amount to sell, in the input token's smallest unit (wei for ETH). */
  amountIn: string;
  /** Maximum slippage (0.05 = 5%). Defaults to 5% with QuoteTrade. */
  slippage?: number;
  /** Wallet that receives the output. Defaults to the sender with QuoteTrade. */
  recipient?: string;
  /** Wallet that will send the transaction. */
  sender: string;
}

/** A trade quote and the transaction that executes it. */
export interface QuoteResponse {
  /** Whether a route was found. Sent by the API as a string; the SDKs read it as a boolean. */
  success?: boolean | null;
  /** The transaction to send from the sender's wallet. */
  call?: Call | null;
  /** Permit2 permits the sender must sign first, when selling an ERC-20. */
  permits?: SignedPermit[] | null;
  /** The Universal Router trade encoded in the call. */
  trade?: Trade | null;
  /** What the trade is expected to return. */
  quote?: Quote | null;
}

/** A Zora API object. */
export interface Replies {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Total number of items, where the API reports it. */
  count?: number | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: ReplyEdge[] | null;
}

/** A Zora API object. */
export interface Reply {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** ID of the comment. */
  commentId?: string | null;
  /** Nonce the comment was signed or posted with. */
  nonce?: string | null;
  /** Wallet of the user who posted it. */
  userAddress?: string | null;
  /** Hash of the transaction that posted it onchain, if it was posted onchain. */
  txHash?: string | null;
  /** The comment text. */
  comment?: string | null;
  /** When it happened (Unix seconds). */
  timestamp?: number | null;
  /** Profile of the user who posted it. */
  userProfile?: UserProfile | null;
  /** Contract of the coin the comment is on. */
  contractAddress?: string | null;
  /** The comment text. */
  text?: string | null;
  /** Date with time (isoformat) */
  commentedAt?: string | null;
  /** Onchain ID of the comment this replies to, if any. */
  replyToOnChainId?: string | null;
  /** Offchain ID of the comment this replies to, if any. */
  replyToOffChainId?: string | null;
  /** Sparks (Zora's likes) the comment received. */
  sparkCount?: number | null;
  /** The profile. */
  profile?: Profile | null;
}

/** Wraps one Reply in a page of results. */
export interface ReplyEdge {
  /** The item. */
  node?: Reply | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface SearchResponse {
  /** The result. Client methods return this field directly. */
  globalSearch?: SearchResultConnection | null;
}

/** One search hit: a profile, a coin, a piece of content or a trend. */
export interface SearchResult {
  /**
   * What was found: GlobalSearchCoinResult, GlobalSearchTrendResult or
   * GlobalSearchUserProfileResult.
   */
  __typename?: string | null;
  /** What kind of thing this result is. */
  entityType?: EntityType | null;
  /** The profile. */
  profile?: Profile | null;
  /** The coin. */
  coin?: Zora20Token | null;
  /** The trend coin, for trend search results. */
  trend?: Zora20Token | null;
}

/**
 * One page of SearchResult results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface SearchResultConnection {
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: SearchResultEdge[] | null;
}

/** Wraps one SearchResult in a page of results. */
export interface SearchResultEdge {
  /** Cursor pointing at this item. */
  cursor?: string | null;
  /** The item. */
  node?: SearchResult | null;
}

/** A Zora API object. */
export interface SignatureInput {
  /** The Permit2 permit. */
  permit: PermitInput;
  /** The signature. */
  signature: string;
}

/** A Zora API object. */
export interface SignedPermit {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** The signature. */
  signature?: string | null;
  /** The Permit2 permit. */
  permit?: Permit | null;
}

/** A Zora API object. */
export interface SocialAccountLinkedEvent {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** The social network. */
  platform?: Platform | null;
  /** Username on the social network. */
  socialAccountUsername?: string | null;
  /** Date with time (isoformat) */
  occurredAt?: string | null;
  /** Whether the account was linked or unlinked. */
  eventType?: EventType | null;
}

/** Wraps one SocialAccountLinkedEvent in a page of results. */
export interface SocialAccountLinkedEventEdge {
  /** The item. */
  node?: SocialAccountLinkedEvent | null;
}

/** A Zora API object. */
export interface SocialAccountLinkedEvents {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: SocialAccountLinkedEventEdge[] | null;
}

/** A Zora API object. */
export interface SocialAccounts {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Linked Instagram account. */
  instagram?: Instagram | null;
  /** Linked TikTok account. */
  tiktok?: Instagram | null;
  /** Linked X (Twitter) account. */
  twitter?: Instagram | null;
  /** Linked Farcaster account. */
  farcaster?: Instagram | null;
}

/** One buy or sell of a coin. */
export interface SwapActivity {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** Amount in the pool's currency, with the currency's USD price at the time. */
  currencyAmountWithPrice?: CurrencyAmountWithPrice | null;
  /** Wallet that sent the swap. */
  senderAddress?: string | null;
  /** Wallet that received the output. */
  recipientAddress?: string | null;
  /** Hash of the transaction it happened in. */
  transactionHash?: string | null;
  /** Coins bought or sold, in the smallest unit (18 decimals). */
  coinAmount?: string | null;
  /** Time of the block it happened in (ISO 8601, UTC). */
  blockTimestamp?: string | null;
  /** BUY or SELL. */
  activityType?: SwapType | null;
  /** Profile of the wallet that sent the trade. */
  senderProfile?: OwnerProfile | null;
}

/**
 * One page of SwapActivity results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface SwapActivityConnection {
  /** Total number of items, where the API reports it. */
  count?: number | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: SwapActivityEdge[] | null;
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
}

/** Wraps one SwapActivity in a page of results. */
export interface SwapActivityEdge {
  /** The item. */
  node?: SwapActivity | null;
  /** Cursor pointing at this item. */
  cursor?: string | null;
}

/** One holder of a coin and how much they hold. */
export interface TokenBalance {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Amount held, in the coin's smallest unit (18 decimals) — divide by 1e18 for whole coins. */
  balance?: string | null;
  /** Wallet holding the coin. */
  ownerAddress?: string | null;
  /** Profile of the holder (a wallet profile if the holder has no Zora account). */
  ownerProfile?: OwnerProfile | null;
}

/**
 * One page of TokenBalance results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface TokenBalanceConnection {
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
  /** Total number of items, where the API reports it. */
  count?: number | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: TokenBalanceEdge[] | null;
}

/** Wraps one TokenBalance in a page of results. */
export interface TokenBalanceEdge {
  /** The item. */
  node?: TokenBalance | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface TokenInfoResponse {
  /** The result. Client methods return this field directly. */
  erc20Token?: Erc20Token | null;
}

/** A coin's current price, in the pool's currency and in USD. */
export interface TokenPrice {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Price of one whole coin in USDC (≈ USD), as a decimal string. */
  priceInUsdc?: string | null;
  /** The coin the price is for. */
  currencyAddress?: string | null;
  /** Price of one whole coin in the pool's currency, as a decimal string. */
  priceInPoolToken?: string | null;
}

/** A token in a trade quote: native ETH or an ERC-20 address. */
export interface TokenSpec {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** eth for native ETH, erc20 for a token (which then needs an address). */
  type?: string | null;
  /** Contract address (lowercase 0x hex). */
  address?: string | null;
}

/**
 * A token to trade: native ETH (type "eth") or an ERC-20 (type "erc20" plus address). Build one
 * with ETH() or ERC20(address).
 */
export interface TokenSpecInput {
  /** eth for native ETH, erc20 for a token (which then needs an address). */
  type: TokenType;
  /** Contract address (lowercase 0x hex). */
  address?: string;
}

/** The raw response envelope. Client methods unwrap it. */
export interface TopLiveStreamsResponse {
  /** The result. Client methods return this field directly. */
  topLiveStreams?: LiveStreamConnection | null;
}

/** A Zora API object. */
export interface Trade {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Universal Router commands the trade executes (hex). */
  commands?: string[] | null;
  /** ETH to send, in wei. */
  value?: string | null;
  /** ABI-encoded input for each command. */
  inputs?: string[] | null;
}

/** One trade made by a wallet. */
export interface TradeActivity {
  /** The activity kind, e.g. GraphQLCoinSwapActivity. */
  __typename?: string | null;
  /** Hash of the transaction it happened in. */
  transactionHash?: string | null;
  /** Index of the swap's log within its transaction. */
  transactionLogIndex?: number | null;
  /** Time of the block it happened in (ISO 8601, UTC). */
  blockTimestamp?: string | null;
  /** Coins traded, in the smallest unit (18 decimals). */
  coinAmount?: string | null;
  /** The coin. */
  coin?: Zora20Token | null;
  /** Globally unique ID. */
  id?: string | null;
  /** BUY or SELL. */
  swapActivityType?: SwapType | null;
  /** Amount in the pool's currency, with the currency's USD price at the time. */
  currencyAmountWithPrice?: CurrencyAmountWithPrice | null;
  /** Profile of the wallet that sent the trade. */
  senderProfile?: OwnerProfile | null;
  /** Zora's ID for the trade. */
  orderId?: string | null;
  /** For a coin launch, how much the creator bought at creation. */
  initialBuyAmount?: string | null;
  /** That initial buy in USD. */
  initialBuyAmountUsd?: number | null;
  /** How many times its value the trade has returned, where Zora computes it. */
  multiplier?: number | null;
  /** Profile of the wallet that made the trade. */
  makerProfile?: OwnerProfile | null;
}

/**
 * One page of TradeActivity results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface TradeActivityConnection {
  /** Total number of items, where the API reports it. */
  count?: number | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: TradeActivityEdge[] | null;
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
}

/** Wraps one TradeActivity in a page of results. */
export interface TradeActivityEdge {
  /** The item. */
  node?: TradeActivity | null;
  /** Cursor pointing at this item. */
  cursor?: string | null;
}

/** One trader's position on the weekly leaderboard. */
export interface TraderLeaderboardEntry {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Name of the coin. */
  entityName?: string | null;
  /** Leaderboard score. */
  score?: number | null;
  /** Trading volume this week in USD. */
  weekVolumeUsd?: number | null;
  /** Trades made this week. */
  weekTradesCount?: number | null;
  /** Gross trading volume this week, in ZORA. */
  weekGrossVolumeZora?: number | null;
  /** Profile of the trader. */
  traderProfile?: FeaturedCreator | null;
}

/**
 * One page of TraderLeaderboardEntry results. `nodes(page)` lists them; PageInfo says how to get
 * the next page.
 */
export interface TraderLeaderboardEntryConnection {
  /** Total number of items, where the API reports it. */
  count?: number | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: TraderLeaderboardEntryEdge[] | null;
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
}

/** Wraps one TraderLeaderboardEntry in a page of results. */
export interface TraderLeaderboardEntryEdge {
  /** The item. */
  node?: TraderLeaderboardEntry | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface TraderLeaderboardResponse {
  /** The result. Client methods return this field directly. */
  exploreTraderLeaderboard?: TraderLeaderboardEntryConnection | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface TrendCoinResponse {
  /** The result. Client methods return this field directly. */
  trendCoin?: Zora20Token | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface TrendsByNameResponse {
  /** The result. Client methods return this field directly. */
  trendsByName?: Zora20TokenConnection | null;
}

/** The Uniswap V4 pool key of a coin's market. */
export interface UniswapV4PoolKey {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** currency0 of the Uniswap V4 pool key. */
  token0Address?: string | null;
  /** currency1 of the Uniswap V4 pool key. */
  token1Address?: string | null;
  /** Pool fee, in hundredths of a basis point. */
  fee?: number | null;
  /** Tick spacing of the pool. */
  tickSpacing?: number | null;
  /** The pool's hook contract (Zora's coin hook). */
  hookAddress?: string | null;
}

/** A Zora API object. */
export interface UserProfile {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6). */
  handle?: string | null;
  /** Profile picture. */
  avatar?: Avatar | null;
}

/** A Zora API object. */
export interface Valuation {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** What the holding would fetch at the current price, in USD. */
  marketValueUsd?: string | null;
  /** Balance × price, in USD, ignoring slippage. */
  faceValueUsd?: string | null;
  /** Block the valuation was computed at. */
  blockNumber?: number | null;
  /** The most of the holding that can be sold into the pool right now. */
  maxSwappable?: MaxSwappable | null;
  /** Amount paid or received, in the pool's currency. */
  currencyAmount?: Amount | null;
  /** Why the valuation couldn't be computed, when it couldn't. */
  error?: string | null;
}

/** The raw response envelope. Client methods unwrap it. */
export interface WalletTradeActivityResponse {
  /** The result. Client methods return this field directly. */
  walletAddressTradeActivity?: TradeActivityConnection | null;
}

/**
 * A Zora coin: an ERC-20 with a Uniswap V4 market, created by a creator or for a piece of content
 * or a trend. Endpoints return different selections of its fields; anything not selected is empty.
 */
export interface Zora20Token {
  /**
   * Which kind of coin this is: GraphQLZora20Token, GraphQLZora20V4Token,
   * GraphQLZora20CreatorToken or GraphQLZora20TrendToken.
   */
  __typename?: string | null;
  /** Globally unique ID. */
  id?: string | null;
  /** True if Zora hides this from its own app. */
  platformBlocked?: boolean | null;
  /** Display name. */
  name?: string | null;
  /** Description from the coin's metadata. */
  description?: string | null;
  /** Contract address (lowercase 0x hex). */
  address?: string | null;
  /** Whether this is a creator coin, a content coin or a trend. */
  coinType?: CoinType | null;
  /** Ticker symbol. */
  symbol?: string | null;
  /** Total supply in whole tokens, as a decimal string ("1000000000" = one billion). */
  totalSupply?: string | null;
  /** All-time trading volume in USD, as a decimal string. */
  totalVolume?: string | null;
  /** Trading volume over the last 24 hours in USD, as a decimal string. */
  volume24h?: string | null;
  /** When it was created (ISO 8601, UTC). */
  createdAt?: string | null;
  /** Wallet that created the coin. */
  creatorAddress?: string | null;
  /** What the coin's pool trades against. */
  poolCurrencyToken?: PoolCurrencyToken | null;
  /** Current price. */
  tokenPrice?: TokenPrice | null;
  /** Market cap in USD, as a decimal string. */
  marketCap?: string | null;
  /**
   * Change in market cap over the last 24 hours in USD (negative when it fell), as a decimal
   * string.
   */
  marketCapDelta24h?: string | null;
  /** Chain ID (8453 = Base). */
  chainId?: number | null;
  /** Metadata URI (EIP-7572 JSON, usually ipfs://). */
  tokenUri?: string | null;
  /** The app that launched the coin; it earns the platform referral share of every trade, for good. */
  platformReferrerAddress?: string | null;
  /** Wallet that receives the creator's share of trading fees. */
  payoutRecipientAddress?: string | null;
  /** Profile of the creator. */
  creatorProfile?: CreatorProfile | null;
  /** The image or video attached to the coin. */
  mediaContent?: MediaContent | null;
  /** Number of distinct wallets holding the coin. */
  uniqueHolders?: number | null;
  /** Pool key of a V4 coin's market. */
  uniswapV4PoolKey?: UniswapV4PoolKey | null;
  /** Pool of a legacy V3 coin. Empty for V4 coins, which use uniswapV4PoolKey. */
  uniswapV3PoolAddress?: string | null;
  /** Comments (only filled by the coin-comments endpoint). */
  zoraComments?: ZoraCommentConnection | null;
  /** What the creator has earned from trading fees, per currency. */
  creatorEarnings?: CreatorEarning[] | null;
  /** Holders (only filled by the coin-holders endpoint). */
  tokenBalances?: TokenBalanceConnection | null;
  /** Comments. */
  comments?: CommentConnection | null;
  /** Prices over the last hour (only filled by the price-history endpoint). */
  oneHour?: PricePoint[] | null;
  /** Prices over the last day. */
  oneDay?: PricePoint[] | null;
  /** Prices over the last week. */
  oneWeek?: PricePoint[] | null;
  /** Prices over the last month. */
  oneMonth?: PricePoint[] | null;
  /** Prices over the coin's whole life. */
  all?: PricePoint[] | null;
  /** Buys and sells (only filled by the coin-swaps endpoint). */
  swapActivities?: SwapActivityConnection | null;
  /** The coin's address on other chains, where Zora reports one. */
  multichainAddress?: string | null;
  /** The coin's Uniswap pool address, where the API reports one. */
  uniswapPoolAddress?: string | null;
}

/**
 * One page of Zora20Token results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface Zora20TokenConnection {
  /** The items on this page, each wrapped in an edge. */
  edges?: Zora20TokenEdge[] | null;
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
  /** Total number of items, where the API reports it. */
  count?: number | null;
}

/** Wraps one Zora20Token in a page of results. */
export interface Zora20TokenEdge {
  /** The item. */
  node?: Zora20Token | null;
  /** Cursor pointing at this item. */
  cursor?: string | null;
}

/** A comment posted on a coin. */
export interface ZoraComment {
  /** The type name Zora's GraphQL backend reports for this object, when it includes one. */
  __typename?: string | null;
  /** ID of the comment. */
  commentId?: string | null;
  /** Nonce the comment was signed or posted with. */
  nonce?: string | null;
  /** Wallet of the user who posted it. */
  userAddress?: string | null;
  /** Hash of the transaction that posted it onchain, if it was posted onchain. */
  txHash?: string | null;
  /** The comment text. */
  comment?: string | null;
  /** When it happened (Unix seconds). */
  timestamp?: number | null;
  /** Profile of the user who posted it. */
  userProfile?: UserProfile | null;
  /** Replies to this comment. */
  replies?: Replies | null;
}

/**
 * One page of ZoraComment results. `nodes(page)` lists them; PageInfo says how to get the next
 * page.
 */
export interface ZoraCommentConnection {
  /** How to fetch the next page. */
  pageInfo?: PageInfo | null;
  /** Total number of items, where the API reports it. */
  count?: number | null;
  /** The items on this page, each wrapped in an edge. */
  edges?: ZoraCommentEdge[] | null;
}

/** Wraps one ZoraComment in a page of results. */
export interface ZoraCommentEdge {
  /** The item. */
  node?: ZoraComment | null;
}

