// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.model.*;
import java.util.List;

/** Optional parameters of ZoraCoins.getCoinsList. Unset values use the API's defaults. */
public final class CoinsListParams {
    private Integer pageSize;
    private String after;
    private Boolean includeUsdcPrice;

    /** Page size. */
    public CoinsListParams pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /** The pageSize set, or null. */
    public Integer getPageSize() {
        return pageSize;
    }

    /** Cursor to continue from: the previous page's pageInfo.endCursor. */
    public CoinsListParams after(String after) {
        this.after = after;
        return this;
    }

    /** The after set, or null. */
    public String getAfter() {
        return after;
    }

    /** Include each coin's price in USDC. Defaults to true. */
    public CoinsListParams includeUsdcPrice(Boolean includeUsdcPrice) {
        this.includeUsdcPrice = includeUsdcPrice;
        return this;
    }

    /** The includeUsdcPrice set, or null. */
    public Boolean getIncludeUsdcPrice() {
        return includeUsdcPrice;
    }

    /** A copy, so pagination can move the cursor without touching the caller's object. */
    public CoinsListParams copy() {
        CoinsListParams c = new CoinsListParams();
        c.pageSize = pageSize;
        c.after = after;
        c.includeUsdcPrice = includeUsdcPrice;
        return c;
    }
}
