// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.model.*;
import java.util.List;

/** Optional parameters of ZoraCoins.getContentCoinPoolConfig. Unset values use the API's defaults. */
public final class ContentCoinPoolConfigParams {
    private String creatorIdentifier;

    /** Profile handle or wallet of the creator, used to pair with their creator coin. */
    public ContentCoinPoolConfigParams creatorIdentifier(String creatorIdentifier) {
        this.creatorIdentifier = creatorIdentifier;
        return this;
    }

    /** The creatorIdentifier set, or null. */
    public String getCreatorIdentifier() {
        return creatorIdentifier;
    }

    /** A copy, so pagination can move the cursor without touching the caller's object. */
    public ContentCoinPoolConfigParams copy() {
        ContentCoinPoolConfigParams c = new ContentCoinPoolConfigParams();
        c.creatorIdentifier = creatorIdentifier;
        return c;
    }
}
