// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.model.*;
import java.util.List;

/** Optional parameters of ZoraCoins.getCreatorCoinPoolConfig. Unset values use the API's defaults. */
public final class CreatorCoinPoolConfigParams {
    private Long targetMarketCapUsd;

    /** Starting market cap to size the pool for, in USD. */
    public CreatorCoinPoolConfigParams targetMarketCapUsd(Long targetMarketCapUsd) {
        this.targetMarketCapUsd = targetMarketCapUsd;
        return this;
    }

    /** The targetMarketCapUsd set, or null. */
    public Long getTargetMarketCapUsd() {
        return targetMarketCapUsd;
    }

    /** A copy, so pagination can move the cursor without touching the caller's object. */
    public CreatorCoinPoolConfigParams copy() {
        CreatorCoinPoolConfigParams c = new CreatorCoinPoolConfigParams();
        c.targetMarketCapUsd = targetMarketCapUsd;
        return c;
    }
}
