// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.model.*;
import java.util.List;

/** Optional parameters of ZoraCoins.getCreatorLivestreamComments. Unset values use the API's defaults. */
public final class CreatorLivestreamCommentsParams {
    private Long chainId;
    private String after;
    private Integer pageSize;

    /** Chain ID. Defaults to Base (8453). */
    public CreatorLivestreamCommentsParams chainId(Long chainId) {
        this.chainId = chainId;
        return this;
    }

    /** The chainId set, or null. */
    public Long getChainId() {
        return chainId;
    }

    /** Cursor to continue from: the previous page's pageInfo.endCursor. */
    public CreatorLivestreamCommentsParams after(String after) {
        this.after = after;
        return this;
    }

    /** The after set, or null. */
    public String getAfter() {
        return after;
    }

    /** Page size. */
    public CreatorLivestreamCommentsParams pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /** The pageSize set, or null. */
    public Integer getPageSize() {
        return pageSize;
    }

    /** A copy, so pagination can move the cursor without touching the caller's object. */
    public CreatorLivestreamCommentsParams copy() {
        CreatorLivestreamCommentsParams c = new CreatorLivestreamCommentsParams();
        c.chainId = chainId;
        c.after = after;
        c.pageSize = pageSize;
        return c;
    }
}
