// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.model.*;
import java.util.List;

/** Optional parameters of ZoraCoins.explore. Unset values use the API's defaults. */
public final class ExploreParams {
    private Integer pageSize;
    private String after;

    /** Page size. */
    public ExploreParams pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /** The pageSize set, or null. */
    public Integer getPageSize() {
        return pageSize;
    }

    /** Cursor to continue from: the previous page's pageInfo.endCursor. */
    public ExploreParams after(String after) {
        this.after = after;
        return this;
    }

    /** The after set, or null. */
    public String getAfter() {
        return after;
    }

    /** A copy, so pagination can move the cursor without touching the caller's object. */
    public ExploreParams copy() {
        ExploreParams c = new ExploreParams();
        c.pageSize = pageSize;
        c.after = after;
        return c;
    }
}
