// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.internal.Json;
import io.github.pgalyen1987.zora.internal.Pages;
import io.github.pgalyen1987.zora.internal.Query;
import io.github.pgalyen1987.zora.model.*;
import java.util.List;
import java.util.Optional;

/** The endpoint methods, generated. Use {@link ZoraCoins}, which adds conveniences on top. */
abstract class GeneratedClient extends BaseClient {
    GeneratedClient(Builder b) {
        super(b);
    }

    /** Look up an API key: whether it exists and is active. (GET /apiKey) */
    public Optional<ApiKey> getApiKey(String apiKey) {
        Query q = new Query();
        q.add("apiKey", apiKey);
        ApiKeyResponse resp = send("GET", "/apiKey", q, null, ApiKeyResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getApiKey());
    }

    /**
     * One coin by contract address: market data, creator profile, media, pool key and creator
     * earnings. Empty if there is no such coin. (GET /coin)
     */
    public Optional<Zora20Token> getCoin(String address, CoinParams params) {
        CoinParams p = params == null ? new CoinParams() : params;
        Query q = new Query();
        q.add("address", address);
        q.add("chain", String.valueOf(p.getChainId() == null ? BASE_CHAIN_ID : p.getChainId()));
        CoinResponse resp = send("GET", "/coin", q, null, CoinResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getZora20Token());
    }

    /**
     * Comments posted on a coin, newest first. Returns one page; iterateCoinComments walks every page.
     * (GET /coinComments)
     */
    public ZoraCommentConnection getCoinComments(String address, CoinCommentsParams params) {
        CoinCommentsParams p = params == null ? new CoinCommentsParams() : params;
        Query q = new Query();
        q.add("address", address);
        q.add("chain", String.valueOf(p.getChainId() == null ? BASE_CHAIN_ID : p.getChainId()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        if (p.getPageSize() != null) q.add("count", Query.format(p.getPageSize()));
        CoinCommentsResponse resp = send("GET", "/coinComments", q, null, CoinCommentsResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((CoinCommentsResponse) cur).getZora20Token();
        cur = cur == null ? null : ((Zora20Token) cur).getZoraComments();
        return cur == null ? new ZoraCommentConnection() : (ZoraCommentConnection) cur;
    }

    /**
     * Every ZoraComment across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<ZoraComment> iterateCoinComments(String address, CoinCommentsParams params) {
        CoinCommentsParams start = params == null ? new CoinCommentsParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            ZoraCommentConnection page = getCoinComments(address, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * Holders of a coin and their balances, largest first. Returns one page; iterateCoinHolders walks
     * every page. (GET /coinHolders)
     */
    public TokenBalanceConnection getCoinHolders(String address, CoinHoldersParams params) {
        CoinHoldersParams p = params == null ? new CoinHoldersParams() : params;
        Query q = new Query();
        q.add("chainId", String.valueOf(p.getChainId() == null ? BASE_CHAIN_ID : p.getChainId()));
        q.add("address", address);
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        if (p.getPageSize() != null) q.add("count", Query.format(p.getPageSize()));
        CoinHoldersResponse resp = send("GET", "/coinHolders", q, null, CoinHoldersResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((CoinHoldersResponse) cur).getZora20Token();
        cur = cur == null ? null : ((Zora20Token) cur).getTokenBalances();
        return cur == null ? new TokenBalanceConnection() : (TokenBalanceConnection) cur;
    }

    /**
     * Every TokenBalance across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<TokenBalance> iterateCoinHolders(String address, CoinHoldersParams params) {
        CoinHoldersParams start = params == null ? new CoinHoldersParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            TokenBalanceConnection page = getCoinHolders(address, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * A coin's comment feed with replies threaded in, newest first. Returns one page;
     * iterateCoinMergedComments walks every page. (GET /coinMergedComments)
     */
    public CommentConnection getCoinMergedComments(String address, CoinMergedCommentsParams params) {
        CoinMergedCommentsParams p = params == null ? new CoinMergedCommentsParams() : params;
        Query q = new Query();
        q.add("address", address);
        q.add("chain", String.valueOf(p.getChainId() == null ? BASE_CHAIN_ID : p.getChainId()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        if (p.getPageSize() != null) q.add("count", Query.format(p.getPageSize()));
        CoinMergedCommentsResponse resp = send("GET", "/coinMergedComments", q, null, CoinMergedCommentsResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((CoinMergedCommentsResponse) cur).getZora20Token();
        cur = cur == null ? null : ((Zora20Token) cur).getComments();
        return cur == null ? new CommentConnection() : (CommentConnection) cur;
    }

    /**
     * Every Comment across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<Comment> iterateCoinMergedComments(String address, CoinMergedCommentsParams params) {
        CoinMergedCommentsParams start = params == null ? new CoinMergedCommentsParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            CommentConnection page = getCoinMergedComments(address, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * A coin's price history at five resolutions: the last hour, day, week, month, and all time. Empty
     * if there is no such coin. (GET /coinPriceHistory)
     */
    public Optional<Zora20Token> getCoinPriceHistory(String address, CoinPriceHistoryParams params) {
        CoinPriceHistoryParams p = params == null ? new CoinPriceHistoryParams() : params;
        Query q = new Query();
        q.add("address", address);
        q.add("chain", String.valueOf(p.getChainId() == null ? BASE_CHAIN_ID : p.getChainId()));
        CoinPriceHistoryResponse resp = send("GET", "/coinPriceHistory", q, null, CoinPriceHistoryResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getZora20Token());
    }

    /**
     * Buys and sells of a coin, newest first. Returns one page; iterateCoinSwaps walks every page.
     * (GET /coinSwaps)
     */
    public SwapActivityConnection getCoinSwaps(String address, CoinSwapsParams params) {
        CoinSwapsParams p = params == null ? new CoinSwapsParams() : params;
        Query q = new Query();
        q.add("address", address);
        q.add("chain", String.valueOf(p.getChainId() == null ? BASE_CHAIN_ID : p.getChainId()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        if (p.getPageSize() != null) q.add("first", Query.format(p.getPageSize()));
        CoinSwapsResponse resp = send("GET", "/coinSwaps", q, null, CoinSwapsResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((CoinSwapsResponse) cur).getZora20Token();
        cur = cur == null ? null : ((Zora20Token) cur).getSwapActivities();
        return cur == null ? new SwapActivityConnection() : (SwapActivityConnection) cur;
    }

    /**
     * Every SwapActivity across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<SwapActivity> iterateCoinSwaps(String address, CoinSwapsParams params) {
        CoinSwapsParams start = params == null ? new CoinSwapsParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            SwapActivityConnection page = getCoinSwaps(address, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /** Several coins in one request. Missing coins are left out of the result. (GET /coins) */
    public List<Zora20Token> getCoins(List<CoinRefInput> coins) {
        Query q = new Query();
        for (Object item : coins) q.add("coins", Json.write(item));
        CoinsResponse resp = send("GET", "/coins", q, null, CoinsResponse.class);
        return resp == null || resp.getZora20Tokens() == null ? java.util.Collections.emptyList() : resp.getZora20Tokens();
    }

    /**
     * Basic information (address, name, symbol, price) for every coin, in pages of up to 1,000.
     * Returns one page; iterateCoinsList walks every page. (GET /coinsList)
     */
    public CoinBasicInfoConnection getCoinsList(CoinsListParams params) {
        CoinsListParams p = params == null ? new CoinsListParams() : params;
        Query q = new Query();
        if (p.getPageSize() != null) q.add("first", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        if (p.getIncludeUsdcPrice() != null) q.add("includeUSDCPrice", Query.format(p.getIncludeUsdcPrice()));
        CoinsListResponse resp = send("GET", "/coinsList", q, null, CoinsListResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((CoinsListResponse) cur).getCoinsBasicInfo();
        return cur == null ? new CoinBasicInfoConnection() : (CoinBasicInfoConnection) cur;
    }

    /**
     * Every CoinBasicInfo across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<CoinBasicInfo> iterateCoinsList(CoinsListParams params) {
        CoinsListParams start = params == null ? new CoinsListParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            CoinBasicInfoConnection page = getCoinsList(p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * The Uniswap V4 pool configuration Zora uses to launch a content coin paired with the given
     * currency. (GET /contentCoinPoolConfig)
     */
    public Optional<PoolConfig> getContentCoinPoolConfig(CurrencyType currencyType, ContentCoinPoolConfigParams params) {
        ContentCoinPoolConfigParams p = params == null ? new ContentCoinPoolConfigParams() : params;
        Query q = new Query();
        if (p.getCreatorIdentifier() != null) q.add("creatorIdentifier", Query.format(p.getCreatorIdentifier()));
        q.add("currencyType", currencyType.value());
        ContentCoinPoolConfigResponse resp = send("GET", "/contentCoinPoolConfig", q, null, ContentCoinPoolConfigResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getContentCoinPoolConfig());
    }

    /**
     * Create a short-lived token for uploading coin media and metadata to Zora's uploader. Requires an
     * API key. (POST /createUploadJWT)
     */
    public Optional<String> createUploadJwt(CreateUploadJwtRequest request) {
        Query q = new Query();
        CreateUploadJwtResponse resp = send("POST", "/createUploadJWT", q, request, CreateUploadJwtResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getCreateUploadJwtFromApiKey());
    }

    /**
     * The Uniswap V4 pool configuration Zora uses to launch a creator coin, optionally sized for a
     * starting market cap in USD. (GET /creatorCoinPoolConfig)
     */
    public Optional<PoolConfig> getCreatorCoinPoolConfig(CreatorCoinPoolConfigParams params) {
        CreatorCoinPoolConfigParams p = params == null ? new CreatorCoinPoolConfigParams() : params;
        Query q = new Query();
        if (p.getTargetMarketCapUsd() != null) q.add("targetMarketCapUsd", Query.format(p.getTargetMarketCapUsd()));
        CreatorCoinPoolConfigResponse resp = send("GET", "/creatorCoinPoolConfig", q, null, CreatorCoinPoolConfigResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getCreatorCoinPoolConfig());
    }

    /**
     * Comments on the live stream of the creator behind a coin. Returns one page;
     * iterateCreatorLivestreamComments walks every page. (GET /creatorLivestreamComments)
     */
    public CommentConnection getCreatorLivestreamComments(String address, CreatorLivestreamCommentsParams params) {
        CreatorLivestreamCommentsParams p = params == null ? new CreatorLivestreamCommentsParams() : params;
        Query q = new Query();
        q.add("address", address);
        q.add("chain", String.valueOf(p.getChainId() == null ? BASE_CHAIN_ID : p.getChainId()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        if (p.getPageSize() != null) q.add("count", Query.format(p.getPageSize()));
        CreatorLivestreamCommentsResponse resp = send("GET", "/creatorLivestreamComments", q, null, CreatorLivestreamCommentsResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((CreatorLivestreamCommentsResponse) cur).getZora20Token();
        cur = cur == null ? null : ((Zora20Token) cur).getCreatorProfile();
        cur = cur == null ? null : ((CreatorProfile) cur).getLiveStream();
        cur = cur == null ? null : ((LiveStream) cur).getComments();
        return cur == null ? new CommentConnection() : (CommentConnection) cur;
    }

    /**
     * Every Comment across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<Comment> iterateCreatorLivestreamComments(String address, CreatorLivestreamCommentsParams params) {
        CreatorLivestreamCommentsParams start = params == null ? new CreatorLivestreamCommentsParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            CommentConnection page = getCreatorLivestreamComments(address, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * A Zora Explore list: top gainers, 24h volume, newest, most valuable creators and more. See
     * ListType for all 25. Returns one page; iterateExplore walks every page. (GET /explore)
     */
    public Zora20TokenConnection explore(ListType listType, ExploreParams params) {
        ExploreParams p = params == null ? new ExploreParams() : params;
        Query q = new Query();
        q.add("listType", listType.value());
        if (p.getPageSize() != null) q.add("count", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        ExploreResponse resp = send("GET", "/explore", q, null, ExploreResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((ExploreResponse) cur).getExploreList();
        return cur == null ? new Zora20TokenConnection() : (Zora20TokenConnection) cur;
    }

    /**
     * Every Zora20Token across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<Zora20Token> iterateExplore(ListType listType, ExploreParams params) {
        ExploreParams start = params == null ? new ExploreParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            Zora20TokenConnection page = explore(listType, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * Creators featured on the weekly leaderboard. Defaults to the current week. Returns one page;
     * iterateFeaturedCreators walks every page. (GET /featuredCreators)
     */
    public FeaturedCreatorConnection getFeaturedCreators(FeaturedCreatorsParams params) {
        FeaturedCreatorsParams p = params == null ? new FeaturedCreatorsParams() : params;
        Query q = new Query();
        if (p.getYear() != null) q.add("year", Query.format(p.getYear()));
        if (p.getWeek() != null) q.add("week", Query.format(p.getWeek()));
        if (p.getPageSize() != null) q.add("first", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        FeaturedCreatorsResponse resp = send("GET", "/featuredCreators", q, null, FeaturedCreatorsResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((FeaturedCreatorsResponse) cur).getTraderLeaderboardFeaturedCreators();
        return cur == null ? new FeaturedCreatorConnection() : (FeaturedCreatorConnection) cur;
    }

    /**
     * Every FeaturedCreator across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<FeaturedCreator> iterateFeaturedCreators(FeaturedCreatorsParams params) {
        FeaturedCreatorsParams start = params == null ? new FeaturedCreatorsParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            FeaturedCreatorConnection page = getFeaturedCreators(p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * Live streams, most recently started first. Returns one page; iterateLatestLiveStreams walks
     * every page. (GET /latestLiveStreams)
     */
    public LiveStreamConnection getLatestLiveStreams(LatestLiveStreamsParams params) {
        LatestLiveStreamsParams p = params == null ? new LatestLiveStreamsParams() : params;
        Query q = new Query();
        if (p.getPageSize() != null) q.add("first", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        LatestLiveStreamsResponse resp = send("GET", "/latestLiveStreams", q, null, LatestLiveStreamsResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((LatestLiveStreamsResponse) cur).getLatestLiveStreams();
        return cur == null ? new LiveStreamConnection() : (LiveStreamConnection) cur;
    }

    /**
     * Every LiveStream across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<LiveStream> iterateLatestLiveStreams(LatestLiveStreamsParams params) {
        LatestLiveStreamsParams start = params == null ? new LatestLiveStreamsParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            LiveStreamConnection page = getLatestLiveStreams(p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * A profile by handle or wallet address, with its linked wallets and creator coin. Empty if there
     * is no such profile. (GET /profile)
     */
    public Optional<Profile> getProfile(String identifier) {
        Query q = new Query();
        q.add("identifier", identifier);
        ProfileResponse resp = send("GET", "/profile", q, null, ProfileResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getProfile());
    }

    /**
     * Coins a profile holds, with balances and current values. Returns one page;
     * iterateProfileBalances walks every page. (GET /profileBalances)
     */
    public CoinBalanceConnection getProfileBalances(String identifier, ProfileBalancesParams params) {
        ProfileBalancesParams p = params == null ? new ProfileBalancesParams() : params;
        Query q = new Query();
        q.add("identifier", identifier);
        if (p.getPageSize() != null) q.add("count", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        if (p.getSortOption() != null) q.add("sortOption", Query.format(p.getSortOption()));
        if (p.getExcludeHidden() != null) q.add("excludeHidden", Query.format(p.getExcludeHidden()));
        if (p.getChainIds() != null) for (Object v : p.getChainIds()) q.add("chainIds", Query.format(v));
        ProfileBalancesResponse resp = send("GET", "/profileBalances", q, null, ProfileBalancesResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((ProfileBalancesResponse) cur).getProfile();
        cur = cur == null ? null : ((Profile) cur).getCoinBalances();
        return cur == null ? new CoinBalanceConnection() : (CoinBalanceConnection) cur;
    }

    /**
     * Every CoinBalance across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<CoinBalance> iterateProfileBalances(String identifier, ProfileBalancesParams params) {
        ProfileBalancesParams start = params == null ? new ProfileBalancesParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            CoinBalanceConnection page = getProfileBalances(identifier, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * Find a Zora profile from its handle on X, TikTok, Farcaster or Instagram. Empty if there is no
     * such profile. (GET /profileBySocialHandle)
     */
    public Optional<ProfileBySocialHandle> getProfileBySocialHandle(Platform platform, String handle) {
        Query q = new Query();
        q.add("platform", platform.value());
        q.add("handle", handle);
        ProfileBySocialHandleResponse resp = send("GET", "/profileBySocialHandle", q, null, ProfileBySocialHandleResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getProfileBySocialHandle());
    }

    /**
     * Coins a profile created. Filter by platform referrer to list only coins launched through a given
     * app. Returns one page; iterateProfileCoins walks every page. (GET /profileCoins)
     */
    public Zora20TokenConnection getProfileCoins(String identifier, ProfileCoinsParams params) {
        ProfileCoinsParams p = params == null ? new ProfileCoinsParams() : params;
        Query q = new Query();
        q.add("identifier", identifier);
        if (p.getPageSize() != null) q.add("count", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        if (p.getChainIds() != null) for (Object v : p.getChainIds()) q.add("chainIds", Query.format(v));
        if (p.getPlatformReferrerAddress() != null) for (Object v : p.getPlatformReferrerAddress()) q.add("platformReferrerAddress", Query.format(v));
        ProfileCoinsResponse resp = send("GET", "/profileCoins", q, null, ProfileCoinsResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((ProfileCoinsResponse) cur).getProfile();
        cur = cur == null ? null : ((Profile) cur).getCreatedCoins();
        return cur == null ? new Zora20TokenConnection() : (Zora20TokenConnection) cur;
    }

    /**
     * Every Zora20Token across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<Zora20Token> iterateProfileCoins(String identifier, ProfileCoinsParams params) {
        ProfileCoinsParams start = params == null ? new ProfileCoinsParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            Zora20TokenConnection page = getProfileCoins(identifier, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * A profile's linked social accounts (X, TikTok, Instagram, Farcaster) and follower counts. Empty
     * if there is no such profile. (GET /profileSocial)
     */
    public Optional<Profile> getProfileSocial(String identifier) {
        Query q = new Query();
        q.add("identifier", identifier);
        ProfileSocialResponse resp = send("GET", "/profileSocial", q, null, ProfileSocialResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getProfile());
    }

    /**
     * Search coins, profiles, content and trends by text. Returns one page; iterateSearch walks every
     * page. (GET /search)
     */
    public SearchResultConnection search(String text, SearchParams params) {
        SearchParams p = params == null ? new SearchParams() : params;
        Query q = new Query();
        q.add("text", text);
        if (p.getEntityType() != null) q.add("entityType", Query.format(p.getEntityType()));
        if (p.getPageSize() != null) q.add("first", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        SearchResponse resp = send("GET", "/search", q, null, SearchResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((SearchResponse) cur).getGlobalSearch();
        return cur == null ? new SearchResultConnection() : (SearchResultConnection) cur;
    }

    /**
     * Every SearchResult across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<SearchResult> iterateSearch(String text, SearchParams params) {
        SearchParams start = params == null ? new SearchParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            SearchResultConnection page = search(text, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * Symbol, decimals and current USD price of any ERC-20 on the chain: ZORA, USDC, WETH, or a coin.
     * Empty if there is no such coin. (GET /tokenInfo)
     */
    public Optional<Erc20Token> getTokenInfo(String address, TokenInfoParams params) {
        TokenInfoParams p = params == null ? new TokenInfoParams() : params;
        Query q = new Query();
        q.add("address", address);
        q.add("chainId", String.valueOf(p.getChainId() == null ? BASE_CHAIN_ID : p.getChainId()));
        TokenInfoResponse resp = send("GET", "/tokenInfo", q, null, TokenInfoResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getErc20Token());
    }

    /**
     * Live streams with the most viewers right now. Returns one page; iterateTopLiveStreams walks
     * every page. (GET /topLiveStreams)
     */
    public LiveStreamConnection getTopLiveStreams(TopLiveStreamsParams params) {
        TopLiveStreamsParams p = params == null ? new TopLiveStreamsParams() : params;
        Query q = new Query();
        if (p.getPageSize() != null) q.add("first", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        TopLiveStreamsResponse resp = send("GET", "/topLiveStreams", q, null, TopLiveStreamsResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((TopLiveStreamsResponse) cur).getTopLiveStreams();
        return cur == null ? new LiveStreamConnection() : (LiveStreamConnection) cur;
    }

    /**
     * Every LiveStream across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<LiveStream> iterateTopLiveStreams(TopLiveStreamsParams params) {
        TopLiveStreamsParams start = params == null ? new TopLiveStreamsParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            LiveStreamConnection page = getTopLiveStreams(p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * The weekly trader leaderboard. Defaults to the current week. Returns one page;
     * iterateTraderLeaderboard walks every page. (GET /traderLeaderboard)
     */
    public TraderLeaderboardEntryConnection getTraderLeaderboard(TraderLeaderboardParams params) {
        TraderLeaderboardParams p = params == null ? new TraderLeaderboardParams() : params;
        Query q = new Query();
        if (p.getWeek() != null) q.add("week", Query.format(p.getWeek()));
        if (p.getYear() != null) q.add("year", Query.format(p.getYear()));
        if (p.getPageSize() != null) q.add("first", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        TraderLeaderboardResponse resp = send("GET", "/traderLeaderboard", q, null, TraderLeaderboardResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((TraderLeaderboardResponse) cur).getExploreTraderLeaderboard();
        return cur == null ? new TraderLeaderboardEntryConnection() : (TraderLeaderboardEntryConnection) cur;
    }

    /**
     * Every TraderLeaderboardEntry across all pages, fetched lazily as you iterate. Stop early with
     * break. params.after picks the starting point.
     */
    public Iterable<TraderLeaderboardEntry> iterateTraderLeaderboard(TraderLeaderboardParams params) {
        TraderLeaderboardParams start = params == null ? new TraderLeaderboardParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            TraderLeaderboardEntryConnection page = getTraderLeaderboard(p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /** A trend coin by its ticker. Empty if there is no such coin. (GET /trendCoin) */
    public Optional<Zora20Token> getTrendCoin(String ticker, TrendCoinParams params) {
        TrendCoinParams p = params == null ? new TrendCoinParams() : params;
        Query q = new Query();
        q.add("ticker", ticker);
        q.add("chainId", String.valueOf(p.getChainId() == null ? BASE_CHAIN_ID : p.getChainId()));
        TrendCoinResponse resp = send("GET", "/trendCoin", q, null, TrendCoinResponse.class);
        return Optional.ofNullable(resp == null ? null : resp.getTrendCoin());
    }

    /**
     * Trend coins whose name matches, best match first. Returns one page; iterateTrendsByName walks
     * every page. (GET /trendsByName)
     */
    public Zora20TokenConnection getTrendsByName(String name, TrendsByNameParams params) {
        TrendsByNameParams p = params == null ? new TrendsByNameParams() : params;
        Query q = new Query();
        q.add("name", name);
        if (p.getPageSize() != null) q.add("first", Query.format(p.getPageSize()));
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        TrendsByNameResponse resp = send("GET", "/trendsByName", q, null, TrendsByNameResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((TrendsByNameResponse) cur).getTrendsByName();
        return cur == null ? new Zora20TokenConnection() : (Zora20TokenConnection) cur;
    }

    /**
     * Every Zora20Token across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<Zora20Token> iterateTrendsByName(String name, TrendsByNameParams params) {
        TrendsByNameParams start = params == null ? new TrendsByNameParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            Zora20TokenConnection page = getTrendsByName(name, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * Trades made by a wallet or profile, newest first. Returns one page; iterateWalletTradeActivity
     * walks every page. (GET /walletTradeActivity)
     */
    public TradeActivityConnection getWalletTradeActivity(String identifier, WalletTradeActivityParams params) {
        WalletTradeActivityParams p = params == null ? new WalletTradeActivityParams() : params;
        Query q = new Query();
        q.add("identifier", identifier);
        if (p.getAfter() != null) q.add("after", Query.format(p.getAfter()));
        if (p.getPageSize() != null) q.add("first", Query.format(p.getPageSize()));
        WalletTradeActivityResponse resp = send("GET", "/walletTradeActivity", q, null, WalletTradeActivityResponse.class);
        Object cur = resp;
        cur = cur == null ? null : ((WalletTradeActivityResponse) cur).getWalletAddressTradeActivity();
        return cur == null ? new TradeActivityConnection() : (TradeActivityConnection) cur;
    }

    /**
     * Every TradeActivity across all pages, fetched lazily as you iterate. Stop early with break.
     * params.after picks the starting point.
     */
    public Iterable<TradeActivity> iterateWalletTradeActivity(String identifier, WalletTradeActivityParams params) {
        WalletTradeActivityParams start = params == null ? new WalletTradeActivityParams() : params.copy();
        return () -> new Pages<>(start, p -> {
            TradeActivityConnection page = getWalletTradeActivity(identifier, p);
            return new Pages.Page<>(page.nodes(), page.nextCursor());
        }, (p, cursor) -> p.after(cursor));
    }

    /**
     * Quote a trade. The result holds the transaction that executes it. Amounts are in the input
     * token's smallest unit (wei for ETH). Set Referrer to earn the trade referral reward. Nothing is
     * signed or sent: pass the returned call to your wallet. (POST /quote)
     */
    public QuoteResponse quote(QuoteRequest request) {
        Query q = new Query();
        QuoteResponse resp = send("POST", "/quote", q, request, QuoteResponse.class);
        return resp;
    }

    /**
     * Build the transaction that creates a content coin. The result also holds the coin's predicted
     * address. Set PlatformReferrer to earn the platform referral share of the coin's trading fees for
     * its whole life. Nothing is signed or sent. (POST /create/content)
     */
    public CreateContentCoinResponse createContentCoin(CreateContentCoinRequest request) {
        Query q = new Query();
        CreateContentCoinResponse resp = send("POST", "/create/content", q, request, CreateContentCoinResponse.class);
        return resp;
    }
}
