// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.model.*;
import java.util.List;

/** Optional parameters of ZoraCoins.getProfileCoins. Unset values use the API's defaults. */
public final class ProfileCoinsParams {
    private Integer pageSize;
    private String after;
    private List<Long> chainIds;
    private List<String> platformReferrerAddress;

    /** Page size. */
    public ProfileCoinsParams pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /** The pageSize set, or null. */
    public Integer getPageSize() {
        return pageSize;
    }

    /** Cursor to continue from: the previous page's pageInfo.endCursor. */
    public ProfileCoinsParams after(String after) {
        this.after = after;
        return this;
    }

    /** The after set, or null. */
    public String getAfter() {
        return after;
    }

    /** Only include these chains. Defaults to Base. */
    public ProfileCoinsParams chainIds(List<Long> chainIds) {
        this.chainIds = chainIds;
        return this;
    }

    /** The chainIds set, or null. */
    public List<Long> getChainIds() {
        return chainIds;
    }

    /** Only coins created through one of these platform referrer addresses. */
    public ProfileCoinsParams platformReferrerAddress(List<String> platformReferrerAddress) {
        this.platformReferrerAddress = platformReferrerAddress;
        return this;
    }

    /** The platformReferrerAddress set, or null. */
    public List<String> getPlatformReferrerAddress() {
        return platformReferrerAddress;
    }

    /** A copy, so pagination can move the cursor without touching the caller's object. */
    public ProfileCoinsParams copy() {
        ProfileCoinsParams c = new ProfileCoinsParams();
        c.pageSize = pageSize;
        c.after = after;
        c.chainIds = chainIds;
        c.platformReferrerAddress = platformReferrerAddress;
        return c;
    }
}
