// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.model.*;
import java.util.List;

/** Optional parameters of ZoraCoins.search. Unset values use the API's defaults. */
public final class SearchParams {
    private EntityType entityType;
    private Integer pageSize;
    private String after;

    /** Only return results of this kind. */
    public SearchParams entityType(EntityType entityType) {
        this.entityType = entityType;
        return this;
    }

    /** The entityType set, or null. */
    public EntityType getEntityType() {
        return entityType;
    }

    /** Page size. */
    public SearchParams pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /** The pageSize set, or null. */
    public Integer getPageSize() {
        return pageSize;
    }

    /** Cursor to continue from: the previous page's pageInfo.endCursor. */
    public SearchParams after(String after) {
        this.after = after;
        return this;
    }

    /** The after set, or null. */
    public String getAfter() {
        return after;
    }

    /** A copy, so pagination can move the cursor without touching the caller's object. */
    public SearchParams copy() {
        SearchParams c = new SearchParams();
        c.entityType = entityType;
        c.pageSize = pageSize;
        c.after = after;
        return c;
    }
}
