// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.model.*;
import java.util.List;

/** Optional parameters of ZoraCoins.getTokenInfo. Unset values use the API's defaults. */
public final class TokenInfoParams {
    private Long chainId;

    /** Chain ID. Defaults to Base (8453). */
    public TokenInfoParams chainId(Long chainId) {
        this.chainId = chainId;
        return this;
    }

    /** The chainId set, or null. */
    public Long getChainId() {
        return chainId;
    }

    /** A copy, so pagination can move the cursor without touching the caller's object. */
    public TokenInfoParams copy() {
        TokenInfoParams c = new TokenInfoParams();
        c.chainId = chainId;
        return c;
    }
}
