// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora;

import io.github.pgalyen1987.zora.model.*;
import java.util.List;

/** Optional parameters of ZoraCoins.getTraderLeaderboard. Unset values use the API's defaults. */
public final class TraderLeaderboardParams {
    private Long week;
    private Long year;
    private Integer pageSize;
    private String after;

    /** ISO week number. Defaults to the current week. */
    public TraderLeaderboardParams week(Long week) {
        this.week = week;
        return this;
    }

    /** The week set, or null. */
    public Long getWeek() {
        return week;
    }

    /** Year of the ISO week. Defaults to the current year. */
    public TraderLeaderboardParams year(Long year) {
        this.year = year;
        return this;
    }

    /** The year set, or null. */
    public Long getYear() {
        return year;
    }

    /** Page size. */
    public TraderLeaderboardParams pageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /** The pageSize set, or null. */
    public Integer getPageSize() {
        return pageSize;
    }

    /** Cursor to continue from: the previous page's pageInfo.endCursor. */
    public TraderLeaderboardParams after(String after) {
        this.after = after;
        return this;
    }

    /** The after set, or null. */
    public String getAfter() {
        return after;
    }

    /** A copy, so pagination can move the cursor without touching the caller's object. */
    public TraderLeaderboardParams copy() {
        TraderLeaderboardParams c = new TraderLeaderboardParams();
        c.week = week;
        c.year = year;
        c.pageSize = pageSize;
        c.after = after;
        return c;
    }
}
