// Generated by codegen/emit_cpp.py from Zora's OpenAPI spec. Do not edit.
#pragma once

#include <functional>
#include <set>

#include "zora/models.hpp"

namespace zora {

/// Optional parameters of Client::coin. Unset values use the API's defaults.
struct CoinParams {
    /// Chain ID. Defaults to Base (8453).
    std::optional<std::int64_t> chain_id;
};

/// Optional parameters of Client::coin_comments. Unset values use the API's defaults.
struct CoinCommentsParams {
    /// Chain ID. Defaults to Base (8453).
    std::optional<std::int64_t> chain_id;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
    /// Page size.
    std::optional<int> page_size;
};

/// Optional parameters of Client::coin_holders. Unset values use the API's defaults.
struct CoinHoldersParams {
    /// Chain ID. Defaults to Base (8453).
    std::optional<std::int64_t> chain_id;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
    /// Page size.
    std::optional<int> page_size;
};

/// Optional parameters of Client::coin_merged_comments. Unset values use the API's defaults.
struct CoinMergedCommentsParams {
    /// Chain ID. Defaults to Base (8453).
    std::optional<std::int64_t> chain_id;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
    /// Page size.
    std::optional<int> page_size;
};

/// Optional parameters of Client::coin_price_history. Unset values use the API's defaults.
struct CoinPriceHistoryParams {
    /// Chain ID. Defaults to Base (8453).
    std::optional<std::int64_t> chain_id;
};

/// Optional parameters of Client::coin_swaps. Unset values use the API's defaults.
struct CoinSwapsParams {
    /// Chain ID. Defaults to Base (8453).
    std::optional<std::int64_t> chain_id;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
    /// Page size.
    std::optional<int> page_size;
};

/// Optional parameters of Client::coins_list. Unset values use the API's defaults.
struct CoinsListParams {
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
    /// Include each coin's price in USDC. Defaults to true.
    std::optional<bool> include_usdc_price;
};

/// Optional parameters of Client::content_coin_pool_config. Unset values use the API's defaults.
struct ContentCoinPoolConfigParams {
    /// Profile handle or wallet of the creator, used to pair with their creator coin.
    std::optional<std::string> creator_identifier;
};

/// Optional parameters of Client::creator_coin_pool_config. Unset values use the API's defaults.
struct CreatorCoinPoolConfigParams {
    /// Starting market cap to size the pool for, in USD.
    std::optional<std::int64_t> target_market_cap_usd;
};

/// Optional parameters of Client::creator_livestream_comments. Unset values use the API's defaults.
struct CreatorLivestreamCommentsParams {
    /// Chain ID. Defaults to Base (8453).
    std::optional<std::int64_t> chain_id;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
    /// Page size.
    std::optional<int> page_size;
};

/// Optional parameters of Client::explore. Unset values use the API's defaults.
struct ExploreParams {
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
};

/// Optional parameters of Client::featured_creators. Unset values use the API's defaults.
struct FeaturedCreatorsParams {
    /// Year of the ISO week. Defaults to the current year.
    std::optional<std::int64_t> year;
    /// ISO week number. Defaults to the current week.
    std::optional<std::int64_t> week;
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
};

/// Optional parameters of Client::latest_live_streams. Unset values use the API's defaults.
struct LatestLiveStreamsParams {
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
};

/// Optional parameters of Client::profile_balances. Unset values use the API's defaults.
struct ProfileBalancesParams {
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
    /// How to order the balances.
    std::optional<SortOption> sort_option;
    /// Leave out coins the profile has hidden. Defaults to true.
    std::optional<bool> exclude_hidden;
    /// Only include these chains. Defaults to Base.
    std::optional<std::vector<std::int64_t>> chain_ids;
};

/// Optional parameters of Client::profile_coins. Unset values use the API's defaults.
struct ProfileCoinsParams {
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
    /// Only include these chains. Defaults to Base.
    std::optional<std::vector<std::int64_t>> chain_ids;
    /// Only coins created through one of these platform referrer addresses.
    std::optional<std::vector<std::string>> platform_referrer_address;
};

/// Optional parameters of Client::search. Unset values use the API's defaults.
struct SearchParams {
    /// Only return results of this kind.
    std::optional<EntityType> entity_type;
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
};

/// Optional parameters of Client::token_info. Unset values use the API's defaults.
struct TokenInfoParams {
    /// Chain ID. Defaults to Base (8453).
    std::optional<std::int64_t> chain_id;
};

/// Optional parameters of Client::top_live_streams. Unset values use the API's defaults.
struct TopLiveStreamsParams {
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
};

/// Optional parameters of Client::trader_leaderboard. Unset values use the API's defaults.
struct TraderLeaderboardParams {
    /// ISO week number. Defaults to the current week.
    std::optional<std::int64_t> week;
    /// Year of the ISO week. Defaults to the current year.
    std::optional<std::int64_t> year;
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
};

/// Optional parameters of Client::trend_coin. Unset values use the API's defaults.
struct TrendCoinParams {
    /// Chain ID. Defaults to Base (8453).
    std::optional<std::int64_t> chain_id;
};

/// Optional parameters of Client::trends_by_name. Unset values use the API's defaults.
struct TrendsByNameParams {
    /// Page size.
    std::optional<int> page_size;
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
};

/// Optional parameters of Client::wallet_trade_activity. Unset values use the API's defaults.
struct WalletTradeActivityParams {
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    std::optional<std::string> after;
    /// Page size.
    std::optional<int> page_size;
};

}  // namespace zora
