"""The words Zora's spec leaves out, written once and shared by every SDK and the GraphQL schema.

Zora's OpenAPI spec describes its operations as "zoraSDK_coin query" and most fields not at all.
Everything a developer reads in the Go, Rust and Python docs and in the GraphQL schema comes from
here, so the four never disagree.
"""

from __future__ import annotations

BASE_CHAIN_ID = 8453

# operationId -> the SDK method name (snake_case; each emitter converts it) and its documentation.
# `returns` says what the method hands back after unwrapping the response envelope.
METHODS: dict[str, dict] = {
    "GetApiKey": {"name": "api_key", "doc": "Look up an API key: whether it exists and is active."},
    "GetCoin": {"name": "coin", "doc": "One coin by contract address: market data, creator profile, media, pool key and creator earnings.", "not_found": True},
    "GetCoins": {"name": "coins", "doc": "Several coins in one request. Missing coins are left out of the result."},
    "GetCoinHolders": {"name": "coin_holders", "doc": "Holders of a coin and their balances, largest first."},
    "GetCoinSwaps": {"name": "coin_swaps", "doc": "Buys and sells of a coin, newest first."},
    "GetCoinComments": {"name": "coin_comments", "doc": "Comments posted on a coin, newest first."},
    "GetCoinMergedComments": {"name": "coin_merged_comments", "doc": "A coin's comment feed with replies threaded in, newest first."},
    "GetCoinPriceHistory": {"name": "coin_price_history", "doc": "A coin's price history at five resolutions: the last hour, day, week, month, and all time.", "not_found": True},
    "GetCoinsList": {"name": "coins_list", "doc": "Basic information (address, name, symbol, price) for every coin, in pages of up to 1,000."},
    "GetTokenInfo": {"name": "token_info", "doc": "Symbol, decimals and current USD price of any ERC-20 on the chain: ZORA, USDC, WETH, or a coin.", "not_found": True},
    "GetExplore": {"name": "explore", "doc": "A Zora Explore list: top gainers, 24h volume, newest, most valuable creators and more. See ListType for all 25."},
    "GetSearch": {"name": "search", "doc": "Search coins, profiles, content and trends by text."},
    "GetTrendCoin": {"name": "trend_coin", "doc": "A trend coin by its ticker.", "not_found": True},
    "GetTrendsByName": {"name": "trends_by_name", "doc": "Trend coins whose name matches, best match first."},
    "GetTraderLeaderboard": {"name": "trader_leaderboard", "doc": "The weekly trader leaderboard. Defaults to the current week."},
    "GetFeaturedCreators": {"name": "featured_creators", "doc": "Creators featured on the weekly leaderboard. Defaults to the current week."},
    "GetLatestLiveStreams": {"name": "latest_live_streams", "doc": "Live streams, most recently started first."},
    "GetTopLiveStreams": {"name": "top_live_streams", "doc": "Live streams with the most viewers right now."},
    "GetCreatorLivestreamComments": {"name": "creator_livestream_comments", "doc": "Comments on the live stream of the creator behind a coin."},
    "GetProfile": {"name": "profile", "doc": "A profile by handle or wallet address, with its linked wallets and creator coin.", "not_found": True},
    "GetProfileCoins": {"name": "profile_coins", "doc": "Coins a profile created. Filter by platform referrer to list only coins launched through a given app."},
    "GetProfileBalances": {"name": "profile_balances", "doc": "Coins a profile holds, with balances and current values."},
    "GetProfileSocial": {"name": "profile_social", "doc": "A profile's linked social accounts (X, TikTok, Instagram, Farcaster) and follower counts.", "not_found": True},
    "GetProfileBySocialHandle": {"name": "profile_by_social_handle", "doc": "Find a Zora profile from its handle on X, TikTok, Farcaster or Instagram.", "not_found": True},
    "GetWalletTradeActivity": {"name": "wallet_trade_activity", "doc": "Trades made by a wallet or profile, newest first."},
    "GetCreatorCoinPoolConfig": {"name": "creator_coin_pool_config", "doc": "The Uniswap V4 pool configuration Zora uses to launch a creator coin, optionally sized for a starting market cap in USD."},
    "GetContentCoinPoolConfig": {"name": "content_coin_pool_config", "doc": "The Uniswap V4 pool configuration Zora uses to launch a content coin paired with the given currency."},
    "PostQuote": {"name": "quote", "doc": "Quote a trade. The result holds the transaction that executes it. Amounts are in the input token's smallest unit (wei for ETH). Set Referrer to earn the trade referral reward. Nothing is signed or sent: pass the returned call to your wallet."},
    "PostCreateContent": {"name": "create_content_coin", "doc": "Build the transaction that creates a content coin. The result also holds the coin's predicted address. Set PlatformReferrer to earn the platform referral share of the coin's trading fees for its whole life. Nothing is signed or sent."},
    "SetCreateUploadJWT": {"name": "create_upload_jwt", "doc": "Create a short-lived token for uploading coin media and metadata to Zora's uploader. Requires an API key."},
}

# Query parameter documentation, by the parameter's wire name.
PARAMS: dict[str, str] = {
    "address": "Contract address (0x…).",
    "chain": "Chain ID. Defaults to Base (8453).",
    "chainId": "Chain ID. Defaults to Base (8453).",
    "chainIds": "Only include these chains. Defaults to Base.",
    "after": "Cursor to continue from: the previous page's pageInfo.endCursor.",
    "count": "Page size.",
    "first": "Page size.",
    "identifier": "Profile handle (without @) or wallet address.",
    "listType": "Which Explore list to return.",
    "sortOption": "How to order the balances.",
    "excludeHidden": "Leave out coins the profile has hidden. Defaults to true.",
    "platformReferrerAddress": "Only coins created through one of these platform referrer addresses.",
    "platform": "The social network the handle belongs to.",
    "handle": "Handle on that network, without @.",
    "text": "What to search for.",
    "entityType": "Only return results of this kind.",
    "week": "ISO week number. Defaults to the current week.",
    "year": "Year of the ISO week. Defaults to the current year.",
    "ticker": "Trend ticker, without $.",
    "name": "Trend name to match.",
    "includeUSDCPrice": "Include each coin's price in USDC. Defaults to true.",
    "targetMarketCapUsd": "Starting market cap to size the pool for, in USD.",
    "creatorIdentifier": "Profile handle or wallet of the creator, used to pair with their creator coin.",
    "currencyType": "The currency the new coin trades against.",
    "apiKey": "The API key to look up.",
    "coins": "The coins to fetch.",
}

# What the core types are. Connections and edges are documented automatically.
TYPES: dict[str, str] = {
    "Zora20Token": "A Zora coin: an ERC-20 with a Uniswap V4 market, created by a creator or for a piece of content or a trend. Endpoints return different selections of its fields; anything not selected is empty.",
    "CoinBasicInfo": "The compact form of a coin returned by the coins list.",
    "Profile": "A Zora profile: handle, avatar, linked wallets, creator coin, and (depending on the call) the coins it created or holds.",
    "CreatorProfile": "The profile of the creator behind a coin.",
    "TokenBalance": "One holder of a coin and how much they hold.",
    "CoinBalance": "One coin a profile holds, with the balance and the coin itself.",
    "SwapActivity": "One buy or sell of a coin.",
    "TradeActivity": "One trade made by a wallet.",
    "ZoraComment": "A comment posted on a coin.",
    "Comment": "A comment in a coin's merged feed or on a live stream.",
    "PricePoint": "The price of a coin at a moment in time.",
    "PageInfo": "Where a page sits in a paginated list. Pass EndCursor as After to get the next page while HasNextPage is true.",
    "MediaContent": "The image, video or other media attached to a coin.",
    "PoolCurrencyToken": "The currency a coin's pool trades against (ZORA, ETH, USDC or a creator coin).",
    "TokenPrice": "A coin's current price, in the pool's currency and in USD.",
    "UniswapV4PoolKey": "The Uniswap V4 pool key of a coin's market.",
    "CreatorEarning": "What a coin's creator has earned from trading fees, in one currency.",
    "SearchResult": "One search hit: a profile, a coin, a piece of content or a trend.",
    "TraderLeaderboardEntry": "One trader's position on the weekly leaderboard.",
    "FeaturedCreator": "A creator featured on the weekly leaderboard.",
    "LiveStream": "A creator's live stream.",
    "Erc20Token": "ERC-20 metadata and price for any token.",
    "PoolConfig": "The pool configuration Zora uses to launch a coin: encoded config plus the currency it pairs with.",
    "QuoteResponse": "A trade quote and the transaction that executes it.",
    "Quote": "What a trade is expected to return.",
    "Call": "A transaction to send from the user's wallet: target (to), calldata and ETH value.",
    "CreateContentCoinResponse": "The calls that create a content coin, and the address it will have.",
    "ApiKey": "Whether an API key exists and is active.",
    "TokenSpec": "A token in a trade quote: native ETH or an ERC-20 address.",
    "TokenSpecInput": "A token to trade: native ETH (type \"eth\") or an ERC-20 (type \"erc20\" plus address). Build one with ETH() or ERC20(address).",
    "CoinRefInput": "A coin to fetch with Coins: its chain and contract address.",
    "QuoteRequest": "A trade to quote. TokenIn, TokenOut, AmountIn and Sender are required; Recipient defaults to Sender and Slippage to 0.05.",
    "CreateContentCoinRequest": "A content coin to create. Metadata must point at EIP-7572 JSON (ipfs:// or https://).",
    "CreateUploadJwtRequest": "Who the upload token is for.",
}

# Request fields the API needs even though the spec doesn't mark them required.
REQUIRED_INPUT: dict[str, set[str]] = {
    "QuoteRequest": {"tokenIn", "tokenOut", "amountIn", "sender"},
    "CreateUploadJwtRequest": {"creatorAddress"},
}

# Enum value documentation, where the name alone isn't enough.
ENUM_DOCS: dict[str, str] = {
    "ListType": "Which Zora Explore list to fetch.",
    "SortOption": "How to order a profile's balances.",
    "Platform": "A social network Zora profiles link to.",
    "EntityType": "What kind of thing a search result is.",
    "CoinType": "What a coin represents: a creator, a piece of content, or a trend.",
    "CurrencyType": "What a new coin's pool trades against.",
    "ContentCoinCurrency": "What a new content coin trades against.",
    "SwapType": "Whether a trade was a buy or a sell.",
    "TokenType": "Native ETH or an ERC-20.",
    "StartingMarketCap": "The starting market cap tier for a new coin.",
    "WalletType": "How a wallet linked to a profile is held.",
    "EventType": "Whether a social account was linked or unlinked.",
    "MetadataType": "How coin metadata is supplied. Only RAW_URI is supported.",
}


def connection_doc(name: str) -> str | None:
    if name.endswith("Connection"):
        node = name[: -len("Connection")]
        return f"One page of {node} results. Nodes() lists them; PageInfo says how to get the next page."
    if name.endswith("Edge"):
        node = name[: -len("Edge")]
        return f"Wraps one {node} in a page of results."
    return None


# Field documentation, checked against real responses (fixtures/). "Type.field" wins over "field".
# Units matter most: the API mixes USD decimals, whole-token decimals and raw 18-decimal integers,
# all as strings, and says nothing about which is which.
FIELDS: dict[str, str] = {
    "address": "Contract address (lowercase 0x hex).",
    "chainId": "Chain ID (8453 = Base).",
    "name": "Display name.",
    "symbol": "Ticker symbol.",
    "handle": "Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6).",
    "createdAt": "When it was created (ISO 8601, UTC).",
    "blockTimestamp": "Time of the block it happened in (ISO 8601, UTC).",
    "transactionHash": "Hash of the transaction it happened in.",
    "platformBlocked": "True if Zora hides this from its own app.",
    "Zora20Token.totalSupply": "Total supply in whole tokens, as a decimal string (\"1000000000\" = one billion).",
    "Zora20Token.totalVolume": "All-time trading volume in USD, as a decimal string.",
    "Zora20Token.volume24h": "Trading volume over the last 24 hours in USD, as a decimal string.",
    "Zora20Token.marketCap": "Market cap in USD, as a decimal string.",
    "Zora20Token.marketCapDelta24h": "Change in market cap over the last 24 hours in USD (negative when it fell), as a decimal string.",
    "Zora20Token.creatorAddress": "Wallet that created the coin.",
    "Zora20Token.payoutRecipientAddress": "Wallet that receives the creator's share of trading fees.",
    "Zora20Token.platformReferrerAddress": "The app that launched the coin; it earns the platform referral share of every trade, for good.",
    "Zora20Token.uniqueHolders": "Number of distinct wallets holding the coin.",
    "Zora20Token.tokenUri": "Metadata URI (EIP-7572 JSON, usually ipfs://).",
    "Zora20Token.coinType": "Whether this is a creator coin, a content coin or a trend.",
    "Zora20Token.uniswapV3PoolAddress": "Pool of a legacy V3 coin. Empty for V4 coins, which use uniswapV4PoolKey.",
    "Zora20Token.uniswapV4PoolKey": "Pool key of a V4 coin's market.",
    "Zora20Token.poolCurrencyToken": "What the coin's pool trades against.",
    "Zora20Token.creatorEarnings": "What the creator has earned from trading fees, per currency.",
    "Zora20Token.zoraComments": "Comments (only filled by the coin-comments endpoint).",
    "Zora20Token.tokenBalances": "Holders (only filled by the coin-holders endpoint).",
    "Zora20Token.swapActivities": "Buys and sells (only filled by the coin-swaps endpoint).",
    "Zora20Token.oneHour": "Prices over the last hour (only filled by the price-history endpoint).",
    "Zora20Token.oneDay": "Prices over the last day.",
    "Zora20Token.oneWeek": "Prices over the last week.",
    "Zora20Token.oneMonth": "Prices over the last month.",
    "Zora20Token.all": "Prices over the coin's whole life.",
    "TokenPrice.priceInUsdc": "Price of one whole coin in USDC (≈ USD), as a decimal string.",
    "TokenPrice.priceInPoolToken": "Price of one whole coin in the pool's currency, as a decimal string.",
    "TokenPrice.currencyAddress": "The coin the price is for.",
    "PricePoint.closePrice": "Price at the end of the interval, in USD.",
    "PricePoint.timestamp": "Start of the interval (ISO 8601, UTC).",
    "TokenBalance.balance": "Amount held, in the coin's smallest unit (18 decimals) — divide by 1e18 for whole coins.",
    "TokenBalance.ownerAddress": "Wallet holding the coin.",
    "CoinBalance.balance": "Amount held, in the coin's smallest unit (18 decimals).",
    "CoinBalance.walletBalance": "Amount held in the profile's own wallets, in the smallest unit (18 decimals).",
    "SwapActivity.activityType": "BUY or SELL.",
    "SwapActivity.coinAmount": "Coins bought or sold, in the smallest unit (18 decimals).",
    "SwapActivity.senderAddress": "Wallet that sent the swap.",
    "SwapActivity.recipientAddress": "Wallet that received the output.",
    "CurrencyAmountWithPrice.priceUsdc": "USD price of one unit of the currency at the time of the swap.",
    "CurrencyAmount.amountDecimal": "Amount in whole units of the currency.",
    "Amount.amountRaw": "Amount in the currency's smallest unit, as an integer string.",
    "Amount.amountDecimal": "Amount in whole units of the currency.",
    "Amount.currencyAddress": "The currency (WETH, ZORA, USDC or a creator coin).",
    "Currency.priceUsd": "Current USD price of one whole token, as a decimal string.",
    "Currency.decimals": "Token decimals (18 for most, 6 for USDC).",
    "Call.target": "Contract to send the transaction to.",
    "Call.to": "Same as target.",
    "Call.data": "Calldata (0x hex).",
    "Call.value": "ETH to send with the transaction, in wei, as an integer string.",
    "Quote.amountOut": "Expected output, in the output token's smallest unit.",
    "Quote.slippage": "Slippage tolerance the quote was built with (0.05 = 5%).",
    "QuoteRequest.amountIn": "Amount to sell, in the input token's smallest unit (wei for ETH).",
    "QuoteRequest.slippage": "Maximum slippage (0.05 = 5%). Defaults to 5% with QuoteTrade.",
    "QuoteRequest.sender": "Wallet that will send the transaction.",
    "QuoteRequest.recipient": "Wallet that receives the output. Defaults to the sender with QuoteTrade.",
    "QuoteRequest.referrer": "Address that earns the trade referral reward for routing this trade.",
    "QuoteRequest.tokenIn": "What to sell. Use ETH() or ERC20(address).",
    "QuoteRequest.tokenOut": "What to buy. Use ETH() or ERC20(address).",
    "QuoteRequest.signatures": "Permit2 signatures, when selling an ERC-20 without a prior approval.",
    "CreateContentCoinRequest.creator": "Wallet creating the coin.",
    "CreateContentCoinRequest.platformReferrer": "Your app's address: it earns the platform referral share of this coin's trading fees for good.",
    "CreateContentCoinRequest.payoutRecipientOverride": "Wallet to receive the creator's fee share instead of the creator.",
    "CreateContentCoinRequest.additionalOwners": "More wallets allowed to manage the coin.",
    "CreateContentCoinRequest.startingMarketCap": "Starting market cap tier.",
    "CreateContentCoinRequest.metadata": "Where the coin's EIP-7572 metadata lives.",
    "PageInfo.endCursor": "Cursor to pass as After for the next page.",
    "PageInfo.hasNextPage": "Whether another page follows.",
    "PageInfo.startCursor": "Cursor of the first item on this page.",
    "MediaContent.mimeType": "MIME type of the original media.",
    "MediaContent.originalUri": "The original media file (often ipfs://).",
    "MediaContent.previewImage": "Resized previews served over https.",
}

FIELDS.update({
    # relay plumbing and envelopes
    "edges": "The items on this page, each wrapped in an edge.",
    "node": "The item.",
    "pageInfo": "How to fetch the next page.",
    "count": "Total number of items, where the API reports it.",
    "cursor": "Cursor pointing at this item.",
    # people and profiles
    "avatar": "Profile picture.",
    "Avatar.small": "Small avatar image URL.",
    "Avatar.medium": "Medium avatar image URL.",
    "Avatar.blurhash": "BlurHash placeholder to show while the image loads.",
    "PreviewImage.small": "Small preview image URL.",
    "PreviewImage.medium": "Medium preview image URL.",
    "PreviewImage.blurhash": "BlurHash placeholder to show while the image loads.",
    "previewImage": "Resized preview of the image.",
    "profile": "The profile.",
    "userProfile": "Profile of the user who posted it.",
    "senderProfile": "Profile of the wallet that sent the trade.",
    "ownerProfile": "Profile of the holder (a wallet profile if the holder has no Zora account).",
    "traderProfile": "Profile of the trader.",
    "makerProfile": "Profile of the wallet that made the trade.",
    "creatorProfile": "Profile of the creator.",
    "displayName": "Display name on that network.",
    "username": "Username on that network.",
    "followerCount": "Followers on that network.",
    "socialAccounts": "Linked social accounts: X, TikTok, Instagram, Farcaster.",
    "SocialAccounts.twitter": "Linked X (Twitter) account.",
    "SocialAccounts.tiktok": "Linked TikTok account.",
    "SocialAccounts.instagram": "Linked Instagram account.",
    "SocialAccounts.farcaster": "Linked Farcaster account.",
    "website": "Website on the profile.",
    "bio": "Profile bio.",
    "publicWallet": "The profile's primary public wallet.",
    "linkedWallets": "Wallets linked to the profile.",
    "externalWallet": "An external wallet linked to the profile.",
    "walletAddress": "Wallet address.",
    "walletType": "How the wallet is held (Privy, external, smart wallet).",
    "ensName": "ENS name of the wallet, if it has one.",
    "followers": "Who follows this profile.",
    "following": "Who this profile follows.",
    "usernameChangesCount": "How many times the handle has been changed.",
    "coinBalances": "Coins the profile holds (only filled by the profile-balances endpoint).",
    "createdCoins": "Coins the profile created (only filled by the profile-coins endpoint).",
    "creatorCoin": "The creator's own creator coin.",
    "socialAccountLinkedEvents": "History of social accounts being linked and unlinked.",
    "platform": "The social network.",
    "socialAccountUsername": "Username on the social network.",
    "eventType": "Whether the account was linked or unlinked.",
    # comments
    "comment": "The comment text.",
    "text": "The comment text.",
    "commentId": "ID of the comment.",
    "userAddress": "Wallet of the user who posted it.",
    "txHash": "Hash of the transaction that posted it onchain, if it was posted onchain.",
    "timestamp": "When it happened (Unix seconds).",
    "nonce": "Nonce the comment was signed or posted with.",
    "replies": "Replies to this comment.",
    "contractAddress": "Contract of the coin the comment is on.",
    "replyToOnChainId": "Onchain ID of the comment this replies to, if any.",
    "replyToOffChainId": "Offchain ID of the comment this replies to, if any.",
    "sparkCount": "Sparks (Zora's likes) the comment received.",
    # money
    "coin": "The coin.",
    "amount": "The amount.",
    "amountUsd": "The amount in USD.",
    "currency": "The currency.",
    "currencyAmount": "Amount paid or received, in the pool's currency.",
    "currencyAmountWithPrice": "Amount in the pool's currency, with the currency's USD price at the time.",
    "priceDelta24h": "Change in the currency's price over the last 24 hours.",
    "priceUsdc": "Price in USDC (≈ USD), as a decimal string.",
    "icon": "Token icon URL.",
    "decimals": "Token decimals (18 for most, 6 for USDC).",
    "valuation": "What the holding is worth.",
    "Valuation.marketValueUsd": "What the holding would fetch at the current price, in USD.",
    "Valuation.faceValueUsd": "Balance × price, in USD, ignoring slippage.",
    "Valuation.blockNumber": "Block the valuation was computed at.",
    "Valuation.maxSwappable": "The most of the holding that can be sold into the pool right now.",
    "Erc20Token.currency": "The token's symbol, decimals and USD price.",
    # coin basics and misc coin fields
    "entityName": "Name of the coin.",
    "coinAddress": "Contract address of the coin.",
    "coinType": "Creator, content or trend coin.",
    "uri": "Metadata URI.",
    "createdUserAddress": "Wallet that created the coin.",
    "collectionAddress": "Contract address of the coin.",
    "creatorAddress": "The creator's wallet.",
    "liveStream": "The creator's live stream, if any.",
    "trend": "The trend coin, for trend search results.",
    "entityType": "What kind of thing this result is.",
    # live streams and media
    "isOnline": "Whether the stream is live right now.",
    "concurrentViewers": "People watching right now.",
    "staticThumbnailUrl": "Still thumbnail image URL.",
    "animatedThumbnailUrl": "Animated thumbnail URL.",
    "comments": "Comments.",
    "videoPreviewUrl": "Short video preview URL.",
    "videoHlsUrl": "HLS stream URL of the video.",
    # pools (Uniswap V4 + Doppler)
    "encodedConfig": "The pool configuration, ABI-encoded as the coin factory expects it.",
    "lowerTicks": "Lower tick of each liquidity position the pool starts with.",
    "upperTicks": "Upper tick of each liquidity position the pool starts with.",
    "numDiscoveryPositions": "Number of price-discovery liquidity positions per range.",
    "maxDiscoverySupplyShares": "Share of supply placed in each discovery range, in 18-decimal fixed point.",
    "UniswapV4PoolKey.token0Address": "currency0 of the Uniswap V4 pool key.",
    "UniswapV4PoolKey.token1Address": "currency1 of the Uniswap V4 pool key.",
    "UniswapV4PoolKey.fee": "Pool fee, in hundredths of a basis point.",
    "UniswapV4PoolKey.tickSpacing": "Tick spacing of the pool.",
    "UniswapV4PoolKey.hookAddress": "The pool's hook contract (Zora's coin hook).",
    # trading
    "tokenIn": "The token being sold.",
    "tokenOut": "The token being bought.",
    "type": "eth for native ETH, erc20 for a token (which then needs an address).",
    "permitActiveSeconds": "How long a Permit2 signature stays valid, in seconds.",
    "signature": "The signature.",
    "permit": "The Permit2 permit.",
    "details": "What the permit allows: token, amount, expiry, nonce.",
    "spender": "Contract allowed to spend the tokens.",
    "sigDeadline": "When the signature stops being valid (Unix seconds).",
    "token": "Token address.",
    "expiration": "When the allowance expires (Unix seconds).",
    "Trade.commands": "Universal Router commands the trade executes (hex).",
    "Trade.inputs": "ABI-encoded input for each command.",
    "Trade.value": "ETH to send, in wei.",
    "transactionLogIndex": "Index of the swap's log within its transaction.",
    "swapActivityType": "BUY or SELL.",
    "orderId": "Zora's ID for the trade.",
    "initialBuyAmount": "For a coin launch, how much the creator bought at creation.",
    "initialBuyAmountUsd": "That initial buy in USD.",
    "multiplier": "How many times its value the trade has returned, where Zora computes it.",
    # leaderboard
    "score": "Leaderboard score.",
    "weekVolumeUsd": "Trading volume this week in USD.",
    "weekTradesCount": "Trades made this week.",
    "weekGrossVolumeZora": "Gross trading volume this week, in ZORA.",
    # api keys
    "apiKey": "The API key.",
    "isActive": "Whether the key is active.",
    "creatorAddress": "Wallet the upload token is for.",
})


FIELDS.update({
    "QuoteResponse.success": "Whether a route was found. Sent by the API as a string; the SDKs read it as a boolean.",
    "QuoteResponse.call": "The transaction to send from the sender's wallet.",
    "QuoteResponse.trade": "The Universal Router trade encoded in the call.",
    "QuoteResponse.quote": "What the trade is expected to return.",
    "QuoteResponse.permits": "Permit2 permits the sender must sign first, when selling an ERC-20.",
    "CreateContentCoinResponse.calls": "Transactions to send from the creator's wallet, in order.",
    "CreateContentCoinResponse.predictedCoinAddress": "The address the coin will have once created.",
    "id": "Globally unique ID.",
    "TradeActivity.coinAmount": "Coins traded, in the smallest unit (18 decimals).",
    "Valuation.error": "Why the valuation couldn't be computed, when it couldn't.",
    "Zora20Token.description": "Description from the coin's metadata.",
    "Zora20Token.tokenPrice": "Current price.",
    "Zora20Token.mediaContent": "The image or video attached to the coin.",
    "Zora20Token.multichainAddress": "The coin's address on other chains, where Zora reports one.",
    "Zora20Token.uniswapPoolAddress": "The coin's Uniswap pool address, where the API reports one.",
})


def field_doc(type_name: str, json_name: str) -> str | None:
    d = FIELDS.get(f"{type_name}.{json_name}") or FIELDS.get(json_name)
    if not d and type_name.endswith("Response"):
        return "The result. Client methods return this field directly."
    return d
