"""Emit the C# SDK's generated files from the IR: models, extensible enums, and client methods."""

from __future__ import annotations

import html
import textwrap
from pathlib import Path

import docs
import ir as irmod
from emit_go import Go, words

OUT = Path(__file__).resolve().parent.parent / "dotnet" / "src" / "Zora.Coins"
HEADER = "// <auto-generated>\n// Generated by codegen/emit_csharp.py from Zora's OpenAPI spec. Do not edit.\n// </auto-generated>\n#nullable enable\n\n"
VERB_FIRST = {"explore", "search", "quote", "create"}
_INIT = {"id": "Id", "url": "Url", "uri": "Uri", "usd": "Usd", "usdc": "Usdc", "jwt": "Jwt", "eth": "Eth"}


def pascal(s: str) -> str:
    if s == "__typename":
        return "Typename"
    return "".join(_INIT.get(w.lower(), w[:1].upper() + (w[1:].lower() if w.isupper() and len(w) > 1 else w[1:])) for w in words(s))


def xml(text: str | None, indent: str = "    ") -> str:
    if not text:
        return ""
    lines = textwrap.wrap(html.escape(text, quote=False), 100 - len(indent))
    return f"{indent}/// <summary>\n" + "".join(f"{indent}/// {l}\n" for l in lines) + f"{indent}/// </summary>\n"


def cs_type(t: irmod.TypeRef) -> str:
    if t.kind == "list" and t.of:
        return f"IReadOnlyList<{cs_type(t.of)}>"
    if t.kind == "scalar":
        return {"string": "string", "int": "long", "float": "double", "bool": "bool"}[t.name]
    if t.kind == "json":
        return "System.Text.Json.JsonElement"
    return t.name


def method_name(snake: str, *, enumerate_: bool = False) -> str:
    stem = "".join(p[:1].upper() + p[1:] for p in snake.split("_"))
    stem = stem.replace("Jwt", "Jwt")
    if enumerate_:
        return f"Enumerate{stem}Async"
    return f"{stem}Async" if snake.split("_")[0] in VERB_FIRST else f"Get{stem}Async"


class CSharp:
    def __init__(self, model: irmod.IR) -> None:
        self.ir = model
        self.go = Go(model)

    def models(self) -> str:
        out = [HEADER, "using System;\nusing System.Collections.Generic;\nusing System.Text.Json;\nusing System.Text.Json.Serialization;\n\nnamespace Zora.Coins;\n\n"]
        for e in self.ir.enums.values():
            d = docs.ENUM_DOCS.get(e.name) or f"{e.name} values."
            out.append(xml(d + " An extensible enum: any string the API sends is kept, so values Zora adds later still work.", ""))
            out.append(f"[JsonConverter(typeof(ExtensibleEnumConverter<{e.name}>))]\n")
            out.append(f"public readonly struct {e.name} : IEquatable<{e.name}>, IExtensibleEnum\n{{\n")
            out.append(f"    /// <summary>The value as the API spells it.</summary>\n    public string Value {{ get; }}\n\n")
            out.append(f"    /// <summary>Wraps any value, including ones this SDK doesn't know.</summary>\n    public {e.name}(string value) => Value = value ?? throw new ArgumentNullException(nameof(value));\n\n")
            for v in e.values:
                out.append(f'    /// <summary><c>{v}</c></summary>\n    public static {e.name} {pascal(v.lower() if not v.islower() else v)} {{ get; }} = new("{v}");\n')
            out.append(f"\n    /// <summary>Every value this SDK knows.</summary>\n    public static IReadOnlyList<{e.name}> All {{ get; }} = new[] {{ " +
                       ", ".join(pascal(v.lower() if not v.islower() else v) for v in e.values) + " };\n\n")
            out.append(f"    /// <inheritdoc/>\n    public bool Equals({e.name} other) => string.Equals(Value, other.Value, StringComparison.Ordinal);\n")
            out.append(f"    /// <inheritdoc/>\n    public override bool Equals(object? obj) => obj is {e.name} other && Equals(other);\n")
            out.append(f"    /// <inheritdoc/>\n    public override int GetHashCode() => Value?.GetHashCode() ?? 0;\n")
            out.append(f"    /// <inheritdoc/>\n    public override string ToString() => Value;\n")
            out.append(f"    /// <summary>Compares values.</summary>\n    public static bool operator ==({e.name} a, {e.name} b) => a.Equals(b);\n")
            out.append(f"    /// <summary>Compares values.</summary>\n    public static bool operator !=({e.name} a, {e.name} b) => !a.Equals(b);\n")
            out.append(f"    /// <summary>Wraps a string.</summary>\n    public static implicit operator {e.name}(string value) => new(value);\n}}\n\n")
        for o in self.ir.objects.values():
            d = docs.TYPES.get(o.name) or docs.connection_doc(o.name)
            if d:
                d = d.replace("Nodes() lists them", "Nodes() lists them")
            if not d and o.name.endswith("Response"):
                d = "The raw response envelope. Client methods unwrap it."
            out.append(xml(d or "A Zora API object.", ""))
            out.append(f"public sealed class {o.name}\n{{\n")
            for f in o.fields:
                fd = docs.field_doc(o.name, f.json) or f.description or (docs.PARAMS.get(f.json) if o.input else None)
                name = pascal(f.json)
                if name == o.name:
                    name += "Value"
                t = cs_type(f.type)
                lenient = f.type.kind == "scalar" and f.type.format == "lenient"
                required = o.input and f.required
                out.append(xml((fd + " Required.") if required and fd else ("Required." if required else fd)))
                out.append(f'    [JsonPropertyName("{f.json}")]\n')
                if lenient:
                    out.append("    [JsonConverter(typeof(FlexBoolConverter))]\n")
                if not required:
                    out.append("    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n")
                if required and (f.type.kind == "object" or t == "string"):
                    out.append(f"    public {t} {name} {{ get; set; }} = default!;\n\n")
                elif required:
                    out.append(f"    public {t} {name} {{ get; set; }}\n\n")
                else:
                    out.append(f"    public {t}? {name} {{ get; set; }}\n\n")
            if o.name.endswith("Connection") and any(f.json == "edges" for f in o.fields):
                edges = next(f for f in o.fields if f.json == "edges")
                edge = self.ir.objects[edges.type.of.name]
                node = next((f for f in edge.fields if f.json == "node"), None)
                if node and node.type.kind == "object":
                    out.append(f"    /// <summary>The {node.type.name} values on this page, skipping empty edges.</summary>\n")
                    out.append(f"    public IReadOnlyList<{node.type.name}> Nodes()\n    {{\n        var list = new List<{node.type.name}>();\n"
                               "        if (Edges != null) foreach (var e in Edges) if (e?.Node != null) list.Add(e.Node);\n        return list;\n    }\n\n")
                    out.append("    /// <summary>The cursor for the next page, or null on the last page.</summary>\n"
                               "    public string? NextCursor() => PageInfo?.HasNextPage == true ? PageInfo.EndCursor : null;\n")
            out.append("}\n\n")
        return "".join(out)

    def _param_field(self, op: irmod.Operation, p: irmod.Param) -> tuple[str, str]:
        if p.name in ("chain", "chainId"):
            return "ChainId", "long?"
        if op.page_size_param == p.name:
            return "PageSize", "int?"
        t = p.type
        if t.kind == "list" and t.of:
            return pascal(p.name), f"IReadOnlyList<{cs_type(t.of)}>?"
        ct = cs_type(t)
        return pascal(p.name), (ct + "?")

    def client(self) -> str:
        out = [HEADER, "using System;\nusing System.Collections.Generic;\nusing System.Globalization;\nusing System.Runtime.CompilerServices;\n"
               "using System.Text.Json;\nusing System.Threading;\nusing System.Threading.Tasks;\n\nnamespace Zora.Coins;\n\n"]
        methods = []
        for op in self.ir.operations:
            meta = docs.METHODS[op.id]
            m = method_name(meta["name"])
            ptype = "".join(x[:1].upper() + x[1:] for x in meta["name"].split("_")) + "Params"
            positional = [p for p in op.params if p.required and p.name not in ("chain", "chainId")]
            optional = [p for p in op.params if p not in positional]
            if optional:
                out.append(xml(f"Optional parameters of <see cref=\"ZoraCoinsClient.{m}\"/>. Leave a property null for the API's default.".replace("&lt;", "<").replace("&gt;", ">").replace("&quot;", '"'), ""))
                out.append(f"public sealed class {ptype}\n{{\n")
                for p in optional:
                    fname, ft = self._param_field(op, p)
                    out.append(xml(docs.PARAMS.get(p.name) or p.description))
                    out.append(f"    public {ft} {fname} {{ get; set; }}\n\n")
                out.append(f"    internal {ptype} Copy() => ({ptype})MemberwiseClone();\n}}\n\n")
            args = []
            for p in positional:
                t = cs_type(p.type)
                args.append(f"{'IEnumerable<' + p.type.of.name + '>' if p.json_items else t} {(pascal(p.name)[:1].lower() + pascal(p.name)[1:])}")
            if optional:
                args.append(f"{ptype}? parameters = null")
            if op.body:
                args.insert(0, f"{op.body} request")
            args.append("CancellationToken cancellationToken = default")
            if op.connection:
                ret = self.go._conn_type(op)
                chain = "resp" + "".join(f"?.{pascal(k)}" for k in op.connection)
                ret_t, ret_expr = ret, f"{chain} ?? new {ret}()"
            elif op.unwrap:
                uf = next(f for f in self.ir.objects[op.response].fields if f.json == op.unwrap)
                if uf.type.kind == "list":
                    ret_t, ret_expr = cs_type(uf.type), f"resp?.{pascal(op.unwrap)} ?? Array.Empty<{cs_type(uf.type.of)}>()"
                else:
                    ret_t, ret_expr = cs_type(uf.type) + "?", f"resp?.{pascal(op.unwrap)}"
            else:
                ret_t, ret_expr = op.response, "resp!"
            d = meta["doc"]
            if op.connection:
                d += f" Returns one page; {method_name(meta['name'], enumerate_=True)} walks every page."
            if meta.get("not_found"):
                d += " Returns null if there is no such " + ("coin" if "coin" in m.lower() or "token" in m.lower() else "profile" if "profile" in m.lower() else "record") + "."
            methods.append(xml(d + f" ({op.method} {op.path})"))
            methods.append(f"    public async Task<{ret_t}> {m}({', '.join(args)})\n    {{\n")
            if optional:
                methods.append("        parameters ??= new();\n")
            methods.append("        var q = new List<KeyValuePair<string, string>>();\n")
            for p in op.params:
                if p in positional:
                    a = pascal(p.name)[:1].lower() + pascal(p.name)[1:]
                    if p.json_items:
                        methods.append(f'        foreach (var item in {a}) q.Add(new("{p.name}", JsonSerializer.Serialize(item, Json.Options)));\n')
                    elif p.type.kind == "enum":
                        methods.append(f'        q.Add(new("{p.name}", {a}.Value));\n')
                    else:
                        methods.append(f'        q.Add(new("{p.name}", {a}));\n')
                else:
                    fname, ft = self._param_field(op, p)
                    if fname == "ChainId":
                        methods.append(f'        q.Add(new("{p.name}", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));\n')
                    elif ft.startswith("IReadOnlyList"):
                        methods.append(f'        if (parameters.{fname} != null) foreach (var v in parameters.{fname}) q.Add(new("{p.name}", Format(v)));\n')
                    else:
                        methods.append(f'        if (parameters.{fname} != null) q.Add(new("{p.name}", Format(parameters.{fname})));\n')
            body = "request" if op.body else "null"
            methods.append(f'        var resp = await SendAsync<{op.response}>("{op.method}", "{op.path}", q, {body}, cancellationToken).ConfigureAwait(false);\n')
            methods.append(f"        return {ret_expr};\n    }}\n\n")
            if op.connection:
                node = op.node_type
                em = method_name(meta["name"], enumerate_=True)
                call_args = [pascal(p.name)[:1].lower() + pascal(p.name)[1:] for p in positional]
                methods.append(xml(f"Every {node} across all pages, fetched as the loop reaches them. Stop early with break. parameters.After picks the starting point."))
                eargs = [a for a in args if not a.startswith("CancellationToken")] + ["[EnumeratorCancellation] CancellationToken cancellationToken = default"]
                methods.append(f"    public async IAsyncEnumerable<{node}> {em}({', '.join(eargs)})\n    {{\n")
                methods.append(f"        var p = parameters?.Copy() ?? new {ptype}();\n        var seen = new HashSet<string>();\n        while (true)\n        {{\n")
                methods.append(f"            var page = await {m}({', '.join(call_args + ['p', 'cancellationToken'])}).ConfigureAwait(false);\n")
                methods.append("            foreach (var n in page.Nodes()) yield return n;\n")
                methods.append("            var next = page.NextCursor();\n            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;\n")
                methods.append(f"            p.After = next;\n        }}\n    }}\n\n")
        out.append("public sealed partial class ZoraCoinsClient\n{\n" + "".join(methods).rstrip() + "\n}\n")
        return "".join(out)


def main() -> None:
    model = irmod.build()
    c = CSharp(model)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "Models.g.cs").write_text(c.models())
    (OUT / "Client.g.cs").write_text(c.client())
    print(f"wrote dotnet/src/Zora.Coins/Models.g.cs and Client.g.cs: {len(model.objects)} types, {len(model.enums)} enums, {len(model.operations)} endpoints")


if __name__ == "__main__":
    main()
