"""Emit the Rust SDK's generated modules from the IR: serde models and async endpoint methods."""

from __future__ import annotations

import re
import subprocess
import textwrap
from pathlib import Path

import docs
import ir as irmod
from emit_go import Go, words

OUT = Path(__file__).resolve().parent.parent / "rust" / "src"
HEADER = "// Code generated by codegen/emit_rust.py from Zora's OpenAPI spec. DO NOT EDIT.\n\n"
KEYWORDS = {"type", "match", "ref", "self", "super", "crate", "mod", "move", "fn", "impl", "trait", "use", "where", "async", "await", "dyn", "loop", "static", "const", "enum", "struct"}


def snake(s: str) -> str:
    if s == "__typename":
        return "typename"
    w = words(s)
    out = "_".join(x.lower() for x in w)
    return out


def field_ident(s: str) -> str:
    n = snake(s)
    return f"r#{n}" if n in KEYWORDS else n


def variant(v: str) -> str:
    w = words(v.lower() if not v.islower() else v)
    return "".join(x[:1].upper() + x[1:].lower() for x in w) or "Empty"


def rust_type_name(name: str) -> str:
    return name  # IR names are already PascalCase; Rust keeps acronyms as words (Erc20Token, ApiKey)


def doc(text: str | None, indent: str = "") -> str:
    if not text:
        return ""
    return "".join(f"{indent}/// {l}\n" for l in textwrap.wrap(text.replace("`", "`"), 96 - len(indent)))


class Rust:
    def __init__(self, model: irmod.IR) -> None:
        self.ir = model
        self.go = Go(model)
        self.boxed = self._find_cycles()

    def _find_cycles(self) -> set[tuple[str, str]]:
        """(type, field) pairs that must be boxed: fields pointing back up a chain of by-value types."""
        boxed: set[tuple[str, str]] = set()

        def visit(name: str, stack: list[str]) -> None:
            o = self.ir.objects.get(name)
            if not o:
                return
            for f in o.fields:
                if f.type.kind == "object":  # lists are already heap-allocated
                    if f.type.name in stack or f.type.name == name:
                        boxed.add((name, f.json))
                    elif len(stack) < 40:
                        visit(f.type.name, stack + [name])

        for n in self.ir.objects:
            visit(n, [])
        return boxed

    def rtype(self, t: irmod.TypeRef, owner: str = "", field: str = "") -> str:
        if t.kind == "list" and t.of:
            return f"Vec<{self.rtype(t.of)}>"
        if t.kind == "scalar":
            return {"string": "String", "int": "i64", "float": "f64", "bool": "bool"}[t.name]
        if t.kind == "json":
            return "serde_json::Value"
        n = rust_type_name(t.name)
        return f"Box<{n}>" if (owner, field) in self.boxed else n

    def models(self) -> str:
        out = [HEADER, "//! Every type the Zora Coins API returns or accepts.\n\n"
               "#![allow(clippy::large_enum_variant, clippy::doc_lazy_continuation)]\n\n"
               "use serde::{Deserialize, Serialize};\n\n"]
        for e in self.ir.enums.values():
            out.append(doc(docs.ENUM_DOCS.get(e.name)))
            out.append("#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]\n#[non_exhaustive]\n")
            out.append(f"pub enum {e.name} {{\n")
            for i, v in enumerate(e.values):
                default = "    #[default]\n" if i == 0 else ""  # request structs derive Default
                out.append(f'    /// `{v}`\n{default}    #[serde(rename = "{v}")]\n    {variant(v)},\n')
            out.append("    /// A value this version of the SDK doesn't know yet.\n    #[serde(other)]\n    Unknown,\n}\n\n")
            out.append(f"impl {e.name} {{\n    /// Every value the SDK knows.\n    pub const ALL: &'static [{e.name}] = &[" +
                       ", ".join(f"{e.name}::{variant(v)}" for v in e.values) + "];\n\n")
            out.append("    /// The value as the API spells it.\n    pub fn as_str(&self) -> &'static str {\n        match self {\n")
            for v in e.values:
                out.append(f'            {e.name}::{variant(v)} => "{v}",\n')
            out.append(f'            {e.name}::Unknown => "UNKNOWN",\n        }}\n    }}\n}}\n\n')
            out.append(f"impl std::fmt::Display for {e.name} {{\n    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{\n"
                       "        f.write_str(self.as_str())\n    }\n}\n\n")
        for o in self.ir.objects.values():
            d = docs.TYPES.get(o.name) or docs.connection_doc(o.name)
            if not d and o.name.endswith("Response"):
                d = "The raw response envelope. Client methods unwrap it; you only need it with `Client::request`."
            used = self.go.used_by.get(o.name)
            if used:
                d = (d + " " if d else "") + "Returned by " + ", ".join(f"[`Client::{snake(u)}`](crate::Client::{snake(u)})" for u in sorted(set(used))) + "."
            out.append(doc(d or "A Zora API object."))
            derive = "Debug, Clone, Default, PartialEq, Serialize, Deserialize"
            out.append(f"#[derive({derive})]\n#[non_exhaustive]\npub struct {o.name} {{\n" if not o.input else f"#[derive({derive})]\npub struct {o.name} {{\n")
            for f in o.fields:
                fd = docs.field_doc(o.name, f.json) or f.description or (docs.PARAMS.get(f.json) if o.input else None)
                required = o.input and f.required
                if required:
                    fd = (fd + " " if fd else "") + "Required."
                out.append(doc(fd, "    "))
                rt = self.rtype(f.type, o.name, f.json)
                lenient = f.type.kind == "scalar" and f.type.format == "lenient"
                attrs = [f'rename = "{f.json}"']
                if lenient:
                    attrs.append('deserialize_with = "crate::de::flex_bool"')
                if required:
                    out.append(f"    #[serde({', '.join(attrs)})]\n    pub {field_ident(f.json)}: {rt},\n")
                else:
                    attrs.append('default, skip_serializing_if = "Option::is_none"')
                    out.append(f"    #[serde({', '.join(attrs)})]\n    pub {field_ident(f.json)}: Option<{rt}>,\n")
            out.append("}\n\n")
            if o.name.endswith("Connection"):
                edges = next((f for f in o.fields if f.json == "edges"), None)
                if edges and edges.type.of and edges.type.of.kind == "object":
                    edge = self.ir.objects[edges.type.of.name]
                    node = next((f for f in edge.fields if f.json == "node"), None)
                    if node and node.type.kind == "object":
                        nt = node.type.name
                        out.append(f"impl {o.name} {{\n")
                        out.append(f"    /// The {nt} values on this page, skipping empty edges.\n")
                        out.append(f"    pub fn nodes(&self) -> impl Iterator<Item = &{nt}> {{\n        self.edges.iter().flatten().filter_map(|e| e.node.as_ref())\n    }}\n\n")
                        out.append(f"    /// Consumes the page, returning its {nt} values.\n")
                        out.append(f"    pub fn into_nodes(self) -> Vec<{nt}> {{\n        self.edges.into_iter().flatten().filter_map(|e| e.node).collect()\n    }}\n\n")
                        if any(f.json == "pageInfo" for f in o.fields):
                            out.append("    /// The cursor for the next page, or `None` on the last page.\n")
                            out.append("    pub fn next_cursor(&self) -> Option<&str> {\n        let info = self.page_info.as_ref()?;\n"
                                       "        if info.has_next_page != Some(true) {\n            return None;\n        }\n        info.end_cursor.as_deref()\n    }\n")
                        out.append("}\n\n")
        return "".join(out)

    # -- endpoints -------------------------------------------------------------------------------
    def _param_field(self, op: irmod.Operation, p: irmod.Param) -> tuple[str, str]:
        if p.name in ("chain", "chainId"):
            return "chain_id", "i64"
        if op.page_size_param == p.name:
            return "page_size", "i64"
        t = p.type
        if t.kind == "list" and t.of:
            return snake(p.name), f"Vec<{self.rtype(t.of)}>"
        return snake(p.name), self.rtype(t)

    def _encode(self, op: irmod.Operation, p: irmod.Param, expr: str, positional: bool) -> str:
        key = p.name
        if p.name in ("chain", "chainId"):
            return f'        q.push(("{key}", {expr}.unwrap_or(BASE_CHAIN_ID).to_string()));\n'
        if p.json_items:
            return f'        for item in {expr} {{\n            q.push(("{key}", serde_json::to_string(item)?));\n        }}\n'
        t = p.type
        conv = lambda v: f"{v}.to_string()" if (t.kind == "enum" or (t.kind == "list" and t.of and t.of.kind == "enum")) else (f"{v}.to_string()")
        if t.kind == "list":
            src = expr if positional else f"{expr}.iter().flatten()"
            return f'        for v in {src} {{\n            q.push(("{key}", {conv("v")}));\n        }}\n'
        if positional:
            return f'        q.push(("{key}", {conv(expr)}));\n'
        return f'        if let Some(v) = &{expr} {{\n            q.push(("{key}", {conv("v")}));\n        }}\n'

    def endpoints(self) -> str:
        out = [HEADER, "//! One method per Zora Coins API endpoint, plus a stream for every paginated one.\n\n"
               "#![allow(clippy::vec_init_then_push)] // generated: every endpoint builds its query the same way\n\n"
               "use futures_core::Stream;\n\nuse crate::client::{paginate, Client, BASE_CHAIN_ID};\nuse crate::error::Result;\nuse crate::models::*;\n\n"]
        methods = []
        for op in self.ir.operations:
            meta = docs.METHODS[op.id]
            m = meta["name"]
            positional = [p for p in op.params if p.required and p.name not in ("chain", "chainId")]
            optional = [p for p in op.params if p not in positional]
            ptype = "".join(x[:1].upper() + x[1:] for x in m.split("_")) + "Params"
            if optional:
                out.append(f"/// Optional parameters of [`Client::{m}`]. `Default::default()` asks for the API's defaults.\n")
                out.append(f"#[derive(Debug, Clone, Default, PartialEq)]\n#[non_exhaustive]\npub struct {ptype} {{\n")
                for p in optional:
                    fname, ft = self._param_field(op, p)
                    out.append(doc(docs.PARAMS.get(p.name) or p.description, "    "))
                    out.append(f"    pub {fname}: Option<{ft}>,\n")
                out.append("}\n\n")
                # builder-style setters so callers can write Params::default().page_size(50)
                out.append(f"impl {ptype} {{\n")
                for p in optional:
                    fname, ft = self._param_field(op, p)
                    arg = "impl Into<String>" if ft == "String" else ft
                    val = "v.into()" if ft == "String" else "v"
                    out.append(f"    /// Sets `{fname}`.\n    pub fn {fname}(mut self, v: {arg}) -> Self {{\n        self.{fname} = Some({val});\n        self\n    }}\n\n")
                out.append("}\n\n")
            args = ["&self"]
            for p in positional:
                t = p.type
                if p.json_items:
                    args.append(f"{snake(p.name)}: &[{self.rtype(t.of)}]")
                elif t.kind == "enum":
                    args.append(f"{snake(p.name)}: {self.rtype(t)}")
                else:
                    args.append(f"{snake(p.name)}: &str")
            if optional:
                args.append(f"params: impl Into<Option<{ptype}>>")
            if op.body:
                args.append(f"req: &{op.body}")
            if op.connection:
                ret = self.go._conn_type(op)
                ret = rust_type_name(ret)
                ret_ty = ret
            elif op.unwrap:
                uf = next(f for f in self.ir.objects[op.response].fields if f.json == op.unwrap)
                inner = self.rtype(uf.type)
                ret_ty = inner if uf.type.kind == "list" else f"Option<{inner}>"
            else:
                ret_ty = op.response
            d = meta["doc"]
            if op.connection:
                d += f" Returns one page; [`Client::iter_{m}`] streams every page."
            if meta.get("not_found"):
                d += " Returns `Ok(None)` if there is no such " + ("coin" if "coin" in m or "token" in m else "profile" if "profile" in m else "record") + "."
            methods.append(doc(d, "    ") + f"    ///\n    /// `{op.method} {op.path}`\n")
            methods.append(f"    pub async fn {m}({', '.join(args)}) -> Result<{ret_ty}> {{\n")
            if optional:
                methods.append("        let params = params.into().unwrap_or_default();\n")
            methods.append("        #[allow(unused_mut)]\n        let mut q: Vec<(&str, String)> = Vec::new();\n")
            for p in op.params:
                if p in positional:
                    expr = snake(p.name)
                    methods.append(self._encode(op, p, expr, True))
                else:
                    fname, _ = self._param_field(op, p)
                    methods.append(self._encode(op, p, f"params.{fname}", False))
            body = "Some(serde_json::to_value(req)?)" if op.body else "None"
            methods.append(f'        let resp: {op.response} = self.request("{op.method}", "{op.path}", &q, {body}).await?;\n')
            if op.connection:
                chain = "Some(resp)"
                for k in op.connection:
                    chain += f".and_then(|x| x.{field_ident(k)})"
                    # boxed fields need unboxing
                methods.append(f"        Ok({self._unbox_chain(op)}.unwrap_or_default())\n    }}\n\n")
            elif op.unwrap:
                uf = next(f for f in self.ir.objects[op.response].fields if f.json == op.unwrap)
                if uf.type.kind == "list":
                    methods.append(f"        Ok(resp.{field_ident(op.unwrap)}.unwrap_or_default())\n    }}\n\n")
                else:
                    methods.append(f"        Ok(resp.{field_ident(op.unwrap)})\n    }}\n\n")
            else:
                methods.append("        Ok(resp)\n    }\n\n")
            if op.connection:
                node = rust_type_name(op.node_type)
                pos_names = [snake(p.name) for p in positional]
                sargs = ["&'a self"] + [a.replace("&str", "&'a str") for a in args[1:]]
                methods.append(f"    /// Streams every {node} across all pages, fetching the next page only as the stream is\n"
                               f"    /// polled. Drop the stream to stop early. `params.after` picks the starting point.\n    ///\n"
                               f"    /// ```no_run\n    /// # async fn run(client: zora_coins::Client) -> zora_coins::Result<()> {{\n"
                               f"    /// use futures_util::TryStreamExt;\n"
                               f"    /// let mut stream = std::pin::pin!(client.iter_{m}({', '.join(self._example_args(op, positional))}));\n"
                               f"    /// while let Some(item) = stream.try_next().await? {{\n    ///     println!(\"{{item:?}}\");\n    /// }}\n"
                               f"    /// # Ok(()) }}\n    /// ```\n")
                methods.append(f"    pub fn iter_{m}<'a>({', '.join(sargs)}) -> impl Stream<Item = Result<{node}>> + 'a {{\n")
                methods.append("        let params = params.into().unwrap_or_default();\n")
                call_pos = "".join(f"{n}, " for n in pos_names)
                methods.append(f"        paginate(params, move |p: {ptype}| async move {{\n"
                               f"            let page = self.{m}({call_pos}p).await?;\n"
                               f"            let next = page.next_cursor().map(str::to_owned);\n"
                               f"            Ok((page.into_nodes(), next))\n"
                               f"        }}, |p, cursor| p.after = Some(cursor))\n    }}\n\n")
        out.append("impl Client {\n" + "".join(methods) + "}\n")
        return "".join(out)

    def _example_args(self, op: irmod.Operation, positional: list[irmod.Param]) -> list[str]:
        out = []
        for p in positional:
            if p.type.kind == "enum":
                e = self.ir.enums[p.type.name]
                out.append(f"zora_coins::{p.type.name}::{variant(e.values[0])}")
            elif p.json_items:
                out.append("&[]")
            else:
                out.append({"address": '"0x0b8590d3c0b1ee6c797e184a4afbb15f8f58a46b"', "identifier": '"jacob"', "text": '"zora"', "name": '"base"'}.get(p.name, '"..."'))
        out.append("None")
        return out

    def _unbox_chain(self, op: irmod.Operation) -> str:
        expr = "Some(resp)"
        t = op.response
        for k in op.connection or []:
            boxed = (t, k) in self.boxed
            expr += f".and_then(|x| x.{field_ident(k)})" + (".map(|b| *b)" if boxed else "")
            f = next(f for f in self.ir.objects[t].fields if f.json == k)
            t = f.type.name
        return expr


def main() -> None:
    model = irmod.build()
    r = Rust(model)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "models.rs").write_text(r.models())
    (OUT / "endpoints.rs").write_text(r.endpoints())
    subprocess.run(["rustfmt", "--edition", "2021", str(OUT / "models.rs"), str(OUT / "endpoints.rs")], check=False)
    print(f"wrote rust/src/models.rs and endpoints.rs: {len(model.objects)} types, {len(model.enums)} enums, "
          f"{len(model.operations)} endpoints; boxed fields: {sorted(r.boxed) or 'none'}")


if __name__ == "__main__":
    main()
