"""Emit the TypeScript SDK's generated files from the IR: interfaces and the client's endpoint methods."""

from __future__ import annotations

import textwrap
from pathlib import Path

import docs
import ir as irmod
from emit_go import Go, go_arg, words

OUT = Path(__file__).resolve().parent.parent / "typescript" / "src"
HEADER = "// Code generated by codegen/emit_ts.py from Zora's OpenAPI spec. DO NOT EDIT.\n\n"


def jsdoc(text: str | None, indent: str = "") -> str:
    if not text:
        return ""
    lines = textwrap.wrap(text.replace("*/", "*\\/"), 96 - len(indent))
    if len(lines) == 1:
        return f"{indent}/** {lines[0]} */\n"
    return f"{indent}/**\n" + "".join(f"{indent} * {l}\n" for l in lines) + f"{indent} */\n"


def const_key(v: str) -> str:
    return "".join(w[:1].upper() + w[1:].lower() for w in words(v.lower() if not v.islower() else v)) or "Empty"


def camel(snake: str) -> str:
    parts = snake.split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def ts_type(t: irmod.TypeRef) -> str:
    if t.kind == "list" and t.of:
        inner = ts_type(t.of)
        return f"Array<{inner}>" if "|" in inner else f"{inner}[]"
    if t.kind == "scalar":
        return {"string": "string", "int": "number", "float": "number", "bool": "boolean"}[t.name]
    if t.kind == "json":
        return "unknown"
    return t.name


def prop(name: str) -> str:
    return name if name.replace("_", "a").isalnum() and not name[0].isdigit() else f'"{name}"'


class TS:
    def __init__(self, model: irmod.IR) -> None:
        self.ir = model
        self.go = Go(model)

    def models(self) -> str:
        out = [HEADER, "/**\n * Every type the Zora Coins API returns or accepts. Response fields are all optional: the API returns\n"
               " * a different selection of a coin's fields from each endpoint, and leaves out some its own spec marks\n"
               " * required. Enum types also accept any string, so a value Zora adds later still type-checks.\n * @module\n */\n\n"]
        for e in self.ir.enums.values():
            out.append(jsdoc(docs.ENUM_DOCS.get(e.name)))
            out.append(f"export const {e.name} = {{\n" + "".join(f'  {const_key(v)}: "{v}",\n' for v in e.values) + "} as const;\n")
            out.append(jsdoc(docs.ENUM_DOCS.get(e.name)))
            out.append(f"export type {e.name} = (typeof {e.name})[keyof typeof {e.name}] | (string & {{}});\n\n")
        for o in self.ir.objects.values():
            d = docs.TYPES.get(o.name) or docs.connection_doc(o.name)
            if d:
                d = d.replace("Nodes() lists them", "`nodes(page)` lists them")
            if not d and o.name.endswith("Response"):
                d = "The raw response envelope. Client methods unwrap it."
            out.append(jsdoc(d or "A Zora API object."))
            out.append(f"export interface {o.name} {{\n")
            for f in o.fields:
                fd = docs.field_doc(o.name, f.json) or f.description or (docs.PARAMS.get(f.json) if o.input else None)
                opt = "" if (o.input and f.required) else "?"
                null = "" if o.input else " | null"
                out.append(jsdoc(fd, "  "))
                out.append(f"  {prop(f.json)}{opt}: {ts_type(f.type)}{null};\n")
            out.append("}\n\n")
        return "".join(out)

    def _param_field(self, op: irmod.Operation, p: irmod.Param) -> tuple[str, str]:
        if p.name in ("chain", "chainId"):
            return "chainId", "number"
        if op.page_size_param == p.name:
            return "pageSize", "number"
        return p.name, ts_type(p.type)

    def client(self) -> str:
        out = [HEADER, 'import { BASE_CHAIN_ID, BaseClient, paginate } from "./base.js";\n',
               'import type * as M from "./models.js";\n\n']
        methods, params_types = [], []
        for op in self.ir.operations:
            meta = docs.METHODS[op.id]
            m = camel(meta["name"])
            ptype = m[:1].upper() + m[1:] + "Params"
            positional = [p for p in op.params if p.required and p.name not in ("chain", "chainId")]
            optional = [p for p in op.params if p not in positional]
            if optional:
                params_types.append(jsdoc(f"Optional parameters of `ZoraCoins.{m}`."))
                params_types.append(f"export interface {ptype} {{\n")
                for p in optional:
                    fname, ft = self._param_field(op, p)
                    params_types.append(jsdoc(docs.PARAMS.get(p.name) or p.description, "  "))
                    params_types.append(f"  {fname}?: {ft if not ft.startswith(tuple(self.ir.enums)) else 'M.' + ft};\n")
                params_types.append("}\n\n")
            args = []
            for p in positional:
                t = ts_type(p.type)
                if p.type.kind == "enum" or (p.type.kind == "list" and p.type.of and p.type.of.kind == "object"):
                    t = "M." + t if p.type.kind == "enum" else f"M.{p.type.of.name}[]"
                args.append(f"{go_arg(p.name)}: {t}")
            if optional:
                args.append(f"params: {ptype} = {{}}")
            if op.body:
                args.append(f"req: M.{op.body}")
            if op.connection:
                ret = "M." + self.go._conn_type(op)
                path = "".join(f"?.{k}" for k in op.connection)
                ret_expr = f"resp{path} ?? {{}}"
            elif op.unwrap:
                uf = next(f for f in self.ir.objects[op.response].fields if f.json == op.unwrap)
                t = ts_type(uf.type)
                if uf.type.kind == "list":
                    ret, ret_expr = f"M.{uf.type.of.name}[]" if uf.type.of.kind == "object" else t, f"resp.{op.unwrap} ?? []"
                else:
                    ret = (f"M.{t}" if uf.type.kind == "object" else t) + " | null"
                    ret_expr = f"resp.{op.unwrap} ?? null"
            else:
                ret, ret_expr = f"M.{op.response}", "resp"
            d = meta["doc"]
            if op.connection:
                d += f" Returns one page; `iter{m[:1].upper() + m[1:]}` walks every page."
            if meta.get("not_found"):
                d += " Resolves to `null` if there is no such " + ("coin" if "coin" in m.lower() or "token" in m.lower() else "profile" if "profile" in m.lower() else "record") + "."
            methods.append(jsdoc(d + f" `{op.method} {op.path}`", "  "))
            methods.append(f"  async {m}({', '.join(args)}): Promise<{ret}> {{\n")
            methods.append("    const q: Array<[string, string]> = [];\n")
            for p in op.params:
                if p in positional:
                    expr = go_arg(p.name)
                    if p.json_items:
                        methods.append(f'    for (const item of {expr}) q.push(["{p.name}", JSON.stringify(item)]);\n')
                    else:
                        methods.append(f'    q.push(["{p.name}", String({expr})]);\n')
                else:
                    fname, _ = self._param_field(op, p)
                    if fname == "chainId":
                        methods.append(f'    q.push(["{p.name}", String(params.chainId ?? BASE_CHAIN_ID)]);\n')
                    elif p.type.kind == "list":
                        methods.append(f'    for (const v of params.{fname} ?? []) q.push(["{p.name}", String(v)]);\n')
                    else:
                        methods.append(f'    if (params.{fname} !== undefined) q.push(["{p.name}", String(params.{fname})]);\n')
            body = ", req" if op.body else ""
            methods.append(f'    const resp = await this.request<M.{op.response}>("{op.method}", "{op.path}", q{body});\n')
            for f in self.ir.objects[op.response].fields:
                if f.type.kind == "scalar" and f.type.format == "lenient":  # the API sends "true" for a boolean
                    methods.append(f'    const raw{f.json.title()} = (resp as {{ {f.json}?: unknown }}).{f.json};\n'
                                   f'    if (typeof raw{f.json.title()} === "string") resp.{f.json} = raw{f.json.title()} === "true";\n')
            methods.append(f"    return {ret_expr};\n  }}\n\n")
            if op.connection:
                node = op.node_type
                it = "iter" + m[:1].upper() + m[1:]
                pos_names = [go_arg(p.name) for p in positional]
                methods.append(jsdoc(f"Every {node} across all pages, fetched as the loop reaches them. `break` stops early; "
                                     "`params.after` picks the starting point.", "  "))
                methods.append(f"  {it}({', '.join(args)}): AsyncGenerator<M.{node}, void, undefined> {{\n")
                call = ", ".join(pos_names + ["p"])
                methods.append(f"    return paginate<{ptype}, M.{node}>(params, async (p) => {{\n"
                               f"      const page = await this.{m}({call});\n"
                               "      const nodes = (page.edges ?? []).flatMap((e) => (e?.node ? [e.node] : []));\n"
                               "      return [nodes, page.pageInfo?.hasNextPage ? page.pageInfo.endCursor ?? undefined : undefined];\n"
                               "    });\n  }\n\n")
        out += params_types
        out.append("/**\n * Client for the Zora Coins API: one method per endpoint, and an `iter…` async generator for every\n"
                   " * paginated one. Use {@link ZoraCoins}, which adds conveniences on top.\n */\n")
        out.append("export class GeneratedClient extends BaseClient {\n" + "".join(methods).rstrip() + "\n}\n")
        return "".join(out)


def main() -> None:
    model = irmod.build()
    t = TS(model)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "models.ts").write_text(t.models())
    (OUT / "client.ts").write_text(t.client())
    print(f"wrote typescript/src/models.ts and client.ts: {len(model.objects)} types, {len(model.enums)} enums, {len(model.operations)} endpoints")


if __name__ == "__main__":
    main()
