"""Emit the Go SDK's generated files from the IR: models, nil-safe getters, and endpoint methods."""

from __future__ import annotations

import re
import subprocess
import textwrap
from pathlib import Path

import docs
import ir as irmod

OUT = Path(__file__).resolve().parent.parent / "go" / "zora"
HEADER = "// Code generated by codegen/emit_go.py from Zora's OpenAPI spec. DO NOT EDIT.\n\n"

_INITIALISMS = {"id": "ID", "url": "URL", "uri": "URI", "api": "API", "usd": "USD", "usdc": "USDC", "jwt": "JWT",
                "http": "HTTP", "json": "JSON", "ipfs": "IPFS", "eth": "ETH", "erc20": "ERC20", "eoa": "EOA", "ids": "IDs"}


def words(s: str) -> list[str]:
    s = re.sub(r"[^0-9a-zA-Z]+", " ", s)
    out = []
    for chunk in s.split():
        # digits stay with the letters before them: V4, ERC20, token0, volume24h
        out += re.findall(r"[A-Z]+[0-9]*(?![a-z])|[A-Z]?[a-z0-9]+|[A-Z]", chunk) or [chunk]
    return out


def go_name(s: str) -> str:
    return "".join(_INITIALISMS.get(w.lower(), w[:1].upper() + w[1:].lower() if w.isupper() and len(w) > 1 else w[:1].upper() + w[1:])
                   for w in words(s))


def go_arg(s: str) -> str:
    """lowerCamel Go identifier: apiKey, listType, address."""
    w = words(s)
    first = w[0].lower()
    return first + go_name("".join(x[:1].upper() + x[1:] for x in w[1:])) if len(w) > 1 else first


def go_type_name(name: str) -> str:
    # IR names are already PascalCase; only fix initialisms (ApiKey -> APIKey, Erc20Token -> ERC20Token)
    return go_name(name)


_VERBS = {"Look": "looks", "Search": "searches", "Quote": "quotes", "Build": "builds", "Create": "creates", "Find": "finds",
          "Wraps": "wraps", "Whether": None}


def go_doc(name: str, doc: str | None, kind: str) -> str | None:
    """Go style: a doc comment is a sentence starting with the identifier (ST1020/ST1021)."""
    if not doc:
        return None
    first, _, rest = doc.partition(" ")
    if first in _VERBS and _VERBS[first]:
        return f"{name} {_VERBS[first]} {rest}"
    lower = doc[:1].lower() + doc[1:]
    if kind == "method":
        return f"{name} returns {lower}"
    if first in ("A", "An", "The", "One", "What", "Where", "How", "Which", "Whether", "Native", "ERC-20", "Symbol", "Several", "Basic"):
        return f"{name} is {lower}" if first not in ("What", "Where", "How", "Which", "Whether") else f"{name} describes {lower}"
    return f"{name} is {lower}"


def comment(text: str | None, indent: str = "", prefix: str = "") -> str:
    if not text:
        return ""
    body = (prefix + text).strip()
    lines = textwrap.wrap(body, 96 - len(indent))
    return "".join(f"{indent}// {l}\n" for l in lines)


class Go:
    def __init__(self, model: irmod.IR) -> None:
        self.ir = model
        self.used_by: dict[str, list[str]] = {}
        for op in model.operations:
            m = docs.METHODS[op.id]["name"]
            for t in filter(None, [op.unwrap_type, op.node_type]):
                self.used_by.setdefault(t, []).append(go_name(m))

    # -- types -----------------------------------------------------------------------------------
    def gtype(self, t: irmod.TypeRef, optional: bool = True) -> str:
        if t.kind == "list" and t.of:
            inner = self.gtype(t.of, optional=False)
            if t.of.kind == "object":
                inner = "*" + go_type_name(t.of.name)
            return "[]" + inner
        if t.kind == "scalar" and t.name == "bool" and t.format == "lenient":
            return "*FlexBool" if optional else "FlexBool"
        base = {
            "scalar": {"string": "string", "int": "int", "float": "float64", "bool": "bool"}.get(t.name, "any"),
            "object": go_type_name(t.name),
            "enum": go_type_name(t.name),
            "json": "json.RawMessage",
        }[t.kind]
        if t.kind == "json":
            return base
        return ("*" + base) if optional else base

    def models(self) -> str:
        uses_json = any(f.type.kind == "json" or (f.type.of and f.type.of.kind == "json") for o in self.ir.objects.values() for f in o.fields)
        out = [HEADER, "package zora\n\n" + ("import \"encoding/json\"\n\n" if uses_json else "")]
        for e in self.ir.enums.values():
            n = go_type_name(e.name)
            out.append(comment(go_doc(n, docs.ENUM_DOCS.get(e.name), "type")))
            out.append(f"type {n} string\n\n")
            out.append(f"// {n} values.\nconst (\n")
            for v in e.values:
                out.append(f"\t{n}{go_name(v.lower()) if not v.islower() else go_name(v)} {n} = \"{v}\"\n")
            out.append(")\n\n")
            out.append(f"// All{n}s lists every {n} the SDK knows. The API may add more.\n")
            out.append(f"var All{n}s = []{n}{{" + ", ".join(f"{n}{go_name(v.lower()) if not v.islower() else go_name(v)}" for v in e.values) + "}\n\n")
        for o in self.ir.objects.values():
            n = go_type_name(o.name)
            doc = docs.TYPES.get(o.name) or docs.connection_doc(o.name)
            if not doc and o.name.endswith("Response"):
                doc = "The raw response envelope. Client methods unwrap it; you only need it with Client.Do."
            if not doc and o.input:
                doc = "Part of a request body."
            used = self.used_by.get(o.name)
            if used:
                doc = (doc + " " if doc else "") + "Returned by " + ", ".join(f"Client.{u}" for u in sorted(set(used))) + "."
            out.append(comment(go_doc(n, doc, "type")) if doc else f"// {n} is a Zora API object.\n")
            out.append(f"type {n} struct {{\n")
            for f in o.fields:
                fn = go_name(f.json)
                required = o.input and f.required and f.type.kind in ("scalar", "enum")
                gt = self.gtype(f.type, optional=not required)
                if o.input and f.required and f.type.kind == "object":
                    gt = "*" + go_type_name(f.type.name)
                tag = f.json if (o.input and f.required) else f.json + ",omitempty"
                desc = docs.field_doc(o.name, f.json) or f.description or (docs.PARAMS.get(f.json) if o.input else None)
                if o.input and f.required:
                    desc = (desc + " " if desc else "") + "Required."
                out.append(comment(desc, "\t"))
                out.append(f"\t{fn} {gt} `json:\"{tag}\"`\n")
            out.append("}\n\n")
            if o.name.endswith("Connection"):
                edges = next((f for f in o.fields if f.json == "edges"), None)
                if edges and edges.type.of and edges.type.of.kind == "object":
                    edge = self.ir.objects[edges.type.of.name]
                    node = next((f for f in edge.fields if f.json == "node"), None)
                    if node and node.type.kind == "object":
                        nt = go_type_name(node.type.name)
                        out.append(f"// Nodes returns the {nt} values on this page, skipping empty edges.\n")
                        out.append(f"func (c *{n}) Nodes() []*{nt} {{\n\tif c == nil {{\n\t\treturn nil\n\t}}\n\tout := make([]*{nt}, 0, len(c.Edges))\n"
                                   f"\tfor _, e := range c.Edges {{\n\t\tif e != nil && e.Node != nil {{\n\t\t\tout = append(out, e.Node)\n\t\t}}\n\t}}\n\treturn out\n}}\n\n")
                        if any(f.json == "pageInfo" for f in o.fields):
                            out.append(f"// NextCursor returns the cursor for the next page, or \"\" on the last page.\n")
                            out.append(f"func (c *{n}) NextCursor() string {{\n\tif !c.GetPageInfo().GetHasNextPage() {{\n\t\treturn \"\"\n\t}}\n\treturn c.GetPageInfo().GetEndCursor()\n}}\n\n")
        return "".join(out)

    def accessors(self) -> str:
        out = [HEADER, "package zora\n\n"]
        for o in self.ir.objects.values():
            n = go_type_name(o.name)
            for f in o.fields:
                fn = go_name(f.json)
                required = o.input and f.required and f.type.kind in ("scalar", "enum")
                gt = self.gtype(f.type, optional=not required)
                if f.type.kind == "json":
                    continue
                if gt == "*FlexBool":
                    out.append(f"// Get{fn} returns {n}.{fn}, or false if it or {n} is nil.\n")
                    out.append(f"func (x *{n}) Get{fn}() bool {{\n\tif x == nil || x.{fn} == nil {{\n\t\treturn false\n\t}}\n\treturn bool(*x.{fn})\n}}\n\n")
                    continue
                if gt.startswith("*") and f.type.kind in ("scalar", "enum"):
                    base = gt[1:]
                    zero = {"string": '""', "int": "0", "float64": "0", "bool": "false"}.get(base, '""')
                    out.append(f"// Get{fn} returns {n}.{fn}, or the zero value if it or {n} is nil.\n")
                    out.append(f"func (x *{n}) Get{fn}() {base} {{\n\tif x == nil || x.{fn} == nil {{\n\t\treturn {zero}\n\t}}\n\treturn *x.{fn}\n}}\n\n")
                else:
                    zero = "nil" if gt.startswith(("*", "[]")) else {"string": '""', "int": "0", "float64": "0", "bool": "false"}.get(gt, '""')
                    out.append(f"// Get{fn} returns {n}.{fn}, or {'nil' if zero == 'nil' else 'the zero value'} if {n} is nil.\n")
                    out.append(f"func (x *{n}) Get{fn}() {gt} {{\n\tif x == nil {{\n\t\treturn {zero}\n\t}}\n\treturn x.{fn}\n}}\n\n")
        return "".join(out)

    # -- endpoints -------------------------------------------------------------------------------
    @staticmethod
    def _is_chain(p: irmod.Param) -> bool:
        return p.name in ("chain", "chainId") and p.type.kind == "scalar"

    @staticmethod
    def _is_page_size(op: irmod.Operation, p: irmod.Param) -> bool:
        return op.page_size_param == p.name

    def _param_field(self, op: irmod.Operation, p: irmod.Param) -> tuple[str, str]:
        if self._is_chain(p):
            return "ChainID", "int"
        if self._is_page_size(op, p):
            return "PageSize", "int"
        t = self.gtype(p.type, optional=False)
        if p.type.kind == "scalar" and p.type.name == "bool":
            t = "*bool"  # these default to true server-side, so false must be sendable
        return go_name(p.name), t

    def _encode(self, op: irmod.Operation, p: irmod.Param, expr: str, positional: bool) -> str:
        """Go statements that add parameter p (held in expr) to url.Values q."""
        key = p.name
        t = p.type
        if self._is_chain(p):
            return f'\tq.Set("{key}", strconv.Itoa(chainOrBase({expr})))\n'
        if p.json_items:
            return (f"\tfor _, item := range {expr} {{\n\t\tb, err := json.Marshal(item)\n\t\tif err != nil {{\n\t\t\treturn nil, err\n\t\t}}\n"
                    f'\t\tq.Add("{key}", string(b))\n\t}}\n')
        if t.kind == "list" and t.of:
            conv = {"int": "strconv.Itoa(v)", "string": "v"}.get(t.of.name, "string(v)" if t.of.kind == "enum" else "fmt.Sprint(v)")
            return f'\tfor _, v := range {expr} {{\n\t\tq.Add("{key}", {conv})\n\t}}\n'
        if t.kind == "enum":
            return (f'\tq.Set("{key}", string({expr}))\n' if positional else f'\tif {expr} != "" {{\n\t\tq.Set("{key}", string({expr}))\n\t}}\n')
        if t.name == "string":
            return f'\tq.Set("{key}", {expr})\n' if positional else f'\tif {expr} != "" {{\n\t\tq.Set("{key}", {expr})\n\t}}\n'
        if t.name == "int":
            return f'\tq.Set("{key}", strconv.Itoa({expr}))\n' if positional else f'\tif {expr} != 0 {{\n\t\tq.Set("{key}", strconv.Itoa({expr}))\n\t}}\n'
        if t.name == "bool":
            return f'\tif {expr} != nil {{\n\t\tq.Set("{key}", strconv.FormatBool(*{expr}))\n\t}}\n'
        if t.name == "float":
            return f'\tif {expr} != 0 {{\n\t\tq.Set("{key}", strconv.FormatFloat({expr}, \'f\', -1, 64))\n\t}}\n'
        raise ValueError(f"cannot encode {op.id}.{p.name}")

    def _unwrap_chain(self, op: irmod.Operation, path: list[str]) -> str:
        expr = "resp"
        for k in path:
            expr += f".Get{go_name(k)}()"
        return expr

    def endpoints(self) -> str:
        out = [HEADER, 'package zora\n\nimport (\n\t"context"\n\t"encoding/json"\n\t"fmt"\n\t"iter"\n\t"net/url"\n\t"strconv"\n)\n\n',
               "var _ = fmt.Sprint // not every generated file needs fmt\n\n"]
        for op in self.ir.operations:
            meta = docs.METHODS[op.id]
            m = go_name(meta["name"])
            positional = [p for p in op.params if p.required and not self._is_chain(p)]
            optional = [p for p in op.params if p not in positional]
            ptype = f"{m}Params"
            if optional:
                out.append(f"// {ptype} holds the optional parameters of Client.{m}. The zero value asks for the API's defaults.\n")
                out.append(f"type {ptype} struct {{\n")
                for p in optional:
                    fname, ft = self._param_field(op, p)
                    out.append(comment(docs.PARAMS.get(p.name) or p.description, "\t"))
                    out.append(f"\t{fname} {ft}\n")
                out.append("}\n\n")
            args = ["ctx context.Context"]
            for p in positional:
                args.append(f"{go_arg(p.name)} {self.gtype(p.type, optional=False)}")
            if optional:
                args.append(f"params *{ptype}")
            body_type = go_type_name(op.body) if op.body else None
            if body_type:
                args.append(f"req *{body_type}")
            # what comes back
            if op.connection:
                conn_t = self._conn_type(op)
                ret, ret_expr = "*" + conn_t, self._unwrap_chain(op, op.connection)
            elif op.unwrap:
                uf = next(f for f in self.ir.objects[op.response].fields if f.json == op.unwrap)
                ret = self.gtype(uf.type, optional=uf.type.kind != "scalar")
                ret_expr = f"resp.{go_name(op.unwrap)}" if uf.type.kind == "list" else self._unwrap_chain(op, [op.unwrap])
            else:
                ret, ret_expr = "*" + go_type_name(op.response), "&resp"
            doc = meta["doc"]
            if op.connection:
                doc += f" Returns one page; Iter{m} walks every page."
            if meta.get("not_found"):
                doc += " Returns an error matching ErrNotFound if there is no such " + ("coin" if "coin" in meta["name"] or "token" in meta["name"] else "profile" if "profile" in meta["name"] else "record") + "."
            out.append(comment(go_doc(m, doc, "method")))
            out.append(f"//\n// {op.method} {op.path}\n")
            out.append(f"func (c *Client) {m}({', '.join(args)}) ({ret}, error) {{\n")
            if optional:
                out.append(f"\tif params == nil {{\n\t\tparams = &{ptype}{{}}\n\t}}\n")
            if body_type:
                out.append(f'\tif req == nil {{\n\t\treturn {self._zero(ret)}, fmt.Errorf("zora: {m} needs a request")\n\t}}\n')
            out.append("\tq := url.Values{}\n")
            for p in op.params:
                if p in positional:
                    out.append(self._encode(op, p, go_arg(p.name), True))
                else:
                    fname, _ = self._param_field(op, p)
                    out.append(self._encode(op, p, f"params.{fname}", False))
            out.append(f"\tvar resp {go_type_name(op.response)}\n")
            body = "req" if body_type else "nil"
            out.append(f'\tif err := c.Do(ctx, "{op.method}", "{op.path}", q, {body}, &resp); err != nil {{\n\t\treturn {self._zero(ret)}, err\n\t}}\n')
            if meta.get("not_found") and ret.startswith("*"):
                what = next((p for p in positional), None)
                ident = go_arg(what.name) if what else '""'
                out.append(f"\tout := {ret_expr}\n\tif out == nil {{\n\t\treturn nil, fmt.Errorf(\"%w: {meta['name'].replace('_', ' ')} %v\", ErrNotFound, {ident})\n\t}}\n\treturn out, nil\n}}\n\n")
            else:
                out.append(f"\treturn {ret_expr}, nil\n}}\n\n")
            if op.connection:
                node = go_type_name(op.node_type)
                out.append(f"// Iter{m} yields every {node} across all pages, fetching the next page as the loop reaches it.\n")
                out.append(f"// Stop early with break; an error ends the sequence. params.After picks the starting point.\n//\n")
                out.append(f"//\tfor x, err := range client.Iter{m}(ctx{''.join(', ' + go_arg(p.name) for p in positional)}, nil) {{\n")
                out.append("//\t\tif err != nil {\n//\t\t\treturn err\n//\t\t}\n//\t\t...\n//\t}\n")
                call_args = ", ".join(["ctx"] + [go_arg(p.name) for p in positional])
                out.append(f"func (c *Client) Iter{m}({', '.join(args)}) iter.Seq2[*{node}, error] {{\n")
                out.append(f"\treturn func(yield func(*{node}, error) bool) {{\n\t\tp := {ptype}{{}}\n\t\tif params != nil {{\n\t\t\tp = *params\n\t\t}}\n")
                out.append(f"\t\tseen := map[string]bool{{}}\n\t\tfor {{\n\t\t\tpage, err := c.{m}({call_args}, &p)\n")
                out.append("\t\t\tif err != nil {\n\t\t\t\tyield(nil, err)\n\t\t\t\treturn\n\t\t\t}\n")
                out.append("\t\t\tfor _, n := range page.Nodes() {\n\t\t\t\tif !yield(n, nil) {\n\t\t\t\t\treturn\n\t\t\t\t}\n\t\t\t}\n")
                out.append("\t\t\tnext := page.NextCursor()\n\t\t\tif next == \"\" || seen[next] {\n\t\t\t\treturn // last page (or a cursor that would loop forever)\n\t\t\t}\n")
                out.append("\t\t\tseen[next] = true\n\t\t\tp.After = next\n\t\t}\n\t}\n}\n\n")
        return "".join(out)

    def _conn_type(self, op: irmod.Operation) -> str:
        t = self.ir.objects[op.response]
        for k in op.connection or []:
            f = next(f for f in t.fields if f.json == k)
            t = self.ir.objects[f.type.name]
        return go_type_name(t.name)

    @staticmethod
    def _zero(ret: str) -> str:
        return "nil" if ret.startswith(("*", "[]")) else '""' if ret == "string" else "0"


def main() -> None:
    model = irmod.build()
    g = Go(model)
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in (("models_gen.go", g.models()), ("accessors_gen.go", g.accessors()), ("endpoints_gen.go", g.endpoints())):
        (OUT / name).write_text(text)
    subprocess.run(["gofmt", "-w", str(OUT)], check=True)
    print(f"wrote {OUT}/{{models,accessors,endpoints}}_gen.go: {len(model.objects)} types, {len(model.enums)} enums, {len(model.operations)} endpoints")


if __name__ == "__main__":
    main()
