// <auto-generated>
// Generated by codegen/emit_csharp.py from Zora's OpenAPI spec. Do not edit.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Zora.Coins;

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetCoinAsync"/&gt;. Leave a property null for
/// the API's default.
/// </summary>
public sealed class CoinParams
{
    /// <summary>
    /// Chain ID. Defaults to Base (8453).
    /// </summary>
    public long? ChainId { get; set; }

    internal CoinParams Copy() => (CoinParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetCoinCommentsAsync"/&gt;. Leave a property
/// null for the API's default.
/// </summary>
public sealed class CoinCommentsParams
{
    /// <summary>
    /// Chain ID. Defaults to Base (8453).
    /// </summary>
    public long? ChainId { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    internal CoinCommentsParams Copy() => (CoinCommentsParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetCoinHoldersAsync"/&gt;. Leave a property
/// null for the API's default.
/// </summary>
public sealed class CoinHoldersParams
{
    /// <summary>
    /// Chain ID. Defaults to Base (8453).
    /// </summary>
    public long? ChainId { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    internal CoinHoldersParams Copy() => (CoinHoldersParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetCoinMergedCommentsAsync"/&gt;. Leave a
/// property null for the API's default.
/// </summary>
public sealed class CoinMergedCommentsParams
{
    /// <summary>
    /// Chain ID. Defaults to Base (8453).
    /// </summary>
    public long? ChainId { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    internal CoinMergedCommentsParams Copy() => (CoinMergedCommentsParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetCoinPriceHistoryAsync"/&gt;. Leave a
/// property null for the API's default.
/// </summary>
public sealed class CoinPriceHistoryParams
{
    /// <summary>
    /// Chain ID. Defaults to Base (8453).
    /// </summary>
    public long? ChainId { get; set; }

    internal CoinPriceHistoryParams Copy() => (CoinPriceHistoryParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetCoinSwapsAsync"/&gt;. Leave a property null
/// for the API's default.
/// </summary>
public sealed class CoinSwapsParams
{
    /// <summary>
    /// Chain ID. Defaults to Base (8453).
    /// </summary>
    public long? ChainId { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    internal CoinSwapsParams Copy() => (CoinSwapsParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetCoinsListAsync"/&gt;. Leave a property null
/// for the API's default.
/// </summary>
public sealed class CoinsListParams
{
    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    /// <summary>
    /// Include each coin's price in USDC. Defaults to true.
    /// </summary>
    public bool? IncludeUsdcPrice { get; set; }

    internal CoinsListParams Copy() => (CoinsListParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetContentCoinPoolConfigAsync"/&gt;. Leave a
/// property null for the API's default.
/// </summary>
public sealed class ContentCoinPoolConfigParams
{
    /// <summary>
    /// Profile handle or wallet of the creator, used to pair with their creator coin.
    /// </summary>
    public string? CreatorIdentifier { get; set; }

    internal ContentCoinPoolConfigParams Copy() => (ContentCoinPoolConfigParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetCreatorCoinPoolConfigAsync"/&gt;. Leave a
/// property null for the API's default.
/// </summary>
public sealed class CreatorCoinPoolConfigParams
{
    /// <summary>
    /// Starting market cap to size the pool for, in USD.
    /// </summary>
    public long? TargetMarketCapUsd { get; set; }

    internal CreatorCoinPoolConfigParams Copy() => (CreatorCoinPoolConfigParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetCreatorLivestreamCommentsAsync"/&gt;. Leave
/// a property null for the API's default.
/// </summary>
public sealed class CreatorLivestreamCommentsParams
{
    /// <summary>
    /// Chain ID. Defaults to Base (8453).
    /// </summary>
    public long? ChainId { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    internal CreatorLivestreamCommentsParams Copy() => (CreatorLivestreamCommentsParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.ExploreAsync"/&gt;. Leave a property null for
/// the API's default.
/// </summary>
public sealed class ExploreParams
{
    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    internal ExploreParams Copy() => (ExploreParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetFeaturedCreatorsAsync"/&gt;. Leave a
/// property null for the API's default.
/// </summary>
public sealed class FeaturedCreatorsParams
{
    /// <summary>
    /// Year of the ISO week. Defaults to the current year.
    /// </summary>
    public long? Year { get; set; }

    /// <summary>
    /// ISO week number. Defaults to the current week.
    /// </summary>
    public long? Week { get; set; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    internal FeaturedCreatorsParams Copy() => (FeaturedCreatorsParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetLatestLiveStreamsAsync"/&gt;. Leave a
/// property null for the API's default.
/// </summary>
public sealed class LatestLiveStreamsParams
{
    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    internal LatestLiveStreamsParams Copy() => (LatestLiveStreamsParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetProfileBalancesAsync"/&gt;. Leave a property
/// null for the API's default.
/// </summary>
public sealed class ProfileBalancesParams
{
    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    /// <summary>
    /// How to order the balances.
    /// </summary>
    public SortOption? SortOption { get; set; }

    /// <summary>
    /// Leave out coins the profile has hidden. Defaults to true.
    /// </summary>
    public bool? ExcludeHidden { get; set; }

    /// <summary>
    /// Only include these chains. Defaults to Base.
    /// </summary>
    public IReadOnlyList<long>? ChainIds { get; set; }

    internal ProfileBalancesParams Copy() => (ProfileBalancesParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetProfileCoinsAsync"/&gt;. Leave a property
/// null for the API's default.
/// </summary>
public sealed class ProfileCoinsParams
{
    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    /// <summary>
    /// Only include these chains. Defaults to Base.
    /// </summary>
    public IReadOnlyList<long>? ChainIds { get; set; }

    /// <summary>
    /// Only coins created through one of these platform referrer addresses.
    /// </summary>
    public IReadOnlyList<string>? PlatformReferrerAddress { get; set; }

    internal ProfileCoinsParams Copy() => (ProfileCoinsParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.SearchAsync"/&gt;. Leave a property null for
/// the API's default.
/// </summary>
public sealed class SearchParams
{
    /// <summary>
    /// Only return results of this kind.
    /// </summary>
    public EntityType? EntityType { get; set; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    internal SearchParams Copy() => (SearchParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetTokenInfoAsync"/&gt;. Leave a property null
/// for the API's default.
/// </summary>
public sealed class TokenInfoParams
{
    /// <summary>
    /// Chain ID. Defaults to Base (8453).
    /// </summary>
    public long? ChainId { get; set; }

    internal TokenInfoParams Copy() => (TokenInfoParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetTopLiveStreamsAsync"/&gt;. Leave a property
/// null for the API's default.
/// </summary>
public sealed class TopLiveStreamsParams
{
    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    internal TopLiveStreamsParams Copy() => (TopLiveStreamsParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetTraderLeaderboardAsync"/&gt;. Leave a
/// property null for the API's default.
/// </summary>
public sealed class TraderLeaderboardParams
{
    /// <summary>
    /// ISO week number. Defaults to the current week.
    /// </summary>
    public long? Week { get; set; }

    /// <summary>
    /// Year of the ISO week. Defaults to the current year.
    /// </summary>
    public long? Year { get; set; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    internal TraderLeaderboardParams Copy() => (TraderLeaderboardParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetTrendCoinAsync"/&gt;. Leave a property null
/// for the API's default.
/// </summary>
public sealed class TrendCoinParams
{
    /// <summary>
    /// Chain ID. Defaults to Base (8453).
    /// </summary>
    public long? ChainId { get; set; }

    internal TrendCoinParams Copy() => (TrendCoinParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetTrendsByNameAsync"/&gt;. Leave a property
/// null for the API's default.
/// </summary>
public sealed class TrendsByNameParams
{
    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    internal TrendsByNameParams Copy() => (TrendsByNameParams)MemberwiseClone();
}

/// <summary>
/// Optional parameters of &lt;see cref="ZoraCoinsClient.GetWalletTradeActivityAsync"/&gt;. Leave a
/// property null for the API's default.
/// </summary>
public sealed class WalletTradeActivityParams
{
    /// <summary>
    /// Cursor to continue from: the previous page's pageInfo.endCursor.
    /// </summary>
    public string? After { get; set; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int? PageSize { get; set; }

    internal WalletTradeActivityParams Copy() => (WalletTradeActivityParams)MemberwiseClone();
}

public sealed partial class ZoraCoinsClient
{
    /// <summary>
    /// Look up an API key: whether it exists and is active. (GET /apiKey)
    /// </summary>
    public async Task<ApiKey?> GetApiKeyAsync(string apiKey, CancellationToken cancellationToken = default)
    {
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("apiKey", apiKey));
        var resp = await SendAsync<ApiKeyResponse>("GET", "/apiKey", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.ApiKey;
    }

    /// <summary>
    /// One coin by contract address: market data, creator profile, media, pool key and creator
    /// earnings. Returns null if there is no such coin. (GET /coin)
    /// </summary>
    public async Task<Zora20Token?> GetCoinAsync(string address, CoinParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("address", address));
        q.Add(new("chain", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));
        var resp = await SendAsync<CoinResponse>("GET", "/coin", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Zora20Token;
    }

    /// <summary>
    /// Comments posted on a coin, newest first. Returns one page; EnumerateCoinCommentsAsync walks
    /// every page. (GET /coinComments)
    /// </summary>
    public async Task<ZoraCommentConnection> GetCoinCommentsAsync(string address, CoinCommentsParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("address", address));
        q.Add(new("chain", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        if (parameters.PageSize != null) q.Add(new("count", Format(parameters.PageSize)));
        var resp = await SendAsync<CoinCommentsResponse>("GET", "/coinComments", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Zora20Token?.ZoraComments ?? new ZoraCommentConnection();
    }

    /// <summary>
    /// Every ZoraComment across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<ZoraComment> EnumerateCoinCommentsAsync(string address, CoinCommentsParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new CoinCommentsParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetCoinCommentsAsync(address, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// Holders of a coin and their balances, largest first. Returns one page; EnumerateCoinHoldersAsync
    /// walks every page. (GET /coinHolders)
    /// </summary>
    public async Task<TokenBalanceConnection> GetCoinHoldersAsync(string address, CoinHoldersParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("chainId", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));
        q.Add(new("address", address));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        if (parameters.PageSize != null) q.Add(new("count", Format(parameters.PageSize)));
        var resp = await SendAsync<CoinHoldersResponse>("GET", "/coinHolders", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Zora20Token?.TokenBalances ?? new TokenBalanceConnection();
    }

    /// <summary>
    /// Every TokenBalance across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<TokenBalance> EnumerateCoinHoldersAsync(string address, CoinHoldersParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new CoinHoldersParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetCoinHoldersAsync(address, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// A coin's comment feed with replies threaded in, newest first. Returns one page;
    /// EnumerateCoinMergedCommentsAsync walks every page. (GET /coinMergedComments)
    /// </summary>
    public async Task<CommentConnection> GetCoinMergedCommentsAsync(string address, CoinMergedCommentsParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("address", address));
        q.Add(new("chain", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        if (parameters.PageSize != null) q.Add(new("count", Format(parameters.PageSize)));
        var resp = await SendAsync<CoinMergedCommentsResponse>("GET", "/coinMergedComments", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Zora20Token?.Comments ?? new CommentConnection();
    }

    /// <summary>
    /// Every Comment across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<Comment> EnumerateCoinMergedCommentsAsync(string address, CoinMergedCommentsParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new CoinMergedCommentsParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetCoinMergedCommentsAsync(address, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// A coin's price history at five resolutions: the last hour, day, week, month, and all time.
    /// Returns null if there is no such coin. (GET /coinPriceHistory)
    /// </summary>
    public async Task<Zora20Token?> GetCoinPriceHistoryAsync(string address, CoinPriceHistoryParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("address", address));
        q.Add(new("chain", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));
        var resp = await SendAsync<CoinPriceHistoryResponse>("GET", "/coinPriceHistory", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Zora20Token;
    }

    /// <summary>
    /// Buys and sells of a coin, newest first. Returns one page; EnumerateCoinSwapsAsync walks every
    /// page. (GET /coinSwaps)
    /// </summary>
    public async Task<SwapActivityConnection> GetCoinSwapsAsync(string address, CoinSwapsParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("address", address));
        q.Add(new("chain", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        if (parameters.PageSize != null) q.Add(new("first", Format(parameters.PageSize)));
        var resp = await SendAsync<CoinSwapsResponse>("GET", "/coinSwaps", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Zora20Token?.SwapActivities ?? new SwapActivityConnection();
    }

    /// <summary>
    /// Every SwapActivity across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<SwapActivity> EnumerateCoinSwapsAsync(string address, CoinSwapsParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new CoinSwapsParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetCoinSwapsAsync(address, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// Several coins in one request. Missing coins are left out of the result. (GET /coins)
    /// </summary>
    public async Task<IReadOnlyList<Zora20Token>> GetCoinsAsync(IEnumerable<CoinRefInput> coins, CancellationToken cancellationToken = default)
    {
        var q = new List<KeyValuePair<string, string>>();
        foreach (var item in coins) q.Add(new("coins", JsonSerializer.Serialize(item, Json.Options)));
        var resp = await SendAsync<CoinsResponse>("GET", "/coins", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Zora20Tokens ?? Array.Empty<Zora20Token>();
    }

    /// <summary>
    /// Basic information (address, name, symbol, price) for every coin, in pages of up to 1,000.
    /// Returns one page; EnumerateCoinsListAsync walks every page. (GET /coinsList)
    /// </summary>
    public async Task<CoinBasicInfoConnection> GetCoinsListAsync(CoinsListParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        if (parameters.PageSize != null) q.Add(new("first", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        if (parameters.IncludeUsdcPrice != null) q.Add(new("includeUSDCPrice", Format(parameters.IncludeUsdcPrice)));
        var resp = await SendAsync<CoinsListResponse>("GET", "/coinsList", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.CoinsBasicInfo ?? new CoinBasicInfoConnection();
    }

    /// <summary>
    /// Every CoinBasicInfo across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<CoinBasicInfo> EnumerateCoinsListAsync(CoinsListParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new CoinsListParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetCoinsListAsync(p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// The Uniswap V4 pool configuration Zora uses to launch a content coin paired with the given
    /// currency. (GET /contentCoinPoolConfig)
    /// </summary>
    public async Task<PoolConfig?> GetContentCoinPoolConfigAsync(CurrencyType currencyType, ContentCoinPoolConfigParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        if (parameters.CreatorIdentifier != null) q.Add(new("creatorIdentifier", Format(parameters.CreatorIdentifier)));
        q.Add(new("currencyType", currencyType.Value));
        var resp = await SendAsync<ContentCoinPoolConfigResponse>("GET", "/contentCoinPoolConfig", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.ContentCoinPoolConfig;
    }

    /// <summary>
    /// Create a short-lived token for uploading coin media and metadata to Zora's uploader. Requires an
    /// API key. (POST /createUploadJWT)
    /// </summary>
    public async Task<string?> CreateUploadJwtAsync(CreateUploadJwtRequest request, CancellationToken cancellationToken = default)
    {
        var q = new List<KeyValuePair<string, string>>();
        var resp = await SendAsync<CreateUploadJwtResponse>("POST", "/createUploadJWT", q, request, cancellationToken).ConfigureAwait(false);
        return resp?.CreateUploadJwtFromApiKey;
    }

    /// <summary>
    /// The Uniswap V4 pool configuration Zora uses to launch a creator coin, optionally sized for a
    /// starting market cap in USD. (GET /creatorCoinPoolConfig)
    /// </summary>
    public async Task<PoolConfig?> GetCreatorCoinPoolConfigAsync(CreatorCoinPoolConfigParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        if (parameters.TargetMarketCapUsd != null) q.Add(new("targetMarketCapUsd", Format(parameters.TargetMarketCapUsd)));
        var resp = await SendAsync<CreatorCoinPoolConfigResponse>("GET", "/creatorCoinPoolConfig", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.CreatorCoinPoolConfig;
    }

    /// <summary>
    /// Comments on the live stream of the creator behind a coin. Returns one page;
    /// EnumerateCreatorLivestreamCommentsAsync walks every page. (GET /creatorLivestreamComments)
    /// </summary>
    public async Task<CommentConnection> GetCreatorLivestreamCommentsAsync(string address, CreatorLivestreamCommentsParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("address", address));
        q.Add(new("chain", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        if (parameters.PageSize != null) q.Add(new("count", Format(parameters.PageSize)));
        var resp = await SendAsync<CreatorLivestreamCommentsResponse>("GET", "/creatorLivestreamComments", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Zora20Token?.CreatorProfile?.LiveStream?.Comments ?? new CommentConnection();
    }

    /// <summary>
    /// Every Comment across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<Comment> EnumerateCreatorLivestreamCommentsAsync(string address, CreatorLivestreamCommentsParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new CreatorLivestreamCommentsParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetCreatorLivestreamCommentsAsync(address, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// A Zora Explore list: top gainers, 24h volume, newest, most valuable creators and more. See
    /// ListType for all 25. Returns one page; EnumerateExploreAsync walks every page. (GET /explore)
    /// </summary>
    public async Task<Zora20TokenConnection> ExploreAsync(ListType listType, ExploreParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("listType", listType.Value));
        if (parameters.PageSize != null) q.Add(new("count", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        var resp = await SendAsync<ExploreResponse>("GET", "/explore", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.ExploreList ?? new Zora20TokenConnection();
    }

    /// <summary>
    /// Every Zora20Token across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<Zora20Token> EnumerateExploreAsync(ListType listType, ExploreParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new ExploreParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await ExploreAsync(listType, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// Creators featured on the weekly leaderboard. Defaults to the current week. Returns one page;
    /// EnumerateFeaturedCreatorsAsync walks every page. (GET /featuredCreators)
    /// </summary>
    public async Task<FeaturedCreatorConnection> GetFeaturedCreatorsAsync(FeaturedCreatorsParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        if (parameters.Year != null) q.Add(new("year", Format(parameters.Year)));
        if (parameters.Week != null) q.Add(new("week", Format(parameters.Week)));
        if (parameters.PageSize != null) q.Add(new("first", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        var resp = await SendAsync<FeaturedCreatorsResponse>("GET", "/featuredCreators", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.TraderLeaderboardFeaturedCreators ?? new FeaturedCreatorConnection();
    }

    /// <summary>
    /// Every FeaturedCreator across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<FeaturedCreator> EnumerateFeaturedCreatorsAsync(FeaturedCreatorsParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new FeaturedCreatorsParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetFeaturedCreatorsAsync(p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// Live streams, most recently started first. Returns one page; EnumerateLatestLiveStreamsAsync
    /// walks every page. (GET /latestLiveStreams)
    /// </summary>
    public async Task<LiveStreamConnection> GetLatestLiveStreamsAsync(LatestLiveStreamsParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        if (parameters.PageSize != null) q.Add(new("first", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        var resp = await SendAsync<LatestLiveStreamsResponse>("GET", "/latestLiveStreams", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.LatestLiveStreams ?? new LiveStreamConnection();
    }

    /// <summary>
    /// Every LiveStream across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<LiveStream> EnumerateLatestLiveStreamsAsync(LatestLiveStreamsParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new LatestLiveStreamsParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetLatestLiveStreamsAsync(p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// A profile by handle or wallet address, with its linked wallets and creator coin. Returns null if
    /// there is no such profile. (GET /profile)
    /// </summary>
    public async Task<Profile?> GetProfileAsync(string identifier, CancellationToken cancellationToken = default)
    {
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("identifier", identifier));
        var resp = await SendAsync<ProfileResponse>("GET", "/profile", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Profile;
    }

    /// <summary>
    /// Coins a profile holds, with balances and current values. Returns one page;
    /// EnumerateProfileBalancesAsync walks every page. (GET /profileBalances)
    /// </summary>
    public async Task<CoinBalanceConnection> GetProfileBalancesAsync(string identifier, ProfileBalancesParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("identifier", identifier));
        if (parameters.PageSize != null) q.Add(new("count", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        if (parameters.SortOption != null) q.Add(new("sortOption", Format(parameters.SortOption)));
        if (parameters.ExcludeHidden != null) q.Add(new("excludeHidden", Format(parameters.ExcludeHidden)));
        if (parameters.ChainIds != null) foreach (var v in parameters.ChainIds) q.Add(new("chainIds", Format(v)));
        var resp = await SendAsync<ProfileBalancesResponse>("GET", "/profileBalances", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Profile?.CoinBalances ?? new CoinBalanceConnection();
    }

    /// <summary>
    /// Every CoinBalance across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<CoinBalance> EnumerateProfileBalancesAsync(string identifier, ProfileBalancesParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new ProfileBalancesParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetProfileBalancesAsync(identifier, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// Find a Zora profile from its handle on X, TikTok, Farcaster or Instagram. Returns null if there
    /// is no such profile. (GET /profileBySocialHandle)
    /// </summary>
    public async Task<ProfileBySocialHandle?> GetProfileBySocialHandleAsync(Platform platform, string handle, CancellationToken cancellationToken = default)
    {
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("platform", platform.Value));
        q.Add(new("handle", handle));
        var resp = await SendAsync<ProfileBySocialHandleResponse>("GET", "/profileBySocialHandle", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.ProfileBySocialHandle;
    }

    /// <summary>
    /// Coins a profile created. Filter by platform referrer to list only coins launched through a given
    /// app. Returns one page; EnumerateProfileCoinsAsync walks every page. (GET /profileCoins)
    /// </summary>
    public async Task<Zora20TokenConnection> GetProfileCoinsAsync(string identifier, ProfileCoinsParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("identifier", identifier));
        if (parameters.PageSize != null) q.Add(new("count", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        if (parameters.ChainIds != null) foreach (var v in parameters.ChainIds) q.Add(new("chainIds", Format(v)));
        if (parameters.PlatformReferrerAddress != null) foreach (var v in parameters.PlatformReferrerAddress) q.Add(new("platformReferrerAddress", Format(v)));
        var resp = await SendAsync<ProfileCoinsResponse>("GET", "/profileCoins", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Profile?.CreatedCoins ?? new Zora20TokenConnection();
    }

    /// <summary>
    /// Every Zora20Token across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<Zora20Token> EnumerateProfileCoinsAsync(string identifier, ProfileCoinsParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new ProfileCoinsParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetProfileCoinsAsync(identifier, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// A profile's linked social accounts (X, TikTok, Instagram, Farcaster) and follower counts.
    /// Returns null if there is no such profile. (GET /profileSocial)
    /// </summary>
    public async Task<Profile?> GetProfileSocialAsync(string identifier, CancellationToken cancellationToken = default)
    {
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("identifier", identifier));
        var resp = await SendAsync<ProfileSocialResponse>("GET", "/profileSocial", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Profile;
    }

    /// <summary>
    /// Search coins, profiles, content and trends by text. Returns one page; EnumerateSearchAsync walks
    /// every page. (GET /search)
    /// </summary>
    public async Task<SearchResultConnection> SearchAsync(string text, SearchParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("text", text));
        if (parameters.EntityType != null) q.Add(new("entityType", Format(parameters.EntityType)));
        if (parameters.PageSize != null) q.Add(new("first", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        var resp = await SendAsync<SearchResponse>("GET", "/search", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.GlobalSearch ?? new SearchResultConnection();
    }

    /// <summary>
    /// Every SearchResult across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<SearchResult> EnumerateSearchAsync(string text, SearchParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new SearchParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await SearchAsync(text, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// Symbol, decimals and current USD price of any ERC-20 on the chain: ZORA, USDC, WETH, or a coin.
    /// Returns null if there is no such coin. (GET /tokenInfo)
    /// </summary>
    public async Task<Erc20Token?> GetTokenInfoAsync(string address, TokenInfoParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("address", address));
        q.Add(new("chainId", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));
        var resp = await SendAsync<TokenInfoResponse>("GET", "/tokenInfo", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.Erc20Token;
    }

    /// <summary>
    /// Live streams with the most viewers right now. Returns one page; EnumerateTopLiveStreamsAsync
    /// walks every page. (GET /topLiveStreams)
    /// </summary>
    public async Task<LiveStreamConnection> GetTopLiveStreamsAsync(TopLiveStreamsParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        if (parameters.PageSize != null) q.Add(new("first", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        var resp = await SendAsync<TopLiveStreamsResponse>("GET", "/topLiveStreams", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.TopLiveStreams ?? new LiveStreamConnection();
    }

    /// <summary>
    /// Every LiveStream across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<LiveStream> EnumerateTopLiveStreamsAsync(TopLiveStreamsParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new TopLiveStreamsParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetTopLiveStreamsAsync(p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// The weekly trader leaderboard. Defaults to the current week. Returns one page;
    /// EnumerateTraderLeaderboardAsync walks every page. (GET /traderLeaderboard)
    /// </summary>
    public async Task<TraderLeaderboardEntryConnection> GetTraderLeaderboardAsync(TraderLeaderboardParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        if (parameters.Week != null) q.Add(new("week", Format(parameters.Week)));
        if (parameters.Year != null) q.Add(new("year", Format(parameters.Year)));
        if (parameters.PageSize != null) q.Add(new("first", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        var resp = await SendAsync<TraderLeaderboardResponse>("GET", "/traderLeaderboard", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.ExploreTraderLeaderboard ?? new TraderLeaderboardEntryConnection();
    }

    /// <summary>
    /// Every TraderLeaderboardEntry across all pages, fetched as the loop reaches them. Stop early with
    /// break. parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<TraderLeaderboardEntry> EnumerateTraderLeaderboardAsync(TraderLeaderboardParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new TraderLeaderboardParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetTraderLeaderboardAsync(p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// A trend coin by its ticker. Returns null if there is no such coin. (GET /trendCoin)
    /// </summary>
    public async Task<Zora20Token?> GetTrendCoinAsync(string ticker, TrendCoinParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("ticker", ticker));
        q.Add(new("chainId", (parameters.ChainId ?? BaseChainId).ToString(CultureInfo.InvariantCulture)));
        var resp = await SendAsync<TrendCoinResponse>("GET", "/trendCoin", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.TrendCoin;
    }

    /// <summary>
    /// Trend coins whose name matches, best match first. Returns one page; EnumerateTrendsByNameAsync
    /// walks every page. (GET /trendsByName)
    /// </summary>
    public async Task<Zora20TokenConnection> GetTrendsByNameAsync(string name, TrendsByNameParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("name", name));
        if (parameters.PageSize != null) q.Add(new("first", Format(parameters.PageSize)));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        var resp = await SendAsync<TrendsByNameResponse>("GET", "/trendsByName", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.TrendsByName ?? new Zora20TokenConnection();
    }

    /// <summary>
    /// Every Zora20Token across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<Zora20Token> EnumerateTrendsByNameAsync(string name, TrendsByNameParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new TrendsByNameParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetTrendsByNameAsync(name, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// Trades made by a wallet or profile, newest first. Returns one page;
    /// EnumerateWalletTradeActivityAsync walks every page. (GET /walletTradeActivity)
    /// </summary>
    public async Task<TradeActivityConnection> GetWalletTradeActivityAsync(string identifier, WalletTradeActivityParams? parameters = null, CancellationToken cancellationToken = default)
    {
        parameters ??= new();
        var q = new List<KeyValuePair<string, string>>();
        q.Add(new("identifier", identifier));
        if (parameters.After != null) q.Add(new("after", Format(parameters.After)));
        if (parameters.PageSize != null) q.Add(new("first", Format(parameters.PageSize)));
        var resp = await SendAsync<WalletTradeActivityResponse>("GET", "/walletTradeActivity", q, null, cancellationToken).ConfigureAwait(false);
        return resp?.WalletAddressTradeActivity ?? new TradeActivityConnection();
    }

    /// <summary>
    /// Every TradeActivity across all pages, fetched as the loop reaches them. Stop early with break.
    /// parameters.After picks the starting point.
    /// </summary>
    public async IAsyncEnumerable<TradeActivity> EnumerateWalletTradeActivityAsync(string identifier, WalletTradeActivityParams? parameters = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var p = parameters?.Copy() ?? new WalletTradeActivityParams();
        var seen = new HashSet<string>();
        while (true)
        {
            var page = await GetWalletTradeActivityAsync(identifier, p, cancellationToken).ConfigureAwait(false);
            foreach (var n in page.Nodes()) yield return n;
            var next = page.NextCursor();
            if (string.IsNullOrEmpty(next) || !seen.Add(next!)) yield break;
            p.After = next;
        }
    }

    /// <summary>
    /// Quote a trade. The result holds the transaction that executes it. Amounts are in the input
    /// token's smallest unit (wei for ETH). Set Referrer to earn the trade referral reward. Nothing is
    /// signed or sent: pass the returned call to your wallet. (POST /quote)
    /// </summary>
    public async Task<QuoteResponse> QuoteAsync(QuoteRequest request, CancellationToken cancellationToken = default)
    {
        var q = new List<KeyValuePair<string, string>>();
        var resp = await SendAsync<QuoteResponse>("POST", "/quote", q, request, cancellationToken).ConfigureAwait(false);
        return resp!;
    }

    /// <summary>
    /// Build the transaction that creates a content coin. The result also holds the coin's predicted
    /// address. Set PlatformReferrer to earn the platform referral share of the coin's trading fees for
    /// its whole life. Nothing is signed or sent. (POST /create/content)
    /// </summary>
    public async Task<CreateContentCoinResponse> CreateContentCoinAsync(CreateContentCoinRequest request, CancellationToken cancellationToken = default)
    {
        var q = new List<KeyValuePair<string, string>>();
        var resp = await SendAsync<CreateContentCoinResponse>("POST", "/create/content", q, request, cancellationToken).ConfigureAwait(false);
        return resp!;
    }
}
