// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Amount {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("currencyAddress")
    private String currencyAddress;
    @JsonProperty("amountRaw")
    private String amountRaw;
    @JsonProperty("amountDecimal")
    private Double amountDecimal;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Amount setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * The currency (WETH, ZORA, USDC or a creator coin). May be null: absent unless the endpoint
     * selected it.
     */
    public String getCurrencyAddress() {
        return currencyAddress;
    }

    /** Sets {@link #getCurrencyAddress()}. Returns this, for chaining. */
    public Amount setCurrencyAddress(String currencyAddress) {
        this.currencyAddress = currencyAddress;
        return this;
    }

    /**
     * Amount in the currency's smallest unit, as an integer string. May be null: absent unless the
     * endpoint selected it.
     */
    public String getAmountRaw() {
        return amountRaw;
    }

    /** Sets {@link #getAmountRaw()}. Returns this, for chaining. */
    public Amount setAmountRaw(String amountRaw) {
        this.amountRaw = amountRaw;
        return this;
    }

    /** Amount in whole units of the currency. May be null: absent unless the endpoint selected it. */
    public Double getAmountDecimal() {
        return amountDecimal;
    }

    /** Sets {@link #getAmountDecimal()}. Returns this, for chaining. */
    public Amount setAmountDecimal(Double amountDecimal) {
        this.amountDecimal = amountDecimal;
        return this;
    }

    @Override
    public String toString() {
        return "Amount" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
