// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** The raw response envelope. Client methods unwrap it. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class ApiKeyResponse {
    @JsonProperty("apiKey")
    private ApiKey apiKey;

    /** The API key. May be null: absent unless the endpoint selected it. */
    public ApiKey getApiKey() {
        return apiKey;
    }

    /** Sets {@link #getApiKey()}. Returns this, for chaining. */
    public ApiKeyResponse setApiKey(ApiKey apiKey) {
        this.apiKey = apiKey;
        return this;
    }

    @Override
    public String toString() {
        return "ApiKeyResponse" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
