// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Avatar {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("previewImage")
    private PreviewImage previewImage;
    @JsonProperty("small")
    private String small;
    @JsonProperty("medium")
    private String medium;
    @JsonProperty("blurhash")
    private String blurhash;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Avatar setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Resized preview of the image. May be null: absent unless the endpoint selected it. */
    public PreviewImage getPreviewImage() {
        return previewImage;
    }

    /** Sets {@link #getPreviewImage()}. Returns this, for chaining. */
    public Avatar setPreviewImage(PreviewImage previewImage) {
        this.previewImage = previewImage;
        return this;
    }

    /** Small avatar image URL. May be null: absent unless the endpoint selected it. */
    public String getSmall() {
        return small;
    }

    /** Sets {@link #getSmall()}. Returns this, for chaining. */
    public Avatar setSmall(String small) {
        this.small = small;
        return this;
    }

    /** Medium avatar image URL. May be null: absent unless the endpoint selected it. */
    public String getMedium() {
        return medium;
    }

    /** Sets {@link #getMedium()}. Returns this, for chaining. */
    public Avatar setMedium(String medium) {
        this.medium = medium;
        return this;
    }

    /**
     * BlurHash placeholder to show while the image loads. May be null: absent unless the endpoint
     * selected it.
     */
    public String getBlurhash() {
        return blurhash;
    }

    /** Sets {@link #getBlurhash()}. Returns this, for chaining. */
    public Avatar setBlurhash(String blurhash) {
        this.blurhash = blurhash;
        return this;
    }

    @Override
    public String toString() {
        return "Avatar" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
