// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A transaction to send from the user's wallet: target (to), calldata and ETH value. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Call {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("data")
    private String data;
    @JsonProperty("value")
    private String value;
    @JsonProperty("target")
    private String target;
    @JsonProperty("to")
    private String to;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Call setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Calldata (0x hex). May be null: absent unless the endpoint selected it. */
    public String getData() {
        return data;
    }

    /** Sets {@link #getData()}. Returns this, for chaining. */
    public Call setData(String data) {
        this.data = data;
        return this;
    }

    /**
     * ETH to send with the transaction, in wei, as an integer string. May be null: absent unless the
     * endpoint selected it.
     */
    public String getValue() {
        return value;
    }

    /** Sets {@link #getValue()}. Returns this, for chaining. */
    public Call setValue(String value) {
        this.value = value;
        return this;
    }

    /** Contract to send the transaction to. May be null: absent unless the endpoint selected it. */
    public String getTarget() {
        return target;
    }

    /** Sets {@link #getTarget()}. Returns this, for chaining. */
    public Call setTarget(String target) {
        this.target = target;
        return this;
    }

    /** Same as target. May be null: absent unless the endpoint selected it. */
    public String getTo() {
        return to;
    }

    /** Sets {@link #getTo()}. Returns this, for chaining. */
    public Call setTo(String to) {
        this.to = to;
        return this;
    }

    @Override
    public String toString() {
        return "Call" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
