// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * What a coin represents: a creator, a piece of content, or a trend. An extensible enum: values Zora
 * adds later are kept, not rejected.
 */
public final class CoinType {
    /** {@code CREATOR} */
    public static final CoinType CREATOR = new CoinType("CREATOR");
    /** {@code CONTENT} */
    public static final CoinType CONTENT = new CoinType("CONTENT");
    /** {@code TREND} */
    public static final CoinType TREND = new CoinType("TREND");

    /** Every value this SDK knows. */
    public static final List<CoinType> ALL = Collections.unmodifiableList(Arrays.asList(CREATOR, CONTENT, TREND));

    private final String value;

    private CoinType(String value) {
        this.value = Objects.requireNonNull(value);
    }

    /** Wraps any value, including ones this SDK doesn't know. */
    @JsonCreator
    public static CoinType of(String value) {
        for (CoinType known : ALL) if (known.value.equals(value)) return known;
        return new CoinType(value);
    }

    /** The value as the API spells it. */
    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof CoinType && (((CoinType) o).value).equals(value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
