// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A coin to fetch with Coins: its chain and contract address. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class CoinRefInput {
    @JsonProperty("chainId")
    private Long chainId;
    @JsonProperty("collectionAddress")
    private String collectionAddress;

    /** Chain ID (8453 = Base). Required. */
    public Long getChainId() {
        return chainId;
    }

    /** Sets {@link #getChainId()}. Returns this, for chaining. */
    public CoinRefInput setChainId(Long chainId) {
        this.chainId = chainId;
        return this;
    }

    /** Contract address of the coin. Required. */
    public String getCollectionAddress() {
        return collectionAddress;
    }

    /** Sets {@link #getCollectionAddress()}. Returns this, for chaining. */
    public CoinRefInput setCollectionAddress(String collectionAddress) {
        this.collectionAddress = collectionAddress;
        return this;
    }

    @Override
    public String toString() {
        return "CoinRefInput" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
