// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A comment in a coin's merged feed or on a live stream. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Comment {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("commentId")
    private String commentId;
    @JsonProperty("nonce")
    private String nonce;
    @JsonProperty("userAddress")
    private String userAddress;
    @JsonProperty("txHash")
    private String txHash;
    @JsonProperty("comment")
    private String comment;
    @JsonProperty("timestamp")
    private Long timestamp;
    @JsonProperty("userProfile")
    private UserProfile userProfile;
    @JsonProperty("replies")
    private Replies replies;
    @JsonProperty("contractAddress")
    private String contractAddress;
    @JsonProperty("text")
    private String text;
    @JsonProperty("commentedAt")
    private String commentedAt;
    @JsonProperty("replyToOnChainId")
    private String replyToOnChainId;
    @JsonProperty("replyToOffChainId")
    private String replyToOffChainId;
    @JsonProperty("sparkCount")
    private Long sparkCount;
    @JsonProperty("profile")
    private Profile profile;
    @JsonProperty("id")
    private String id;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Comment setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** ID of the comment. May be null: absent unless the endpoint selected it. */
    public String getCommentId() {
        return commentId;
    }

    /** Sets {@link #getCommentId()}. Returns this, for chaining. */
    public Comment setCommentId(String commentId) {
        this.commentId = commentId;
        return this;
    }

    /**
     * Nonce the comment was signed or posted with. May be null: absent unless the endpoint selected
     * it.
     */
    public String getNonce() {
        return nonce;
    }

    /** Sets {@link #getNonce()}. Returns this, for chaining. */
    public Comment setNonce(String nonce) {
        this.nonce = nonce;
        return this;
    }

    /** Wallet of the user who posted it. May be null: absent unless the endpoint selected it. */
    public String getUserAddress() {
        return userAddress;
    }

    /** Sets {@link #getUserAddress()}. Returns this, for chaining. */
    public Comment setUserAddress(String userAddress) {
        this.userAddress = userAddress;
        return this;
    }

    /**
     * Hash of the transaction that posted it onchain, if it was posted onchain. May be null: absent
     * unless the endpoint selected it.
     */
    public String getTxHash() {
        return txHash;
    }

    /** Sets {@link #getTxHash()}. Returns this, for chaining. */
    public Comment setTxHash(String txHash) {
        this.txHash = txHash;
        return this;
    }

    /** The comment text. May be null: absent unless the endpoint selected it. */
    public String getComment() {
        return comment;
    }

    /** Sets {@link #getComment()}. Returns this, for chaining. */
    public Comment setComment(String comment) {
        this.comment = comment;
        return this;
    }

    /** When it happened (Unix seconds). May be null: absent unless the endpoint selected it. */
    public Long getTimestamp() {
        return timestamp;
    }

    /** Sets {@link #getTimestamp()}. Returns this, for chaining. */
    public Comment setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /** Profile of the user who posted it. May be null: absent unless the endpoint selected it. */
    public UserProfile getUserProfile() {
        return userProfile;
    }

    /** Sets {@link #getUserProfile()}. Returns this, for chaining. */
    public Comment setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
        return this;
    }

    /** Replies to this comment. May be null: absent unless the endpoint selected it. */
    public Replies getReplies() {
        return replies;
    }

    /** Sets {@link #getReplies()}. Returns this, for chaining. */
    public Comment setReplies(Replies replies) {
        this.replies = replies;
        return this;
    }

    /** Contract of the coin the comment is on. May be null: absent unless the endpoint selected it. */
    public String getContractAddress() {
        return contractAddress;
    }

    /** Sets {@link #getContractAddress()}. Returns this, for chaining. */
    public Comment setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress;
        return this;
    }

    /** The comment text. May be null: absent unless the endpoint selected it. */
    public String getText() {
        return text;
    }

    /** Sets {@link #getText()}. Returns this, for chaining. */
    public Comment setText(String text) {
        this.text = text;
        return this;
    }

    /** Date with time (isoformat) May be null: absent unless the endpoint selected it. */
    public String getCommentedAt() {
        return commentedAt;
    }

    /** Sets {@link #getCommentedAt()}. Returns this, for chaining. */
    public Comment setCommentedAt(String commentedAt) {
        this.commentedAt = commentedAt;
        return this;
    }

    /**
     * Onchain ID of the comment this replies to, if any. May be null: absent unless the endpoint
     * selected it.
     */
    public String getReplyToOnChainId() {
        return replyToOnChainId;
    }

    /** Sets {@link #getReplyToOnChainId()}. Returns this, for chaining. */
    public Comment setReplyToOnChainId(String replyToOnChainId) {
        this.replyToOnChainId = replyToOnChainId;
        return this;
    }

    /**
     * Offchain ID of the comment this replies to, if any. May be null: absent unless the endpoint
     * selected it.
     */
    public String getReplyToOffChainId() {
        return replyToOffChainId;
    }

    /** Sets {@link #getReplyToOffChainId()}. Returns this, for chaining. */
    public Comment setReplyToOffChainId(String replyToOffChainId) {
        this.replyToOffChainId = replyToOffChainId;
        return this;
    }

    /** Sparks (Zora's likes) the comment received. May be null: absent unless the endpoint selected it. */
    public Long getSparkCount() {
        return sparkCount;
    }

    /** Sets {@link #getSparkCount()}. Returns this, for chaining. */
    public Comment setSparkCount(Long sparkCount) {
        this.sparkCount = sparkCount;
        return this;
    }

    /** The profile. May be null: absent unless the endpoint selected it. */
    public Profile getProfile() {
        return profile;
    }

    /** Sets {@link #getProfile()}. Returns this, for chaining. */
    public Comment setProfile(Profile profile) {
        this.profile = profile;
        return this;
    }

    /** Globally unique ID. May be null: absent unless the endpoint selected it. */
    public String getId() {
        return id;
    }

    /** Sets {@link #getId()}. Returns this, for chaining. */
    public Comment setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        return "Comment" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
