// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * What a new content coin trades against. An extensible enum: values Zora adds later are kept, not
 * rejected.
 */
public final class ContentCoinCurrency {
    /** {@code CREATOR_COIN} */
    public static final ContentCoinCurrency CREATOR_COIN = new ContentCoinCurrency("CREATOR_COIN");
    /** {@code ZORA} */
    public static final ContentCoinCurrency ZORA = new ContentCoinCurrency("ZORA");
    /** {@code ETH} */
    public static final ContentCoinCurrency ETH = new ContentCoinCurrency("ETH");
    /** {@code CREATOR_COIN_OR_ZORA} */
    public static final ContentCoinCurrency CREATOR_COIN_OR_ZORA = new ContentCoinCurrency("CREATOR_COIN_OR_ZORA");

    /** Every value this SDK knows. */
    public static final List<ContentCoinCurrency> ALL = Collections.unmodifiableList(Arrays.asList(CREATOR_COIN, ZORA, ETH, CREATOR_COIN_OR_ZORA));

    private final String value;

    private ContentCoinCurrency(String value) {
        this.value = Objects.requireNonNull(value);
    }

    /** Wraps any value, including ones this SDK doesn't know. */
    @JsonCreator
    public static ContentCoinCurrency of(String value) {
        for (ContentCoinCurrency known : ALL) if (known.value.equals(value)) return known;
        return new ContentCoinCurrency(value);
    }

    /** The value as the API spells it. */
    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof ContentCoinCurrency && (((ContentCoinCurrency) o).value).equals(value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
