// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** The profile of the creator behind a coin. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class CreatorProfile {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("id")
    private String id;
    @JsonProperty("handle")
    private String handle;
    @JsonProperty("platformBlocked")
    private Boolean platformBlocked;
    @JsonProperty("avatar")
    private Avatar avatar;
    @JsonProperty("socialAccounts")
    private SocialAccounts socialAccounts;
    @JsonProperty("creatorCoin")
    private Zora20Token creatorCoin;
    @JsonProperty("liveStream")
    private LiveStream liveStream;

    /**
     * The profile kind, e.g. GraphQLAccountProfile. May be null: absent unless the endpoint selected
     * it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public CreatorProfile setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Globally unique ID. May be null: absent unless the endpoint selected it. */
    public String getId() {
        return id;
    }

    /** Sets {@link #getId()}. Returns this, for chaining. */
    public CreatorProfile setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6). May be
     * null: absent unless the endpoint selected it.
     */
    public String getHandle() {
        return handle;
    }

    /** Sets {@link #getHandle()}. Returns this, for chaining. */
    public CreatorProfile setHandle(String handle) {
        this.handle = handle;
        return this;
    }

    /** True if Zora hides this from its own app. May be null: absent unless the endpoint selected it. */
    public Boolean getPlatformBlocked() {
        return platformBlocked;
    }

    /** Sets {@link #getPlatformBlocked()}. Returns this, for chaining. */
    public CreatorProfile setPlatformBlocked(Boolean platformBlocked) {
        this.platformBlocked = platformBlocked;
        return this;
    }

    /** Profile picture. May be null: absent unless the endpoint selected it. */
    public Avatar getAvatar() {
        return avatar;
    }

    /** Sets {@link #getAvatar()}. Returns this, for chaining. */
    public CreatorProfile setAvatar(Avatar avatar) {
        this.avatar = avatar;
        return this;
    }

    /**
     * Linked social accounts: X, TikTok, Instagram, Farcaster. May be null: absent unless the endpoint
     * selected it.
     */
    public SocialAccounts getSocialAccounts() {
        return socialAccounts;
    }

    /** Sets {@link #getSocialAccounts()}. Returns this, for chaining. */
    public CreatorProfile setSocialAccounts(SocialAccounts socialAccounts) {
        this.socialAccounts = socialAccounts;
        return this;
    }

    /** The creator's own creator coin. May be null: absent unless the endpoint selected it. */
    public Zora20Token getCreatorCoin() {
        return creatorCoin;
    }

    /** Sets {@link #getCreatorCoin()}. Returns this, for chaining. */
    public CreatorProfile setCreatorCoin(Zora20Token creatorCoin) {
        this.creatorCoin = creatorCoin;
        return this;
    }

    /** The creator's live stream, if any. May be null: absent unless the endpoint selected it. */
    public LiveStream getLiveStream() {
        return liveStream;
    }

    /** Sets {@link #getLiveStream()}. Returns this, for chaining. */
    public CreatorProfile setLiveStream(LiveStream liveStream) {
        this.liveStream = liveStream;
        return this;
    }

    @Override
    public String toString() {
        return "CreatorProfile" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
