// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A content coin to create. Metadata must point at EIP-7572 JSON (ipfs:// or https://). */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class CreateContentCoinRequest {
    @JsonProperty("creator")
    private String creator;
    @JsonProperty("name")
    private String name;
    @JsonProperty("symbol")
    private String symbol;
    @JsonProperty("metadata")
    private MetadataInput metadata;
    @JsonProperty("currency")
    private ContentCoinCurrency currency;
    @JsonProperty("chainId")
    private Long chainId;
    @JsonProperty("startingMarketCap")
    private StartingMarketCap startingMarketCap;
    @JsonProperty("platformReferrer")
    private String platformReferrer;
    @JsonProperty("additionalOwners")
    private List<String> additionalOwners;
    @JsonProperty("payoutRecipientOverride")
    private String payoutRecipientOverride;
    @JsonProperty("enableSmartWalletRouting")
    private Boolean enableSmartWalletRouting;

    /** Wallet creating the coin. Required. */
    public String getCreator() {
        return creator;
    }

    /** Sets {@link #getCreator()}. Returns this, for chaining. */
    public CreateContentCoinRequest setCreator(String creator) {
        this.creator = creator;
        return this;
    }

    /** Display name. Required. */
    public String getName() {
        return name;
    }

    /** Sets {@link #getName()}. Returns this, for chaining. */
    public CreateContentCoinRequest setName(String name) {
        this.name = name;
        return this;
    }

    /** Ticker symbol. Required. */
    public String getSymbol() {
        return symbol;
    }

    /** Sets {@link #getSymbol()}. Returns this, for chaining. */
    public CreateContentCoinRequest setSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /** Where the coin's EIP-7572 metadata lives. Required. */
    public MetadataInput getMetadata() {
        return metadata;
    }

    /** Sets {@link #getMetadata()}. Returns this, for chaining. */
    public CreateContentCoinRequest setMetadata(MetadataInput metadata) {
        this.metadata = metadata;
        return this;
    }

    /** The currency. Required. */
    public ContentCoinCurrency getCurrency() {
        return currency;
    }

    /** Sets {@link #getCurrency()}. Returns this, for chaining. */
    public CreateContentCoinRequest setCurrency(ContentCoinCurrency currency) {
        this.currency = currency;
        return this;
    }

    /** Chain ID (8453 = Base). Optional. */
    public Long getChainId() {
        return chainId;
    }

    /** Sets {@link #getChainId()}. Returns this, for chaining. */
    public CreateContentCoinRequest setChainId(Long chainId) {
        this.chainId = chainId;
        return this;
    }

    /** Starting market cap tier. Optional. */
    public StartingMarketCap getStartingMarketCap() {
        return startingMarketCap;
    }

    /** Sets {@link #getStartingMarketCap()}. Returns this, for chaining. */
    public CreateContentCoinRequest setStartingMarketCap(StartingMarketCap startingMarketCap) {
        this.startingMarketCap = startingMarketCap;
        return this;
    }

    /**
     * Your app's address: it earns the platform referral share of this coin's trading fees for good.
     * Optional.
     */
    public String getPlatformReferrer() {
        return platformReferrer;
    }

    /** Sets {@link #getPlatformReferrer()}. Returns this, for chaining. */
    public CreateContentCoinRequest setPlatformReferrer(String platformReferrer) {
        this.platformReferrer = platformReferrer;
        return this;
    }

    /** More wallets allowed to manage the coin. Optional. */
    public List<String> getAdditionalOwners() {
        return additionalOwners;
    }

    /** Sets {@link #getAdditionalOwners()}. Returns this, for chaining. */
    public CreateContentCoinRequest setAdditionalOwners(List<String> additionalOwners) {
        this.additionalOwners = additionalOwners;
        return this;
    }

    /** Wallet to receive the creator's fee share instead of the creator. Optional. */
    public String getPayoutRecipientOverride() {
        return payoutRecipientOverride;
    }

    /** Sets {@link #getPayoutRecipientOverride()}. Returns this, for chaining. */
    public CreateContentCoinRequest setPayoutRecipientOverride(String payoutRecipientOverride) {
        this.payoutRecipientOverride = payoutRecipientOverride;
        return this;
    }

    /** Optional flag to enable smart wallet routing. Defaults to false if omitted. Optional. */
    public Boolean getEnableSmartWalletRouting() {
        return enableSmartWalletRouting;
    }

    /** Sets {@link #getEnableSmartWalletRouting()}. Returns this, for chaining. */
    public CreateContentCoinRequest setEnableSmartWalletRouting(Boolean enableSmartWalletRouting) {
        this.enableSmartWalletRouting = enableSmartWalletRouting;
        return this;
    }

    @Override
    public String toString() {
        return "CreateContentCoinRequest" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
