// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** The calls that create a content coin, and the address it will have. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class CreateContentCoinResponse {
    @JsonProperty("calls")
    private List<Call> calls;
    @JsonProperty("predictedCoinAddress")
    private String predictedCoinAddress;
    @JsonProperty("backingCurrency")
    private String backingCurrency;
    @JsonProperty("usedSmartWalletRouting")
    private Boolean usedSmartWalletRouting;

    /**
     * Transactions to send from the creator's wallet, in order. May be null: absent unless the
     * endpoint selected it.
     */
    public List<Call> getCalls() {
        return calls;
    }

    /** Sets {@link #getCalls()}. Returns this, for chaining. */
    public CreateContentCoinResponse setCalls(List<Call> calls) {
        this.calls = calls;
        return this;
    }

    /**
     * The address the coin will have once created. May be null: absent unless the endpoint selected
     * it.
     */
    public String getPredictedCoinAddress() {
        return predictedCoinAddress;
    }

    /** Sets {@link #getPredictedCoinAddress()}. Returns this, for chaining. */
    public CreateContentCoinResponse setPredictedCoinAddress(String predictedCoinAddress) {
        this.predictedCoinAddress = predictedCoinAddress;
        return this;
    }

    /**
     * The result. Client methods return this field directly. May be null: absent unless the endpoint
     * selected it.
     */
    public String getBackingCurrency() {
        return backingCurrency;
    }

    /** Sets {@link #getBackingCurrency()}. Returns this, for chaining. */
    public CreateContentCoinResponse setBackingCurrency(String backingCurrency) {
        this.backingCurrency = backingCurrency;
        return this;
    }

    /**
     * The result. Client methods return this field directly. May be null: absent unless the endpoint
     * selected it.
     */
    public Boolean getUsedSmartWalletRouting() {
        return usedSmartWalletRouting;
    }

    /** Sets {@link #getUsedSmartWalletRouting()}. Returns this, for chaining. */
    public CreateContentCoinResponse setUsedSmartWalletRouting(Boolean usedSmartWalletRouting) {
        this.usedSmartWalletRouting = usedSmartWalletRouting;
        return this;
    }

    @Override
    public String toString() {
        return "CreateContentCoinResponse" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
