// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** Who the upload token is for. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class CreateUploadJwtRequest {
    @JsonProperty("creatorAddress")
    private String creatorAddress;

    /** Wallet the upload token is for. Required. */
    public String getCreatorAddress() {
        return creatorAddress;
    }

    /** Sets {@link #getCreatorAddress()}. Returns this, for chaining. */
    public CreateUploadJwtRequest setCreatorAddress(String creatorAddress) {
        this.creatorAddress = creatorAddress;
        return this;
    }

    @Override
    public String toString() {
        return "CreateUploadJwtRequest" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
