// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** What a coin's creator has earned from trading fees, in one currency. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class CreatorEarning {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("amount")
    private Amount amount;
    @JsonProperty("amountUsd")
    private String amountUsd;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public CreatorEarning setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** The amount. May be null: absent unless the endpoint selected it. */
    public Amount getAmount() {
        return amount;
    }

    /** Sets {@link #getAmount()}. Returns this, for chaining. */
    public CreatorEarning setAmount(Amount amount) {
        this.amount = amount;
        return this;
    }

    /** The amount in USD. May be null: absent unless the endpoint selected it. */
    public String getAmountUsd() {
        return amountUsd;
    }

    /** Sets {@link #getAmountUsd()}. Returns this, for chaining. */
    public CreatorEarning setAmountUsd(String amountUsd) {
        this.amountUsd = amountUsd;
        return this;
    }

    @Override
    public String toString() {
        return "CreatorEarning" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
