// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class CurrencyAmountWithPrice {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("priceUsdc")
    private String priceUsdc;
    @JsonProperty("currencyAmount")
    private Amount currencyAmount;
    @JsonProperty("amountUsd")
    private String amountUsd;
    @JsonProperty("priceDelta24h")
    private String priceDelta24h;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public CurrencyAmountWithPrice setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * USD price of one unit of the currency at the time of the swap. May be null: absent unless the
     * endpoint selected it.
     */
    public String getPriceUsdc() {
        return priceUsdc;
    }

    /** Sets {@link #getPriceUsdc()}. Returns this, for chaining. */
    public CurrencyAmountWithPrice setPriceUsdc(String priceUsdc) {
        this.priceUsdc = priceUsdc;
        return this;
    }

    /**
     * Amount paid or received, in the pool's currency. May be null: absent unless the endpoint
     * selected it.
     */
    public Amount getCurrencyAmount() {
        return currencyAmount;
    }

    /** Sets {@link #getCurrencyAmount()}. Returns this, for chaining. */
    public CurrencyAmountWithPrice setCurrencyAmount(Amount currencyAmount) {
        this.currencyAmount = currencyAmount;
        return this;
    }

    /** The amount in USD. May be null: absent unless the endpoint selected it. */
    public String getAmountUsd() {
        return amountUsd;
    }

    /** Sets {@link #getAmountUsd()}. Returns this, for chaining. */
    public CurrencyAmountWithPrice setAmountUsd(String amountUsd) {
        this.amountUsd = amountUsd;
        return this;
    }

    /**
     * Change in the currency's price over the last 24 hours. May be null: absent unless the endpoint
     * selected it.
     */
    public String getPriceDelta24h() {
        return priceDelta24h;
    }

    /** Sets {@link #getPriceDelta24h()}. Returns this, for chaining. */
    public CurrencyAmountWithPrice setPriceDelta24h(String priceDelta24h) {
        this.priceDelta24h = priceDelta24h;
        return this;
    }

    @Override
    public String toString() {
        return "CurrencyAmountWithPrice" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
