// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Currency {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("priceUsd")
    private String priceUsd;
    @JsonProperty("decimals")
    private Long decimals;
    @JsonProperty("name")
    private String name;
    @JsonProperty("symbol")
    private String symbol;
    @JsonProperty("icon")
    private String icon;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Currency setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * Current USD price of one whole token, as a decimal string. May be null: absent unless the
     * endpoint selected it.
     */
    public String getPriceUsd() {
        return priceUsd;
    }

    /** Sets {@link #getPriceUsd()}. Returns this, for chaining. */
    public Currency setPriceUsd(String priceUsd) {
        this.priceUsd = priceUsd;
        return this;
    }

    /** Token decimals (18 for most, 6 for USDC). May be null: absent unless the endpoint selected it. */
    public Long getDecimals() {
        return decimals;
    }

    /** Sets {@link #getDecimals()}. Returns this, for chaining. */
    public Currency setDecimals(Long decimals) {
        this.decimals = decimals;
        return this;
    }

    /** Display name. May be null: absent unless the endpoint selected it. */
    public String getName() {
        return name;
    }

    /** Sets {@link #getName()}. Returns this, for chaining. */
    public Currency setName(String name) {
        this.name = name;
        return this;
    }

    /** Ticker symbol. May be null: absent unless the endpoint selected it. */
    public String getSymbol() {
        return symbol;
    }

    /** Sets {@link #getSymbol()}. Returns this, for chaining. */
    public Currency setSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /** Token icon URL. May be null: absent unless the endpoint selected it. */
    public String getIcon() {
        return icon;
    }

    /** Sets {@link #getIcon()}. Returns this, for chaining. */
    public Currency setIcon(String icon) {
        this.icon = icon;
        return this;
    }

    @Override
    public String toString() {
        return "Currency" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
