// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Details {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("token")
    private String token;
    @JsonProperty("amount")
    private String amount;
    @JsonProperty("expiration")
    private Double expiration;
    @JsonProperty("nonce")
    private Double nonce;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Details setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Token address. May be null: absent unless the endpoint selected it. */
    public String getToken() {
        return token;
    }

    /** Sets {@link #getToken()}. Returns this, for chaining. */
    public Details setToken(String token) {
        this.token = token;
        return this;
    }

    /** The amount. May be null: absent unless the endpoint selected it. */
    public String getAmount() {
        return amount;
    }

    /** Sets {@link #getAmount()}. Returns this, for chaining. */
    public Details setAmount(String amount) {
        this.amount = amount;
        return this;
    }

    /** When the allowance expires (Unix seconds). May be null: absent unless the endpoint selected it. */
    public Double getExpiration() {
        return expiration;
    }

    /** Sets {@link #getExpiration()}. Returns this, for chaining. */
    public Details setExpiration(Double expiration) {
        this.expiration = expiration;
        return this;
    }

    /**
     * Nonce the comment was signed or posted with. May be null: absent unless the endpoint selected
     * it.
     */
    public Double getNonce() {
        return nonce;
    }

    /** Sets {@link #getNonce()}. Returns this, for chaining. */
    public Details setNonce(Double nonce) {
        this.nonce = nonce;
        return this;
    }

    @Override
    public String toString() {
        return "Details" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
