// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * What kind of thing a search result is. An extensible enum: values Zora adds later are kept, not
 * rejected.
 */
public final class EntityType {
    /** {@code USER_PROFILE} */
    public static final EntityType USER_PROFILE = new EntityType("USER_PROFILE");
    /** {@code CONTENT} */
    public static final EntityType CONTENT = new EntityType("CONTENT");
    /** {@code TREND} */
    public static final EntityType TREND = new EntityType("TREND");
    /** {@code COIN} */
    public static final EntityType COIN = new EntityType("COIN");

    /** Every value this SDK knows. */
    public static final List<EntityType> ALL = Collections.unmodifiableList(Arrays.asList(USER_PROFILE, CONTENT, TREND, COIN));

    private final String value;

    private EntityType(String value) {
        this.value = Objects.requireNonNull(value);
    }

    /** Wraps any value, including ones this SDK doesn't know. */
    @JsonCreator
    public static EntityType of(String value) {
        for (EntityType known : ALL) if (known.value.equals(value)) return known;
        return new EntityType(value);
    }

    /** The value as the API spells it. */
    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof EntityType && (((EntityType) o).value).equals(value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
