// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** ERC-20 metadata and price for any token. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Erc20Token {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("currency")
    private Currency currency;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Erc20Token setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** The token's symbol, decimals and USD price. May be null: absent unless the endpoint selected it. */
    public Currency getCurrency() {
        return currency;
    }

    /** Sets {@link #getCurrency()}. Returns this, for chaining. */
    public Erc20Token setCurrency(Currency currency) {
        this.currency = currency;
        return this;
    }

    @Override
    public String toString() {
        return "Erc20Token" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
