// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Whether a social account was linked or unlinked. An extensible enum: values Zora adds later are
 * kept, not rejected.
 */
public final class EventType {
    /** {@code LINK} */
    public static final EventType LINK = new EventType("LINK");
    /** {@code UNLINK} */
    public static final EventType UNLINK = new EventType("UNLINK");

    /** Every value this SDK knows. */
    public static final List<EventType> ALL = Collections.unmodifiableList(Arrays.asList(LINK, UNLINK));

    private final String value;

    private EventType(String value) {
        this.value = Objects.requireNonNull(value);
    }

    /** Wraps any value, including ones this SDK doesn't know. */
    @JsonCreator
    public static EventType of(String value) {
        for (EventType known : ALL) if (known.value.equals(value)) return known;
        return new EventType(value);
    }

    /** The value as the API spells it. */
    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof EventType && (((EventType) o).value).equals(value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
