// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class ExternalWallet {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("ensName")
    private String ensName;
    @JsonProperty("walletAddress")
    private String walletAddress;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public ExternalWallet setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** ENS name of the wallet, if it has one. May be null: absent unless the endpoint selected it. */
    public String getEnsName() {
        return ensName;
    }

    /** Sets {@link #getEnsName()}. Returns this, for chaining. */
    public ExternalWallet setEnsName(String ensName) {
        this.ensName = ensName;
        return this;
    }

    /** Wallet address. May be null: absent unless the endpoint selected it. */
    public String getWalletAddress() {
        return walletAddress;
    }

    /** Sets {@link #getWalletAddress()}. Returns this, for chaining. */
    public ExternalWallet setWalletAddress(String walletAddress) {
        this.walletAddress = walletAddress;
        return this;
    }

    @Override
    public String toString() {
        return "ExternalWallet" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
