// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A creator featured on the weekly leaderboard. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class FeaturedCreator {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("id")
    private String id;
    @JsonProperty("handle")
    private String handle;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public FeaturedCreator setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Globally unique ID. May be null: absent unless the endpoint selected it. */
    public String getId() {
        return id;
    }

    /** Sets {@link #getId()}. Returns this, for chaining. */
    public FeaturedCreator setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6). May be
     * null: absent unless the endpoint selected it.
     */
    public String getHandle() {
        return handle;
    }

    /** Sets {@link #getHandle()}. Returns this, for chaining. */
    public FeaturedCreator setHandle(String handle) {
        this.handle = handle;
        return this;
    }

    @Override
    public String toString() {
        return "FeaturedCreator" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
