// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Followers {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("count")
    private Long count;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Followers setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * Total number of items, where the API reports it. May be null: absent unless the endpoint
     * selected it.
     */
    public Long getCount() {
        return count;
    }

    /** Sets {@link #getCount()}. Returns this, for chaining. */
    public Followers setCount(Long count) {
        this.count = count;
        return this;
    }

    @Override
    public String toString() {
        return "Followers" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
