// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Instagram {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("username")
    private String username;
    @JsonProperty("displayName")
    private String displayName;
    @JsonProperty("followerCount")
    private Long followerCount;
    @JsonProperty("id")
    private String id;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Instagram setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Username on that network. May be null: absent unless the endpoint selected it. */
    public String getUsername() {
        return username;
    }

    /** Sets {@link #getUsername()}. Returns this, for chaining. */
    public Instagram setUsername(String username) {
        this.username = username;
        return this;
    }

    /** Display name on that network. May be null: absent unless the endpoint selected it. */
    public String getDisplayName() {
        return displayName;
    }

    /** Sets {@link #getDisplayName()}. Returns this, for chaining. */
    public Instagram setDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /** Followers on that network. May be null: absent unless the endpoint selected it. */
    public Long getFollowerCount() {
        return followerCount;
    }

    /** Sets {@link #getFollowerCount()}. Returns this, for chaining. */
    public Instagram setFollowerCount(Long followerCount) {
        this.followerCount = followerCount;
        return this;
    }

    /** Globally unique ID. May be null: absent unless the endpoint selected it. */
    public String getId() {
        return id;
    }

    /** Sets {@link #getId()}. Returns this, for chaining. */
    public Instagram setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public String toString() {
        return "Instagram" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
