// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** Wraps one LinkedWallet in a page of results. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class LinkedWalletEdge {
    @JsonProperty("node")
    private PublicWallet node;

    /** The item. May be null: absent unless the endpoint selected it. */
    public PublicWallet getNode() {
        return node;
    }

    /** Sets {@link #getNode()}. Returns this, for chaining. */
    public LinkedWalletEdge setNode(PublicWallet node) {
        this.node = node;
        return this;
    }

    @Override
    public String toString() {
        return "LinkedWalletEdge" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
