// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A creator's live stream. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class LiveStream {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("comments")
    private CommentConnection comments;
    @JsonProperty("id")
    private String id;
    @JsonProperty("isOnline")
    private Boolean isOnline;
    @JsonProperty("isActive")
    private Boolean isActive;
    @JsonProperty("concurrentViewers")
    private Long concurrentViewers;
    @JsonProperty("staticThumbnailUrl")
    private String staticThumbnailUrl;
    @JsonProperty("animatedThumbnailUrl")
    private String animatedThumbnailUrl;
    @JsonProperty("creatorProfile")
    private CreatorProfile creatorProfile;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public LiveStream setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Comments. May be null: absent unless the endpoint selected it. */
    public CommentConnection getComments() {
        return comments;
    }

    /** Sets {@link #getComments()}. Returns this, for chaining. */
    public LiveStream setComments(CommentConnection comments) {
        this.comments = comments;
        return this;
    }

    /** Globally unique ID. May be null: absent unless the endpoint selected it. */
    public String getId() {
        return id;
    }

    /** Sets {@link #getId()}. Returns this, for chaining. */
    public LiveStream setId(String id) {
        this.id = id;
        return this;
    }

    /** Whether the stream is live right now. May be null: absent unless the endpoint selected it. */
    public Boolean getIsOnline() {
        return isOnline;
    }

    /** Sets {@link #getIsOnline()}. Returns this, for chaining. */
    public LiveStream setIsOnline(Boolean isOnline) {
        this.isOnline = isOnline;
        return this;
    }

    /** Whether the key is active. May be null: absent unless the endpoint selected it. */
    public Boolean getIsActive() {
        return isActive;
    }

    /** Sets {@link #getIsActive()}. Returns this, for chaining. */
    public LiveStream setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    /** People watching right now. May be null: absent unless the endpoint selected it. */
    public Long getConcurrentViewers() {
        return concurrentViewers;
    }

    /** Sets {@link #getConcurrentViewers()}. Returns this, for chaining. */
    public LiveStream setConcurrentViewers(Long concurrentViewers) {
        this.concurrentViewers = concurrentViewers;
        return this;
    }

    /** Still thumbnail image URL. May be null: absent unless the endpoint selected it. */
    public String getStaticThumbnailUrl() {
        return staticThumbnailUrl;
    }

    /** Sets {@link #getStaticThumbnailUrl()}. Returns this, for chaining. */
    public LiveStream setStaticThumbnailUrl(String staticThumbnailUrl) {
        this.staticThumbnailUrl = staticThumbnailUrl;
        return this;
    }

    /** Animated thumbnail URL. May be null: absent unless the endpoint selected it. */
    public String getAnimatedThumbnailUrl() {
        return animatedThumbnailUrl;
    }

    /** Sets {@link #getAnimatedThumbnailUrl()}. Returns this, for chaining. */
    public LiveStream setAnimatedThumbnailUrl(String animatedThumbnailUrl) {
        this.animatedThumbnailUrl = animatedThumbnailUrl;
        return this;
    }

    /** Profile of the creator. May be null: absent unless the endpoint selected it. */
    public CreatorProfile getCreatorProfile() {
        return creatorProfile;
    }

    /** Sets {@link #getCreatorProfile()}. Returns this, for chaining. */
    public LiveStream setCreatorProfile(CreatorProfile creatorProfile) {
        this.creatorProfile = creatorProfile;
        return this;
    }

    @Override
    public String toString() {
        return "LiveStream" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
