// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** The image, video or other media attached to a coin. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class MediaContent {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("mimeType")
    private String mimeType;
    @JsonProperty("originalUri")
    private String originalUri;
    @JsonProperty("previewImage")
    private PreviewImage previewImage;
    @JsonProperty("videoPreviewUrl")
    private String videoPreviewUrl;
    @JsonProperty("videoHlsUrl")
    private String videoHlsUrl;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public MediaContent setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** MIME type of the original media. May be null: absent unless the endpoint selected it. */
    public String getMimeType() {
        return mimeType;
    }

    /** Sets {@link #getMimeType()}. Returns this, for chaining. */
    public MediaContent setMimeType(String mimeType) {
        this.mimeType = mimeType;
        return this;
    }

    /** The original media file (often ipfs://). May be null: absent unless the endpoint selected it. */
    public String getOriginalUri() {
        return originalUri;
    }

    /** Sets {@link #getOriginalUri()}. Returns this, for chaining. */
    public MediaContent setOriginalUri(String originalUri) {
        this.originalUri = originalUri;
        return this;
    }

    /** Resized previews served over https. May be null: absent unless the endpoint selected it. */
    public PreviewImage getPreviewImage() {
        return previewImage;
    }

    /** Sets {@link #getPreviewImage()}. Returns this, for chaining. */
    public MediaContent setPreviewImage(PreviewImage previewImage) {
        this.previewImage = previewImage;
        return this;
    }

    /** Short video preview URL. May be null: absent unless the endpoint selected it. */
    public String getVideoPreviewUrl() {
        return videoPreviewUrl;
    }

    /** Sets {@link #getVideoPreviewUrl()}. Returns this, for chaining. */
    public MediaContent setVideoPreviewUrl(String videoPreviewUrl) {
        this.videoPreviewUrl = videoPreviewUrl;
        return this;
    }

    /** HLS stream URL of the video. May be null: absent unless the endpoint selected it. */
    public String getVideoHlsUrl() {
        return videoHlsUrl;
    }

    /** Sets {@link #getVideoHlsUrl()}. Returns this, for chaining. */
    public MediaContent setVideoHlsUrl(String videoHlsUrl) {
        this.videoHlsUrl = videoHlsUrl;
        return this;
    }

    @Override
    public String toString() {
        return "MediaContent" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
