// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Permit {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("sigDeadline")
    private String sigDeadline;
    @JsonProperty("spender")
    private String spender;
    @JsonProperty("details")
    private Details details;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Permit setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * When the signature stops being valid (Unix seconds). May be null: absent unless the endpoint
     * selected it.
     */
    public String getSigDeadline() {
        return sigDeadline;
    }

    /** Sets {@link #getSigDeadline()}. Returns this, for chaining. */
    public Permit setSigDeadline(String sigDeadline) {
        this.sigDeadline = sigDeadline;
        return this;
    }

    /** Contract allowed to spend the tokens. May be null: absent unless the endpoint selected it. */
    public String getSpender() {
        return spender;
    }

    /** Sets {@link #getSpender()}. Returns this, for chaining. */
    public Permit setSpender(String spender) {
        this.spender = spender;
        return this;
    }

    /**
     * What the permit allows: token, amount, expiry, nonce. May be null: absent unless the endpoint
     * selected it.
     */
    public Details getDetails() {
        return details;
    }

    /** Sets {@link #getDetails()}. Returns this, for chaining. */
    public Permit setDetails(Details details) {
        this.details = details;
        return this;
    }

    @Override
    public String toString() {
        return "Permit" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
