// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * A social network Zora profiles link to. An extensible enum: values Zora adds later are kept, not
 * rejected.
 */
public final class Platform {
    /** {@code TWITTER} */
    public static final Platform TWITTER = new Platform("TWITTER");
    /** {@code TIKTOK} */
    public static final Platform TIKTOK = new Platform("TIKTOK");
    /** {@code FARCASTER} */
    public static final Platform FARCASTER = new Platform("FARCASTER");
    /** {@code INSTAGRAM} */
    public static final Platform INSTAGRAM = new Platform("INSTAGRAM");

    /** Every value this SDK knows. */
    public static final List<Platform> ALL = Collections.unmodifiableList(Arrays.asList(TWITTER, TIKTOK, FARCASTER, INSTAGRAM));

    private final String value;

    private Platform(String value) {
        this.value = Objects.requireNonNull(value);
    }

    /** Wraps any value, including ones this SDK doesn't know. */
    @JsonCreator
    public static Platform of(String value) {
        for (Platform known : ALL) if (known.value.equals(value)) return known;
        return new Platform(value);
    }

    /** The value as the API spells it. */
    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof Platform && (((Platform) o).value).equals(value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
