// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** The currency a coin's pool trades against (ZORA, ETH, USDC or a creator coin). */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class PoolCurrencyToken {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("address")
    private String address;
    @JsonProperty("name")
    private String name;
    @JsonProperty("decimals")
    private Long decimals;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public PoolCurrencyToken setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Contract address (lowercase 0x hex). May be null: absent unless the endpoint selected it. */
    public String getAddress() {
        return address;
    }

    /** Sets {@link #getAddress()}. Returns this, for chaining. */
    public PoolCurrencyToken setAddress(String address) {
        this.address = address;
        return this;
    }

    /** Display name. May be null: absent unless the endpoint selected it. */
    public String getName() {
        return name;
    }

    /** Sets {@link #getName()}. Returns this, for chaining. */
    public PoolCurrencyToken setName(String name) {
        this.name = name;
        return this;
    }

    /** Token decimals (18 for most, 6 for USDC). May be null: absent unless the endpoint selected it. */
    public Long getDecimals() {
        return decimals;
    }

    /** Sets {@link #getDecimals()}. Returns this, for chaining. */
    public PoolCurrencyToken setDecimals(Long decimals) {
        this.decimals = decimals;
        return this;
    }

    @Override
    public String toString() {
        return "PoolCurrencyToken" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
