// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** The price of a coin at a moment in time. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class PricePoint {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("timestamp")
    private String timestamp;
    @JsonProperty("closePrice")
    private String closePrice;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public PricePoint setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Start of the interval (ISO 8601, UTC). May be null: absent unless the endpoint selected it. */
    public String getTimestamp() {
        return timestamp;
    }

    /** Sets {@link #getTimestamp()}. Returns this, for chaining. */
    public PricePoint setTimestamp(String timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /** Price at the end of the interval, in USD. May be null: absent unless the endpoint selected it. */
    public String getClosePrice() {
        return closePrice;
    }

    /** Sets {@link #getClosePrice()}. Returns this, for chaining. */
    public PricePoint setClosePrice(String closePrice) {
        this.closePrice = closePrice;
        return this;
    }

    @Override
    public String toString() {
        return "PricePoint" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
