// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** The raw response envelope. Client methods unwrap it. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class ProfileResponse {
    @JsonProperty("profile")
    private Profile profile;

    /** The profile. May be null: absent unless the endpoint selected it. */
    public Profile getProfile() {
        return profile;
    }

    /** Sets {@link #getProfile()}. Returns this, for chaining. */
    public ProfileResponse setProfile(Profile profile) {
        this.profile = profile;
        return this;
    }

    @Override
    public String toString() {
        return "ProfileResponse" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
