// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/**
 * A Zora profile: handle, avatar, linked wallets, creator coin, and (depending on the call) the coins
 * it created or holds.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Profile {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("id")
    private String id;
    @JsonProperty("handle")
    private String handle;
    @JsonProperty("avatar")
    private Avatar avatar;
    @JsonProperty("platformBlocked")
    private Boolean platformBlocked;
    @JsonProperty("socialAccounts")
    private SocialAccounts socialAccounts;
    @JsonProperty("creatorCoin")
    private Zora20Token creatorCoin;
    @JsonProperty("username")
    private String username;
    @JsonProperty("createdAt")
    private String createdAt;
    @JsonProperty("displayName")
    private String displayName;
    @JsonProperty("bio")
    private String bio;
    @JsonProperty("website")
    private String website;
    @JsonProperty("publicWallet")
    private PublicWallet publicWallet;
    @JsonProperty("linkedWallets")
    private LinkedWallets linkedWallets;
    @JsonProperty("coinBalances")
    private CoinBalanceConnection coinBalances;
    @JsonProperty("createdCoins")
    private Zora20TokenConnection createdCoins;
    @JsonProperty("usernameChangesCount")
    private Long usernameChangesCount;
    @JsonProperty("externalWallet")
    private ExternalWallet externalWallet;
    @JsonProperty("followers")
    private Followers followers;
    @JsonProperty("following")
    private Followers following;
    @JsonProperty("socialAccountLinkedEvents")
    private SocialAccountLinkedEvents socialAccountLinkedEvents;

    /**
     * The profile kind, e.g. GraphQLAccountProfile. May be null: absent unless the endpoint selected
     * it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Profile setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Globally unique ID. May be null: absent unless the endpoint selected it. */
    public String getId() {
        return id;
    }

    /** Sets {@link #getId()}. Returns this, for chaining. */
    public Profile setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Zora handle, without @. Wallet-only profiles get a shortened address (0x06d7...b1c6). May be
     * null: absent unless the endpoint selected it.
     */
    public String getHandle() {
        return handle;
    }

    /** Sets {@link #getHandle()}. Returns this, for chaining. */
    public Profile setHandle(String handle) {
        this.handle = handle;
        return this;
    }

    /** Profile picture. May be null: absent unless the endpoint selected it. */
    public Avatar getAvatar() {
        return avatar;
    }

    /** Sets {@link #getAvatar()}. Returns this, for chaining. */
    public Profile setAvatar(Avatar avatar) {
        this.avatar = avatar;
        return this;
    }

    /** True if Zora hides this from its own app. May be null: absent unless the endpoint selected it. */
    public Boolean getPlatformBlocked() {
        return platformBlocked;
    }

    /** Sets {@link #getPlatformBlocked()}. Returns this, for chaining. */
    public Profile setPlatformBlocked(Boolean platformBlocked) {
        this.platformBlocked = platformBlocked;
        return this;
    }

    /**
     * Linked social accounts: X, TikTok, Instagram, Farcaster. May be null: absent unless the endpoint
     * selected it.
     */
    public SocialAccounts getSocialAccounts() {
        return socialAccounts;
    }

    /** Sets {@link #getSocialAccounts()}. Returns this, for chaining. */
    public Profile setSocialAccounts(SocialAccounts socialAccounts) {
        this.socialAccounts = socialAccounts;
        return this;
    }

    /** The creator's own creator coin. May be null: absent unless the endpoint selected it. */
    public Zora20Token getCreatorCoin() {
        return creatorCoin;
    }

    /** Sets {@link #getCreatorCoin()}. Returns this, for chaining. */
    public Profile setCreatorCoin(Zora20Token creatorCoin) {
        this.creatorCoin = creatorCoin;
        return this;
    }

    /** Username on that network. May be null: absent unless the endpoint selected it. */
    public String getUsername() {
        return username;
    }

    /** Sets {@link #getUsername()}. Returns this, for chaining. */
    public Profile setUsername(String username) {
        this.username = username;
        return this;
    }

    /** When it was created (ISO 8601, UTC). May be null: absent unless the endpoint selected it. */
    public String getCreatedAt() {
        return createdAt;
    }

    /** Sets {@link #getCreatedAt()}. Returns this, for chaining. */
    public Profile setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /** Display name on that network. May be null: absent unless the endpoint selected it. */
    public String getDisplayName() {
        return displayName;
    }

    /** Sets {@link #getDisplayName()}. Returns this, for chaining. */
    public Profile setDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /** Profile bio. May be null: absent unless the endpoint selected it. */
    public String getBio() {
        return bio;
    }

    /** Sets {@link #getBio()}. Returns this, for chaining. */
    public Profile setBio(String bio) {
        this.bio = bio;
        return this;
    }

    /** Website on the profile. May be null: absent unless the endpoint selected it. */
    public String getWebsite() {
        return website;
    }

    /** Sets {@link #getWebsite()}. Returns this, for chaining. */
    public Profile setWebsite(String website) {
        this.website = website;
        return this;
    }

    /** The profile's primary public wallet. May be null: absent unless the endpoint selected it. */
    public PublicWallet getPublicWallet() {
        return publicWallet;
    }

    /** Sets {@link #getPublicWallet()}. Returns this, for chaining. */
    public Profile setPublicWallet(PublicWallet publicWallet) {
        this.publicWallet = publicWallet;
        return this;
    }

    /** Wallets linked to the profile. May be null: absent unless the endpoint selected it. */
    public LinkedWallets getLinkedWallets() {
        return linkedWallets;
    }

    /** Sets {@link #getLinkedWallets()}. Returns this, for chaining. */
    public Profile setLinkedWallets(LinkedWallets linkedWallets) {
        this.linkedWallets = linkedWallets;
        return this;
    }

    /**
     * Coins the profile holds (only filled by the profile-balances endpoint). May be null: absent
     * unless the endpoint selected it.
     */
    public CoinBalanceConnection getCoinBalances() {
        return coinBalances;
    }

    /** Sets {@link #getCoinBalances()}. Returns this, for chaining. */
    public Profile setCoinBalances(CoinBalanceConnection coinBalances) {
        this.coinBalances = coinBalances;
        return this;
    }

    /**
     * Coins the profile created (only filled by the profile-coins endpoint). May be null: absent
     * unless the endpoint selected it.
     */
    public Zora20TokenConnection getCreatedCoins() {
        return createdCoins;
    }

    /** Sets {@link #getCreatedCoins()}. Returns this, for chaining. */
    public Profile setCreatedCoins(Zora20TokenConnection createdCoins) {
        this.createdCoins = createdCoins;
        return this;
    }

    /** How many times the handle has been changed. May be null: absent unless the endpoint selected it. */
    public Long getUsernameChangesCount() {
        return usernameChangesCount;
    }

    /** Sets {@link #getUsernameChangesCount()}. Returns this, for chaining. */
    public Profile setUsernameChangesCount(Long usernameChangesCount) {
        this.usernameChangesCount = usernameChangesCount;
        return this;
    }

    /** An external wallet linked to the profile. May be null: absent unless the endpoint selected it. */
    public ExternalWallet getExternalWallet() {
        return externalWallet;
    }

    /** Sets {@link #getExternalWallet()}. Returns this, for chaining. */
    public Profile setExternalWallet(ExternalWallet externalWallet) {
        this.externalWallet = externalWallet;
        return this;
    }

    /** Who follows this profile. May be null: absent unless the endpoint selected it. */
    public Followers getFollowers() {
        return followers;
    }

    /** Sets {@link #getFollowers()}. Returns this, for chaining. */
    public Profile setFollowers(Followers followers) {
        this.followers = followers;
        return this;
    }

    /** Who this profile follows. May be null: absent unless the endpoint selected it. */
    public Followers getFollowing() {
        return following;
    }

    /** Sets {@link #getFollowing()}. Returns this, for chaining. */
    public Profile setFollowing(Followers following) {
        this.following = following;
        return this;
    }

    /**
     * History of social accounts being linked and unlinked. May be null: absent unless the endpoint
     * selected it.
     */
    public SocialAccountLinkedEvents getSocialAccountLinkedEvents() {
        return socialAccountLinkedEvents;
    }

    /** Sets {@link #getSocialAccountLinkedEvents()}. Returns this, for chaining. */
    public Profile setSocialAccountLinkedEvents(SocialAccountLinkedEvents socialAccountLinkedEvents) {
        this.socialAccountLinkedEvents = socialAccountLinkedEvents;
        return this;
    }

    @Override
    public String toString() {
        return "Profile" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
