// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** What a trade is expected to return. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Quote {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("amountOut")
    private String amountOut;
    @JsonProperty("slippage")
    private Double slippage;
    @JsonProperty("tokenIn")
    private TokenSpec tokenIn;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Quote setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * Expected output, in the output token's smallest unit. May be null: absent unless the endpoint
     * selected it.
     */
    public String getAmountOut() {
        return amountOut;
    }

    /** Sets {@link #getAmountOut()}. Returns this, for chaining. */
    public Quote setAmountOut(String amountOut) {
        this.amountOut = amountOut;
        return this;
    }

    /**
     * Slippage tolerance the quote was built with (0.05 = 5%). May be null: absent unless the endpoint
     * selected it.
     */
    public Double getSlippage() {
        return slippage;
    }

    /** Sets {@link #getSlippage()}. Returns this, for chaining. */
    public Quote setSlippage(Double slippage) {
        this.slippage = slippage;
        return this;
    }

    /** The token being sold. May be null: absent unless the endpoint selected it. */
    public TokenSpec getTokenIn() {
        return tokenIn;
    }

    /** Sets {@link #getTokenIn()}. Returns this, for chaining. */
    public Quote setTokenIn(TokenSpec tokenIn) {
        this.tokenIn = tokenIn;
        return this;
    }

    @Override
    public String toString() {
        return "Quote" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
