// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/**
 * A trade to quote. TokenIn, TokenOut, AmountIn and Sender are required; Recipient defaults to Sender
 * and Slippage to 0.05.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class QuoteRequest {
    @JsonProperty("referrer")
    private String referrer;
    @JsonProperty("signatures")
    private List<SignatureInput> signatures;
    @JsonProperty("permitActiveSeconds")
    private Double permitActiveSeconds;
    @JsonProperty("chainId")
    private Long chainId;
    @JsonProperty("tokenOut")
    private TokenSpecInput tokenOut;
    @JsonProperty("tokenIn")
    private TokenSpecInput tokenIn;
    @JsonProperty("amountIn")
    private String amountIn;
    @JsonProperty("slippage")
    private Double slippage;
    @JsonProperty("recipient")
    private String recipient;
    @JsonProperty("sender")
    private String sender;

    /** Address that earns the trade referral reward for routing this trade. Optional. */
    public String getReferrer() {
        return referrer;
    }

    /** Sets {@link #getReferrer()}. Returns this, for chaining. */
    public QuoteRequest setReferrer(String referrer) {
        this.referrer = referrer;
        return this;
    }

    /** Permit2 signatures, when selling an ERC-20 without a prior approval. Optional. */
    public List<SignatureInput> getSignatures() {
        return signatures;
    }

    /** Sets {@link #getSignatures()}. Returns this, for chaining. */
    public QuoteRequest setSignatures(List<SignatureInput> signatures) {
        this.signatures = signatures;
        return this;
    }

    /** How long a Permit2 signature stays valid, in seconds. Optional. */
    public Double getPermitActiveSeconds() {
        return permitActiveSeconds;
    }

    /** Sets {@link #getPermitActiveSeconds()}. Returns this, for chaining. */
    public QuoteRequest setPermitActiveSeconds(Double permitActiveSeconds) {
        this.permitActiveSeconds = permitActiveSeconds;
        return this;
    }

    /** Chain ID (8453 = Base). Optional. */
    public Long getChainId() {
        return chainId;
    }

    /** Sets {@link #getChainId()}. Returns this, for chaining. */
    public QuoteRequest setChainId(Long chainId) {
        this.chainId = chainId;
        return this;
    }

    /** What to buy. Use ETH() or ERC20(address). Required. */
    public TokenSpecInput getTokenOut() {
        return tokenOut;
    }

    /** Sets {@link #getTokenOut()}. Returns this, for chaining. */
    public QuoteRequest setTokenOut(TokenSpecInput tokenOut) {
        this.tokenOut = tokenOut;
        return this;
    }

    /** What to sell. Use ETH() or ERC20(address). Required. */
    public TokenSpecInput getTokenIn() {
        return tokenIn;
    }

    /** Sets {@link #getTokenIn()}. Returns this, for chaining. */
    public QuoteRequest setTokenIn(TokenSpecInput tokenIn) {
        this.tokenIn = tokenIn;
        return this;
    }

    /** Amount to sell, in the input token's smallest unit (wei for ETH). Required. */
    public String getAmountIn() {
        return amountIn;
    }

    /** Sets {@link #getAmountIn()}. Returns this, for chaining. */
    public QuoteRequest setAmountIn(String amountIn) {
        this.amountIn = amountIn;
        return this;
    }

    /** Maximum slippage (0.05 = 5%). Defaults to 5% with QuoteTrade. Optional. */
    public Double getSlippage() {
        return slippage;
    }

    /** Sets {@link #getSlippage()}. Returns this, for chaining. */
    public QuoteRequest setSlippage(Double slippage) {
        this.slippage = slippage;
        return this;
    }

    /** Wallet that receives the output. Defaults to the sender with QuoteTrade. Optional. */
    public String getRecipient() {
        return recipient;
    }

    /** Sets {@link #getRecipient()}. Returns this, for chaining. */
    public QuoteRequest setRecipient(String recipient) {
        this.recipient = recipient;
        return this;
    }

    /** Wallet that will send the transaction. Required. */
    public String getSender() {
        return sender;
    }

    /** Sets {@link #getSender()}. Returns this, for chaining. */
    public QuoteRequest setSender(String sender) {
        this.sender = sender;
        return this;
    }

    @Override
    public String toString() {
        return "QuoteRequest" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
