// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A trade quote and the transaction that executes it. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class QuoteResponse {
    @JsonProperty("success")
    @JsonDeserialize(using = FlexBooleanDeserializer.class)
    private Boolean success;
    @JsonProperty("call")
    private Call call;
    @JsonProperty("permits")
    private List<SignedPermit> permits;
    @JsonProperty("trade")
    private Trade trade;
    @JsonProperty("quote")
    private Quote quote;

    /**
     * Whether a route was found. Sent by the API as a string; the SDKs read it as a boolean. May be
     * null: absent unless the endpoint selected it.
     */
    public Boolean getSuccess() {
        return success;
    }

    /** Sets {@link #getSuccess()}. Returns this, for chaining. */
    public QuoteResponse setSuccess(Boolean success) {
        this.success = success;
        return this;
    }

    /**
     * The transaction to send from the sender's wallet. May be null: absent unless the endpoint
     * selected it.
     */
    public Call getCall() {
        return call;
    }

    /** Sets {@link #getCall()}. Returns this, for chaining. */
    public QuoteResponse setCall(Call call) {
        this.call = call;
        return this;
    }

    /**
     * Permit2 permits the sender must sign first, when selling an ERC-20. May be null: absent unless
     * the endpoint selected it.
     */
    public List<SignedPermit> getPermits() {
        return permits;
    }

    /** Sets {@link #getPermits()}. Returns this, for chaining. */
    public QuoteResponse setPermits(List<SignedPermit> permits) {
        this.permits = permits;
        return this;
    }

    /**
     * The Universal Router trade encoded in the call. May be null: absent unless the endpoint selected
     * it.
     */
    public Trade getTrade() {
        return trade;
    }

    /** Sets {@link #getTrade()}. Returns this, for chaining. */
    public QuoteResponse setTrade(Trade trade) {
        this.trade = trade;
        return this;
    }

    /** What the trade is expected to return. May be null: absent unless the endpoint selected it. */
    public Quote getQuote() {
        return quote;
    }

    /** Sets {@link #getQuote()}. Returns this, for chaining. */
    public QuoteResponse setQuote(Quote quote) {
        this.quote = quote;
        return this;
    }

    @Override
    public String toString() {
        return "QuoteResponse" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
