// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class SignedPermit {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("signature")
    private String signature;
    @JsonProperty("permit")
    private Permit permit;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public SignedPermit setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** The signature. May be null: absent unless the endpoint selected it. */
    public String getSignature() {
        return signature;
    }

    /** Sets {@link #getSignature()}. Returns this, for chaining. */
    public SignedPermit setSignature(String signature) {
        this.signature = signature;
        return this;
    }

    /** The Permit2 permit. May be null: absent unless the endpoint selected it. */
    public Permit getPermit() {
        return permit;
    }

    /** Sets {@link #getPermit()}. Returns this, for chaining. */
    public SignedPermit setPermit(Permit permit) {
        this.permit = permit;
        return this;
    }

    @Override
    public String toString() {
        return "SignedPermit" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
