// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class SignatureInput {
    @JsonProperty("permit")
    private PermitInput permit;
    @JsonProperty("signature")
    private String signature;

    /** The Permit2 permit. Required. */
    public PermitInput getPermit() {
        return permit;
    }

    /** Sets {@link #getPermit()}. Returns this, for chaining. */
    public SignatureInput setPermit(PermitInput permit) {
        this.permit = permit;
        return this;
    }

    /** The signature. Required. */
    public String getSignature() {
        return signature;
    }

    /** Sets {@link #getSignature()}. Returns this, for chaining. */
    public SignatureInput setSignature(String signature) {
        this.signature = signature;
        return this;
    }

    @Override
    public String toString() {
        return "SignatureInput" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
