// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class SocialAccountLinkedEvents {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("edges")
    private List<SocialAccountLinkedEventEdge> edges;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public SocialAccountLinkedEvents setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * The items on this page, each wrapped in an edge. May be null: absent unless the endpoint
     * selected it.
     */
    public List<SocialAccountLinkedEventEdge> getEdges() {
        return edges;
    }

    /** Sets {@link #getEdges()}. Returns this, for chaining. */
    public SocialAccountLinkedEvents setEdges(List<SocialAccountLinkedEventEdge> edges) {
        this.edges = edges;
        return this;
    }

    @Override
    public String toString() {
        return "SocialAccountLinkedEvents" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
