// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class SocialAccounts {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("instagram")
    private Instagram instagram;
    @JsonProperty("tiktok")
    private Instagram tiktok;
    @JsonProperty("twitter")
    private Instagram twitter;
    @JsonProperty("farcaster")
    private Instagram farcaster;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public SocialAccounts setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Linked Instagram account. May be null: absent unless the endpoint selected it. */
    public Instagram getInstagram() {
        return instagram;
    }

    /** Sets {@link #getInstagram()}. Returns this, for chaining. */
    public SocialAccounts setInstagram(Instagram instagram) {
        this.instagram = instagram;
        return this;
    }

    /** Linked TikTok account. May be null: absent unless the endpoint selected it. */
    public Instagram getTiktok() {
        return tiktok;
    }

    /** Sets {@link #getTiktok()}. Returns this, for chaining. */
    public SocialAccounts setTiktok(Instagram tiktok) {
        this.tiktok = tiktok;
        return this;
    }

    /** Linked X (Twitter) account. May be null: absent unless the endpoint selected it. */
    public Instagram getTwitter() {
        return twitter;
    }

    /** Sets {@link #getTwitter()}. Returns this, for chaining. */
    public SocialAccounts setTwitter(Instagram twitter) {
        this.twitter = twitter;
        return this;
    }

    /** Linked Farcaster account. May be null: absent unless the endpoint selected it. */
    public Instagram getFarcaster() {
        return farcaster;
    }

    /** Sets {@link #getFarcaster()}. Returns this, for chaining. */
    public SocialAccounts setFarcaster(Instagram farcaster) {
        this.farcaster = farcaster;
        return this;
    }

    @Override
    public String toString() {
        return "SocialAccounts" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
