// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * How to order a profile's balances. An extensible enum: values Zora adds later are kept, not
 * rejected.
 */
public final class SortOption {
    /** {@code BALANCE} */
    public static final SortOption BALANCE = new SortOption("BALANCE");
    /** {@code MARKET_CAP} */
    public static final SortOption MARKET_CAP = new SortOption("MARKET_CAP");
    /** {@code USD_VALUE} */
    public static final SortOption USD_VALUE = new SortOption("USD_VALUE");
    /** {@code PRICE_CHANGE} */
    public static final SortOption PRICE_CHANGE = new SortOption("PRICE_CHANGE");
    /** {@code MARKET_VALUE_USD} */
    public static final SortOption MARKET_VALUE_USD = new SortOption("MARKET_VALUE_USD");

    /** Every value this SDK knows. */
    public static final List<SortOption> ALL = Collections.unmodifiableList(Arrays.asList(BALANCE, MARKET_CAP, USD_VALUE, PRICE_CHANGE, MARKET_VALUE_USD));

    private final String value;

    private SortOption(String value) {
        this.value = Objects.requireNonNull(value);
    }

    /** Wraps any value, including ones this SDK doesn't know. */
    @JsonCreator
    public static SortOption of(String value) {
        for (SortOption known : ALL) if (known.value.equals(value)) return known;
        return new SortOption(value);
    }

    /** The value as the API spells it. */
    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof SortOption && (((SortOption) o).value).equals(value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
