// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Whether a trade was a buy or a sell. An extensible enum: values Zora adds later are kept, not
 * rejected.
 */
public final class SwapType {
    /** {@code BUY} */
    public static final SwapType BUY = new SwapType("BUY");
    /** {@code SELL} */
    public static final SwapType SELL = new SwapType("SELL");

    /** Every value this SDK knows. */
    public static final List<SwapType> ALL = Collections.unmodifiableList(Arrays.asList(BUY, SELL));

    private final String value;

    private SwapType(String value) {
        this.value = Objects.requireNonNull(value);
    }

    /** Wraps any value, including ones this SDK doesn't know. */
    @JsonCreator
    public static SwapType of(String value) {
        for (SwapType known : ALL) if (known.value.equals(value)) return known;
        return new SwapType(value);
    }

    /** The value as the API spells it. */
    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof SwapType && (((SwapType) o).value).equals(value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
