// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** One buy or sell of a coin. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class SwapActivity {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("id")
    private String id;
    @JsonProperty("currencyAmountWithPrice")
    private CurrencyAmountWithPrice currencyAmountWithPrice;
    @JsonProperty("senderAddress")
    private String senderAddress;
    @JsonProperty("recipientAddress")
    private String recipientAddress;
    @JsonProperty("transactionHash")
    private String transactionHash;
    @JsonProperty("coinAmount")
    private String coinAmount;
    @JsonProperty("blockTimestamp")
    private String blockTimestamp;
    @JsonProperty("activityType")
    private SwapType activityType;
    @JsonProperty("senderProfile")
    private OwnerProfile senderProfile;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public SwapActivity setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Globally unique ID. May be null: absent unless the endpoint selected it. */
    public String getId() {
        return id;
    }

    /** Sets {@link #getId()}. Returns this, for chaining. */
    public SwapActivity setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Amount in the pool's currency, with the currency's USD price at the time. May be null: absent
     * unless the endpoint selected it.
     */
    public CurrencyAmountWithPrice getCurrencyAmountWithPrice() {
        return currencyAmountWithPrice;
    }

    /** Sets {@link #getCurrencyAmountWithPrice()}. Returns this, for chaining. */
    public SwapActivity setCurrencyAmountWithPrice(CurrencyAmountWithPrice currencyAmountWithPrice) {
        this.currencyAmountWithPrice = currencyAmountWithPrice;
        return this;
    }

    /** Wallet that sent the swap. May be null: absent unless the endpoint selected it. */
    public String getSenderAddress() {
        return senderAddress;
    }

    /** Sets {@link #getSenderAddress()}. Returns this, for chaining. */
    public SwapActivity setSenderAddress(String senderAddress) {
        this.senderAddress = senderAddress;
        return this;
    }

    /** Wallet that received the output. May be null: absent unless the endpoint selected it. */
    public String getRecipientAddress() {
        return recipientAddress;
    }

    /** Sets {@link #getRecipientAddress()}. Returns this, for chaining. */
    public SwapActivity setRecipientAddress(String recipientAddress) {
        this.recipientAddress = recipientAddress;
        return this;
    }

    /** Hash of the transaction it happened in. May be null: absent unless the endpoint selected it. */
    public String getTransactionHash() {
        return transactionHash;
    }

    /** Sets {@link #getTransactionHash()}. Returns this, for chaining. */
    public SwapActivity setTransactionHash(String transactionHash) {
        this.transactionHash = transactionHash;
        return this;
    }

    /**
     * Coins bought or sold, in the smallest unit (18 decimals). May be null: absent unless the
     * endpoint selected it.
     */
    public String getCoinAmount() {
        return coinAmount;
    }

    /** Sets {@link #getCoinAmount()}. Returns this, for chaining. */
    public SwapActivity setCoinAmount(String coinAmount) {
        this.coinAmount = coinAmount;
        return this;
    }

    /**
     * Time of the block it happened in (ISO 8601, UTC). May be null: absent unless the endpoint
     * selected it.
     */
    public String getBlockTimestamp() {
        return blockTimestamp;
    }

    /** Sets {@link #getBlockTimestamp()}. Returns this, for chaining. */
    public SwapActivity setBlockTimestamp(String blockTimestamp) {
        this.blockTimestamp = blockTimestamp;
        return this;
    }

    /** BUY or SELL. May be null: absent unless the endpoint selected it. */
    public SwapType getActivityType() {
        return activityType;
    }

    /** Sets {@link #getActivityType()}. Returns this, for chaining. */
    public SwapActivity setActivityType(SwapType activityType) {
        this.activityType = activityType;
        return this;
    }

    /** Profile of the wallet that sent the trade. May be null: absent unless the endpoint selected it. */
    public OwnerProfile getSenderProfile() {
        return senderProfile;
    }

    /** Sets {@link #getSenderProfile()}. Returns this, for chaining. */
    public SwapActivity setSenderProfile(OwnerProfile senderProfile) {
        this.senderProfile = senderProfile;
        return this;
    }

    @Override
    public String toString() {
        return "SwapActivity" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
