// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/**
 * A token to trade: native ETH (type "eth") or an ERC-20 (type "erc20" plus address). Build one with
 * ETH() or ERC20(address).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class TokenSpecInput {
    @JsonProperty("type")
    private TokenType type_;
    @JsonProperty("address")
    private String address;

    /** eth for native ETH, erc20 for a token (which then needs an address). Required. */
    public TokenType getType() {
        return type_;
    }

    /** Sets {@link #getType()}. Returns this, for chaining. */
    public TokenSpecInput setType(TokenType type_) {
        this.type_ = type_;
        return this;
    }

    /** Contract address (lowercase 0x hex). Optional. */
    public String getAddress() {
        return address;
    }

    /** Sets {@link #getAddress()}. Returns this, for chaining. */
    public TokenSpecInput setAddress(String address) {
        this.address = address;
        return this;
    }

    @Override
    public String toString() {
        return "TokenSpecInput" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
