// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A token in a trade quote: native ETH or an ERC-20 address. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class TokenSpec {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("type")
    private String type_;
    @JsonProperty("address")
    private String address;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public TokenSpec setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * eth for native ETH, erc20 for a token (which then needs an address). May be null: absent unless
     * the endpoint selected it.
     */
    public String getType() {
        return type_;
    }

    /** Sets {@link #getType()}. Returns this, for chaining. */
    public TokenSpec setType(String type_) {
        this.type_ = type_;
        return this;
    }

    /** Contract address (lowercase 0x hex). May be null: absent unless the endpoint selected it. */
    public String getAddress() {
        return address;
    }

    /** Sets {@link #getAddress()}. Returns this, for chaining. */
    public TokenSpec setAddress(String address) {
        this.address = address;
        return this;
    }

    @Override
    public String toString() {
        return "TokenSpec" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
