// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** One page of TokenBalance results. Nodes() lists them; PageInfo says how to get the next page. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class TokenBalanceConnection {
    @JsonProperty("pageInfo")
    private PageInfo pageInfo;
    @JsonProperty("count")
    private Long count;
    @JsonProperty("edges")
    private List<TokenBalanceEdge> edges;

    /** How to fetch the next page. May be null: absent unless the endpoint selected it. */
    public PageInfo getPageInfo() {
        return pageInfo;
    }

    /** Sets {@link #getPageInfo()}. Returns this, for chaining. */
    public TokenBalanceConnection setPageInfo(PageInfo pageInfo) {
        this.pageInfo = pageInfo;
        return this;
    }

    /**
     * Total number of items, where the API reports it. May be null: absent unless the endpoint
     * selected it.
     */
    public Long getCount() {
        return count;
    }

    /** Sets {@link #getCount()}. Returns this, for chaining. */
    public TokenBalanceConnection setCount(Long count) {
        this.count = count;
        return this;
    }

    /**
     * The items on this page, each wrapped in an edge. May be null: absent unless the endpoint
     * selected it.
     */
    public List<TokenBalanceEdge> getEdges() {
        return edges;
    }

    /** Sets {@link #getEdges()}. Returns this, for chaining. */
    public TokenBalanceConnection setEdges(List<TokenBalanceEdge> edges) {
        this.edges = edges;
        return this;
    }

    /** The TokenBalance values on this page, skipping empty edges. */
    public List<TokenBalance> nodes() {
        List<TokenBalance> out = new ArrayList<>();
        if (edges != null) for (TokenBalanceEdge e : edges) if (e != null && e.getNode() != null) out.add(e.getNode());
        return out;
    }

    /** The cursor for the next page, or null on the last page. */
    public String nextCursor() {
        return pageInfo != null && Boolean.TRUE.equals(pageInfo.getHasNextPage()) ? pageInfo.getEndCursor() : null;
    }

    @Override
    public String toString() {
        return "TokenBalanceConnection" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
