// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/** Native ETH or an ERC-20. An extensible enum: values Zora adds later are kept, not rejected. */
public final class TokenType {
    /** {@code eth} */
    public static final TokenType ETH = new TokenType("eth");
    /** {@code erc20} */
    public static final TokenType ERC20 = new TokenType("erc20");

    /** Every value this SDK knows. */
    public static final List<TokenType> ALL = Collections.unmodifiableList(Arrays.asList(ETH, ERC20));

    private final String value;

    private TokenType(String value) {
        this.value = Objects.requireNonNull(value);
    }

    /** Wraps any value, including ones this SDK doesn't know. */
    @JsonCreator
    public static TokenType of(String value) {
        for (TokenType known : ALL) if (known.value.equals(value)) return known;
        return new TokenType(value);
    }

    /** The value as the API spells it. */
    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof TokenType && (((TokenType) o).value).equals(value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
