// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** One holder of a coin and how much they hold. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class TokenBalance {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("balance")
    private String balance;
    @JsonProperty("ownerAddress")
    private String ownerAddress;
    @JsonProperty("ownerProfile")
    private OwnerProfile ownerProfile;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public TokenBalance setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * Amount held, in the coin's smallest unit (18 decimals) — divide by 1e18 for whole coins. May be
     * null: absent unless the endpoint selected it.
     */
    public String getBalance() {
        return balance;
    }

    /** Sets {@link #getBalance()}. Returns this, for chaining. */
    public TokenBalance setBalance(String balance) {
        this.balance = balance;
        return this;
    }

    /** Wallet holding the coin. May be null: absent unless the endpoint selected it. */
    public String getOwnerAddress() {
        return ownerAddress;
    }

    /** Sets {@link #getOwnerAddress()}. Returns this, for chaining. */
    public TokenBalance setOwnerAddress(String ownerAddress) {
        this.ownerAddress = ownerAddress;
        return this;
    }

    /**
     * Profile of the holder (a wallet profile if the holder has no Zora account). May be null: absent
     * unless the endpoint selected it.
     */
    public OwnerProfile getOwnerProfile() {
        return ownerProfile;
    }

    /** Sets {@link #getOwnerProfile()}. Returns this, for chaining. */
    public TokenBalance setOwnerProfile(OwnerProfile ownerProfile) {
        this.ownerProfile = ownerProfile;
        return this;
    }

    @Override
    public String toString() {
        return "TokenBalance" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
