// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A coin's current price, in the pool's currency and in USD. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class TokenPrice {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("priceInUsdc")
    private String priceInUsdc;
    @JsonProperty("currencyAddress")
    private String currencyAddress;
    @JsonProperty("priceInPoolToken")
    private String priceInPoolToken;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public TokenPrice setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * Price of one whole coin in USDC (≈ USD), as a decimal string. May be null: absent unless the
     * endpoint selected it.
     */
    public String getPriceInUsdc() {
        return priceInUsdc;
    }

    /** Sets {@link #getPriceInUsdc()}. Returns this, for chaining. */
    public TokenPrice setPriceInUsdc(String priceInUsdc) {
        this.priceInUsdc = priceInUsdc;
        return this;
    }

    /** The coin the price is for. May be null: absent unless the endpoint selected it. */
    public String getCurrencyAddress() {
        return currencyAddress;
    }

    /** Sets {@link #getCurrencyAddress()}. Returns this, for chaining. */
    public TokenPrice setCurrencyAddress(String currencyAddress) {
        this.currencyAddress = currencyAddress;
        return this;
    }

    /**
     * Price of one whole coin in the pool's currency, as a decimal string. May be null: absent unless
     * the endpoint selected it.
     */
    public String getPriceInPoolToken() {
        return priceInPoolToken;
    }

    /** Sets {@link #getPriceInPoolToken()}. Returns this, for chaining. */
    public TokenPrice setPriceInPoolToken(String priceInPoolToken) {
        this.priceInPoolToken = priceInPoolToken;
        return this;
    }

    @Override
    public String toString() {
        return "TokenPrice" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
