// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Trade {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("commands")
    private List<String> commands;
    @JsonProperty("value")
    private String value;
    @JsonProperty("inputs")
    private List<String> inputs;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Trade setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * Universal Router commands the trade executes (hex). May be null: absent unless the endpoint
     * selected it.
     */
    public List<String> getCommands() {
        return commands;
    }

    /** Sets {@link #getCommands()}. Returns this, for chaining. */
    public Trade setCommands(List<String> commands) {
        this.commands = commands;
        return this;
    }

    /** ETH to send, in wei. May be null: absent unless the endpoint selected it. */
    public String getValue() {
        return value;
    }

    /** Sets {@link #getValue()}. Returns this, for chaining. */
    public Trade setValue(String value) {
        this.value = value;
        return this;
    }

    /** ABI-encoded input for each command. May be null: absent unless the endpoint selected it. */
    public List<String> getInputs() {
        return inputs;
    }

    /** Sets {@link #getInputs()}. Returns this, for chaining. */
    public Trade setInputs(List<String> inputs) {
        this.inputs = inputs;
        return this;
    }

    @Override
    public String toString() {
        return "Trade" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
