// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** One trader's position on the weekly leaderboard. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class TraderLeaderboardEntry {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("entityName")
    private String entityName;
    @JsonProperty("score")
    private Long score;
    @JsonProperty("weekVolumeUsd")
    private Double weekVolumeUsd;
    @JsonProperty("weekTradesCount")
    private Long weekTradesCount;
    @JsonProperty("weekGrossVolumeZora")
    private Double weekGrossVolumeZora;
    @JsonProperty("traderProfile")
    private FeaturedCreator traderProfile;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public TraderLeaderboardEntry setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Name of the coin. May be null: absent unless the endpoint selected it. */
    public String getEntityName() {
        return entityName;
    }

    /** Sets {@link #getEntityName()}. Returns this, for chaining. */
    public TraderLeaderboardEntry setEntityName(String entityName) {
        this.entityName = entityName;
        return this;
    }

    /** Leaderboard score. May be null: absent unless the endpoint selected it. */
    public Long getScore() {
        return score;
    }

    /** Sets {@link #getScore()}. Returns this, for chaining. */
    public TraderLeaderboardEntry setScore(Long score) {
        this.score = score;
        return this;
    }

    /** Trading volume this week in USD. May be null: absent unless the endpoint selected it. */
    public Double getWeekVolumeUsd() {
        return weekVolumeUsd;
    }

    /** Sets {@link #getWeekVolumeUsd()}. Returns this, for chaining. */
    public TraderLeaderboardEntry setWeekVolumeUsd(Double weekVolumeUsd) {
        this.weekVolumeUsd = weekVolumeUsd;
        return this;
    }

    /** Trades made this week. May be null: absent unless the endpoint selected it. */
    public Long getWeekTradesCount() {
        return weekTradesCount;
    }

    /** Sets {@link #getWeekTradesCount()}. Returns this, for chaining. */
    public TraderLeaderboardEntry setWeekTradesCount(Long weekTradesCount) {
        this.weekTradesCount = weekTradesCount;
        return this;
    }

    /** Gross trading volume this week, in ZORA. May be null: absent unless the endpoint selected it. */
    public Double getWeekGrossVolumeZora() {
        return weekGrossVolumeZora;
    }

    /** Sets {@link #getWeekGrossVolumeZora()}. Returns this, for chaining. */
    public TraderLeaderboardEntry setWeekGrossVolumeZora(Double weekGrossVolumeZora) {
        this.weekGrossVolumeZora = weekGrossVolumeZora;
        return this;
    }

    /** Profile of the trader. May be null: absent unless the endpoint selected it. */
    public FeaturedCreator getTraderProfile() {
        return traderProfile;
    }

    /** Sets {@link #getTraderProfile()}. Returns this, for chaining. */
    public TraderLeaderboardEntry setTraderProfile(FeaturedCreator traderProfile) {
        this.traderProfile = traderProfile;
        return this;
    }

    @Override
    public String toString() {
        return "TraderLeaderboardEntry" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
