// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** A Zora API object. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Valuation {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("marketValueUsd")
    private String marketValueUsd;
    @JsonProperty("faceValueUsd")
    private String faceValueUsd;
    @JsonProperty("blockNumber")
    private Long blockNumber;
    @JsonProperty("maxSwappable")
    private MaxSwappable maxSwappable;
    @JsonProperty("currencyAmount")
    private Amount currencyAmount;
    @JsonProperty("error")
    private String error;

    /**
     * The type name Zora's GraphQL backend reports for this object, when it includes one. May be null:
     * absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Valuation setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /**
     * What the holding would fetch at the current price, in USD. May be null: absent unless the
     * endpoint selected it.
     */
    public String getMarketValueUsd() {
        return marketValueUsd;
    }

    /** Sets {@link #getMarketValueUsd()}. Returns this, for chaining. */
    public Valuation setMarketValueUsd(String marketValueUsd) {
        this.marketValueUsd = marketValueUsd;
        return this;
    }

    /** Balance × price, in USD, ignoring slippage. May be null: absent unless the endpoint selected it. */
    public String getFaceValueUsd() {
        return faceValueUsd;
    }

    /** Sets {@link #getFaceValueUsd()}. Returns this, for chaining. */
    public Valuation setFaceValueUsd(String faceValueUsd) {
        this.faceValueUsd = faceValueUsd;
        return this;
    }

    /** Block the valuation was computed at. May be null: absent unless the endpoint selected it. */
    public Long getBlockNumber() {
        return blockNumber;
    }

    /** Sets {@link #getBlockNumber()}. Returns this, for chaining. */
    public Valuation setBlockNumber(Long blockNumber) {
        this.blockNumber = blockNumber;
        return this;
    }

    /**
     * The most of the holding that can be sold into the pool right now. May be null: absent unless the
     * endpoint selected it.
     */
    public MaxSwappable getMaxSwappable() {
        return maxSwappable;
    }

    /** Sets {@link #getMaxSwappable()}. Returns this, for chaining. */
    public Valuation setMaxSwappable(MaxSwappable maxSwappable) {
        this.maxSwappable = maxSwappable;
        return this;
    }

    /**
     * Amount paid or received, in the pool's currency. May be null: absent unless the endpoint
     * selected it.
     */
    public Amount getCurrencyAmount() {
        return currencyAmount;
    }

    /** Sets {@link #getCurrencyAmount()}. Returns this, for chaining. */
    public Valuation setCurrencyAmount(Amount currencyAmount) {
        this.currencyAmount = currencyAmount;
        return this;
    }

    /**
     * Why the valuation couldn't be computed, when it couldn't. May be null: absent unless the
     * endpoint selected it.
     */
    public String getError() {
        return error;
    }

    /** Sets {@link #getError()}. Returns this, for chaining. */
    public Valuation setError(String error) {
        this.error = error;
        return this;
    }

    @Override
    public String toString() {
        return "Valuation" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
