// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * How a wallet linked to a profile is held. An extensible enum: values Zora adds later are kept, not
 * rejected.
 */
public final class WalletType {
    /** {@code PRIVY} */
    public static final WalletType PRIVY = new WalletType("PRIVY");
    /** {@code EXTERNAL} */
    public static final WalletType EXTERNAL = new WalletType("EXTERNAL");
    /** {@code SMART_WALLET} */
    public static final WalletType SMART_WALLET = new WalletType("SMART_WALLET");

    /** Every value this SDK knows. */
    public static final List<WalletType> ALL = Collections.unmodifiableList(Arrays.asList(PRIVY, EXTERNAL, SMART_WALLET));

    private final String value;

    private WalletType(String value) {
        this.value = Objects.requireNonNull(value);
    }

    /** Wraps any value, including ones this SDK doesn't know. */
    @JsonCreator
    public static WalletType of(String value) {
        for (WalletType known : ALL) if (known.value.equals(value)) return known;
        return new WalletType(value);
    }

    /** The value as the API spells it. */
    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof WalletType && (((WalletType) o).value).equals(value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
