// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/** Wraps one Zora20Token in a page of results. */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Zora20TokenEdge {
    @JsonProperty("node")
    private Zora20Token node;
    @JsonProperty("cursor")
    private String cursor;

    /** The item. May be null: absent unless the endpoint selected it. */
    public Zora20Token getNode() {
        return node;
    }

    /** Sets {@link #getNode()}. Returns this, for chaining. */
    public Zora20TokenEdge setNode(Zora20Token node) {
        this.node = node;
        return this;
    }

    /** Cursor pointing at this item. May be null: absent unless the endpoint selected it. */
    public String getCursor() {
        return cursor;
    }

    /** Sets {@link #getCursor()}. Returns this, for chaining. */
    public Zora20TokenEdge setCursor(String cursor) {
        this.cursor = cursor;
        return this;
    }

    @Override
    public String toString() {
        return "Zora20TokenEdge" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
