// Generated by codegen/emit_java.py from Zora's OpenAPI spec. Do not edit.
package io.github.pgalyen1987.zora.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.github.pgalyen1987.zora.internal.FlexBooleanDeserializer;
import java.util.ArrayList;
import java.util.List;

/**
 * A Zora coin: an ERC-20 with a Uniswap V4 market, created by a creator or for a piece of content or a
 * trend. Endpoints return different selections of its fields; anything not selected is empty.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public final class Zora20Token {
    @JsonProperty("__typename")
    private String typename;
    @JsonProperty("id")
    private String id;
    @JsonProperty("platformBlocked")
    private Boolean platformBlocked;
    @JsonProperty("name")
    private String name;
    @JsonProperty("description")
    private String description;
    @JsonProperty("address")
    private String address;
    @JsonProperty("coinType")
    private CoinType coinType;
    @JsonProperty("symbol")
    private String symbol;
    @JsonProperty("totalSupply")
    private String totalSupply;
    @JsonProperty("totalVolume")
    private String totalVolume;
    @JsonProperty("volume24h")
    private String volume24h;
    @JsonProperty("createdAt")
    private String createdAt;
    @JsonProperty("creatorAddress")
    private String creatorAddress;
    @JsonProperty("poolCurrencyToken")
    private PoolCurrencyToken poolCurrencyToken;
    @JsonProperty("tokenPrice")
    private TokenPrice tokenPrice;
    @JsonProperty("marketCap")
    private String marketCap;
    @JsonProperty("marketCapDelta24h")
    private String marketCapDelta24h;
    @JsonProperty("chainId")
    private Long chainId;
    @JsonProperty("tokenUri")
    private String tokenUri;
    @JsonProperty("platformReferrerAddress")
    private String platformReferrerAddress;
    @JsonProperty("payoutRecipientAddress")
    private String payoutRecipientAddress;
    @JsonProperty("creatorProfile")
    private CreatorProfile creatorProfile;
    @JsonProperty("mediaContent")
    private MediaContent mediaContent;
    @JsonProperty("uniqueHolders")
    private Long uniqueHolders;
    @JsonProperty("uniswapV4PoolKey")
    private UniswapV4PoolKey uniswapV4PoolKey;
    @JsonProperty("uniswapV3PoolAddress")
    private String uniswapV3PoolAddress;
    @JsonProperty("zoraComments")
    private ZoraCommentConnection zoraComments;
    @JsonProperty("creatorEarnings")
    private List<CreatorEarning> creatorEarnings;
    @JsonProperty("tokenBalances")
    private TokenBalanceConnection tokenBalances;
    @JsonProperty("comments")
    private CommentConnection comments;
    @JsonProperty("oneHour")
    private List<PricePoint> oneHour;
    @JsonProperty("oneDay")
    private List<PricePoint> oneDay;
    @JsonProperty("oneWeek")
    private List<PricePoint> oneWeek;
    @JsonProperty("oneMonth")
    private List<PricePoint> oneMonth;
    @JsonProperty("all")
    private List<PricePoint> all;
    @JsonProperty("swapActivities")
    private SwapActivityConnection swapActivities;
    @JsonProperty("multichainAddress")
    private String multichainAddress;
    @JsonProperty("uniswapPoolAddress")
    private String uniswapPoolAddress;

    /**
     * Which kind of coin this is: GraphQLZora20Token, GraphQLZora20V4Token, GraphQLZora20CreatorToken
     * or GraphQLZora20TrendToken. May be null: absent unless the endpoint selected it.
     */
    public String getTypename() {
        return typename;
    }

    /** Sets {@link #getTypename()}. Returns this, for chaining. */
    public Zora20Token setTypename(String typename) {
        this.typename = typename;
        return this;
    }

    /** Globally unique ID. May be null: absent unless the endpoint selected it. */
    public String getId() {
        return id;
    }

    /** Sets {@link #getId()}. Returns this, for chaining. */
    public Zora20Token setId(String id) {
        this.id = id;
        return this;
    }

    /** True if Zora hides this from its own app. May be null: absent unless the endpoint selected it. */
    public Boolean getPlatformBlocked() {
        return platformBlocked;
    }

    /** Sets {@link #getPlatformBlocked()}. Returns this, for chaining. */
    public Zora20Token setPlatformBlocked(Boolean platformBlocked) {
        this.platformBlocked = platformBlocked;
        return this;
    }

    /** Display name. May be null: absent unless the endpoint selected it. */
    public String getName() {
        return name;
    }

    /** Sets {@link #getName()}. Returns this, for chaining. */
    public Zora20Token setName(String name) {
        this.name = name;
        return this;
    }

    /** Description from the coin's metadata. May be null: absent unless the endpoint selected it. */
    public String getDescription() {
        return description;
    }

    /** Sets {@link #getDescription()}. Returns this, for chaining. */
    public Zora20Token setDescription(String description) {
        this.description = description;
        return this;
    }

    /** Contract address (lowercase 0x hex). May be null: absent unless the endpoint selected it. */
    public String getAddress() {
        return address;
    }

    /** Sets {@link #getAddress()}. Returns this, for chaining. */
    public Zora20Token setAddress(String address) {
        this.address = address;
        return this;
    }

    /**
     * Whether this is a creator coin, a content coin or a trend. May be null: absent unless the
     * endpoint selected it.
     */
    public CoinType getCoinType() {
        return coinType;
    }

    /** Sets {@link #getCoinType()}. Returns this, for chaining. */
    public Zora20Token setCoinType(CoinType coinType) {
        this.coinType = coinType;
        return this;
    }

    /** Ticker symbol. May be null: absent unless the endpoint selected it. */
    public String getSymbol() {
        return symbol;
    }

    /** Sets {@link #getSymbol()}. Returns this, for chaining. */
    public Zora20Token setSymbol(String symbol) {
        this.symbol = symbol;
        return this;
    }

    /**
     * Total supply in whole tokens, as a decimal string ("1000000000" = one billion). May be null:
     * absent unless the endpoint selected it.
     */
    public String getTotalSupply() {
        return totalSupply;
    }

    /** Sets {@link #getTotalSupply()}. Returns this, for chaining. */
    public Zora20Token setTotalSupply(String totalSupply) {
        this.totalSupply = totalSupply;
        return this;
    }

    /**
     * All-time trading volume in USD, as a decimal string. May be null: absent unless the endpoint
     * selected it.
     */
    public String getTotalVolume() {
        return totalVolume;
    }

    /** Sets {@link #getTotalVolume()}. Returns this, for chaining. */
    public Zora20Token setTotalVolume(String totalVolume) {
        this.totalVolume = totalVolume;
        return this;
    }

    /**
     * Trading volume over the last 24 hours in USD, as a decimal string. May be null: absent unless
     * the endpoint selected it.
     */
    public String getVolume24h() {
        return volume24h;
    }

    /** Sets {@link #getVolume24h()}. Returns this, for chaining. */
    public Zora20Token setVolume24h(String volume24h) {
        this.volume24h = volume24h;
        return this;
    }

    /** When it was created (ISO 8601, UTC). May be null: absent unless the endpoint selected it. */
    public String getCreatedAt() {
        return createdAt;
    }

    /** Sets {@link #getCreatedAt()}. Returns this, for chaining. */
    public Zora20Token setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /** Wallet that created the coin. May be null: absent unless the endpoint selected it. */
    public String getCreatorAddress() {
        return creatorAddress;
    }

    /** Sets {@link #getCreatorAddress()}. Returns this, for chaining. */
    public Zora20Token setCreatorAddress(String creatorAddress) {
        this.creatorAddress = creatorAddress;
        return this;
    }

    /** What the coin's pool trades against. May be null: absent unless the endpoint selected it. */
    public PoolCurrencyToken getPoolCurrencyToken() {
        return poolCurrencyToken;
    }

    /** Sets {@link #getPoolCurrencyToken()}. Returns this, for chaining. */
    public Zora20Token setPoolCurrencyToken(PoolCurrencyToken poolCurrencyToken) {
        this.poolCurrencyToken = poolCurrencyToken;
        return this;
    }

    /** Current price. May be null: absent unless the endpoint selected it. */
    public TokenPrice getTokenPrice() {
        return tokenPrice;
    }

    /** Sets {@link #getTokenPrice()}. Returns this, for chaining. */
    public Zora20Token setTokenPrice(TokenPrice tokenPrice) {
        this.tokenPrice = tokenPrice;
        return this;
    }

    /** Market cap in USD, as a decimal string. May be null: absent unless the endpoint selected it. */
    public String getMarketCap() {
        return marketCap;
    }

    /** Sets {@link #getMarketCap()}. Returns this, for chaining. */
    public Zora20Token setMarketCap(String marketCap) {
        this.marketCap = marketCap;
        return this;
    }

    /**
     * Change in market cap over the last 24 hours in USD (negative when it fell), as a decimal string.
     * May be null: absent unless the endpoint selected it.
     */
    public String getMarketCapDelta24h() {
        return marketCapDelta24h;
    }

    /** Sets {@link #getMarketCapDelta24h()}. Returns this, for chaining. */
    public Zora20Token setMarketCapDelta24h(String marketCapDelta24h) {
        this.marketCapDelta24h = marketCapDelta24h;
        return this;
    }

    /** Chain ID (8453 = Base). May be null: absent unless the endpoint selected it. */
    public Long getChainId() {
        return chainId;
    }

    /** Sets {@link #getChainId()}. Returns this, for chaining. */
    public Zora20Token setChainId(Long chainId) {
        this.chainId = chainId;
        return this;
    }

    /**
     * Metadata URI (EIP-7572 JSON, usually ipfs://). May be null: absent unless the endpoint selected
     * it.
     */
    public String getTokenUri() {
        return tokenUri;
    }

    /** Sets {@link #getTokenUri()}. Returns this, for chaining. */
    public Zora20Token setTokenUri(String tokenUri) {
        this.tokenUri = tokenUri;
        return this;
    }

    /**
     * The app that launched the coin; it earns the platform referral share of every trade, for good.
     * May be null: absent unless the endpoint selected it.
     */
    public String getPlatformReferrerAddress() {
        return platformReferrerAddress;
    }

    /** Sets {@link #getPlatformReferrerAddress()}. Returns this, for chaining. */
    public Zora20Token setPlatformReferrerAddress(String platformReferrerAddress) {
        this.platformReferrerAddress = platformReferrerAddress;
        return this;
    }

    /**
     * Wallet that receives the creator's share of trading fees. May be null: absent unless the
     * endpoint selected it.
     */
    public String getPayoutRecipientAddress() {
        return payoutRecipientAddress;
    }

    /** Sets {@link #getPayoutRecipientAddress()}. Returns this, for chaining. */
    public Zora20Token setPayoutRecipientAddress(String payoutRecipientAddress) {
        this.payoutRecipientAddress = payoutRecipientAddress;
        return this;
    }

    /** Profile of the creator. May be null: absent unless the endpoint selected it. */
    public CreatorProfile getCreatorProfile() {
        return creatorProfile;
    }

    /** Sets {@link #getCreatorProfile()}. Returns this, for chaining. */
    public Zora20Token setCreatorProfile(CreatorProfile creatorProfile) {
        this.creatorProfile = creatorProfile;
        return this;
    }

    /** The image or video attached to the coin. May be null: absent unless the endpoint selected it. */
    public MediaContent getMediaContent() {
        return mediaContent;
    }

    /** Sets {@link #getMediaContent()}. Returns this, for chaining. */
    public Zora20Token setMediaContent(MediaContent mediaContent) {
        this.mediaContent = mediaContent;
        return this;
    }

    /**
     * Number of distinct wallets holding the coin. May be null: absent unless the endpoint selected
     * it.
     */
    public Long getUniqueHolders() {
        return uniqueHolders;
    }

    /** Sets {@link #getUniqueHolders()}. Returns this, for chaining. */
    public Zora20Token setUniqueHolders(Long uniqueHolders) {
        this.uniqueHolders = uniqueHolders;
        return this;
    }

    /** Pool key of a V4 coin's market. May be null: absent unless the endpoint selected it. */
    public UniswapV4PoolKey getUniswapV4PoolKey() {
        return uniswapV4PoolKey;
    }

    /** Sets {@link #getUniswapV4PoolKey()}. Returns this, for chaining. */
    public Zora20Token setUniswapV4PoolKey(UniswapV4PoolKey uniswapV4PoolKey) {
        this.uniswapV4PoolKey = uniswapV4PoolKey;
        return this;
    }

    /**
     * Pool of a legacy V3 coin. Empty for V4 coins, which use uniswapV4PoolKey. May be null: absent
     * unless the endpoint selected it.
     */
    public String getUniswapV3PoolAddress() {
        return uniswapV3PoolAddress;
    }

    /** Sets {@link #getUniswapV3PoolAddress()}. Returns this, for chaining. */
    public Zora20Token setUniswapV3PoolAddress(String uniswapV3PoolAddress) {
        this.uniswapV3PoolAddress = uniswapV3PoolAddress;
        return this;
    }

    /**
     * Comments (only filled by the coin-comments endpoint). May be null: absent unless the endpoint
     * selected it.
     */
    public ZoraCommentConnection getZoraComments() {
        return zoraComments;
    }

    /** Sets {@link #getZoraComments()}. Returns this, for chaining. */
    public Zora20Token setZoraComments(ZoraCommentConnection zoraComments) {
        this.zoraComments = zoraComments;
        return this;
    }

    /**
     * What the creator has earned from trading fees, per currency. May be null: absent unless the
     * endpoint selected it.
     */
    public List<CreatorEarning> getCreatorEarnings() {
        return creatorEarnings;
    }

    /** Sets {@link #getCreatorEarnings()}. Returns this, for chaining. */
    public Zora20Token setCreatorEarnings(List<CreatorEarning> creatorEarnings) {
        this.creatorEarnings = creatorEarnings;
        return this;
    }

    /**
     * Holders (only filled by the coin-holders endpoint). May be null: absent unless the endpoint
     * selected it.
     */
    public TokenBalanceConnection getTokenBalances() {
        return tokenBalances;
    }

    /** Sets {@link #getTokenBalances()}. Returns this, for chaining. */
    public Zora20Token setTokenBalances(TokenBalanceConnection tokenBalances) {
        this.tokenBalances = tokenBalances;
        return this;
    }

    /** Comments. May be null: absent unless the endpoint selected it. */
    public CommentConnection getComments() {
        return comments;
    }

    /** Sets {@link #getComments()}. Returns this, for chaining. */
    public Zora20Token setComments(CommentConnection comments) {
        this.comments = comments;
        return this;
    }

    /**
     * Prices over the last hour (only filled by the price-history endpoint). May be null: absent
     * unless the endpoint selected it.
     */
    public List<PricePoint> getOneHour() {
        return oneHour;
    }

    /** Sets {@link #getOneHour()}. Returns this, for chaining. */
    public Zora20Token setOneHour(List<PricePoint> oneHour) {
        this.oneHour = oneHour;
        return this;
    }

    /** Prices over the last day. May be null: absent unless the endpoint selected it. */
    public List<PricePoint> getOneDay() {
        return oneDay;
    }

    /** Sets {@link #getOneDay()}. Returns this, for chaining. */
    public Zora20Token setOneDay(List<PricePoint> oneDay) {
        this.oneDay = oneDay;
        return this;
    }

    /** Prices over the last week. May be null: absent unless the endpoint selected it. */
    public List<PricePoint> getOneWeek() {
        return oneWeek;
    }

    /** Sets {@link #getOneWeek()}. Returns this, for chaining. */
    public Zora20Token setOneWeek(List<PricePoint> oneWeek) {
        this.oneWeek = oneWeek;
        return this;
    }

    /** Prices over the last month. May be null: absent unless the endpoint selected it. */
    public List<PricePoint> getOneMonth() {
        return oneMonth;
    }

    /** Sets {@link #getOneMonth()}. Returns this, for chaining. */
    public Zora20Token setOneMonth(List<PricePoint> oneMonth) {
        this.oneMonth = oneMonth;
        return this;
    }

    /** Prices over the coin's whole life. May be null: absent unless the endpoint selected it. */
    public List<PricePoint> getAll() {
        return all;
    }

    /** Sets {@link #getAll()}. Returns this, for chaining. */
    public Zora20Token setAll(List<PricePoint> all) {
        this.all = all;
        return this;
    }

    /**
     * Buys and sells (only filled by the coin-swaps endpoint). May be null: absent unless the endpoint
     * selected it.
     */
    public SwapActivityConnection getSwapActivities() {
        return swapActivities;
    }

    /** Sets {@link #getSwapActivities()}. Returns this, for chaining. */
    public Zora20Token setSwapActivities(SwapActivityConnection swapActivities) {
        this.swapActivities = swapActivities;
        return this;
    }

    /**
     * The coin's address on other chains, where Zora reports one. May be null: absent unless the
     * endpoint selected it.
     */
    public String getMultichainAddress() {
        return multichainAddress;
    }

    /** Sets {@link #getMultichainAddress()}. Returns this, for chaining. */
    public Zora20Token setMultichainAddress(String multichainAddress) {
        this.multichainAddress = multichainAddress;
        return this;
    }

    /**
     * The coin's Uniswap pool address, where the API reports one. May be null: absent unless the
     * endpoint selected it.
     */
    public String getUniswapPoolAddress() {
        return uniswapPoolAddress;
    }

    /** Sets {@link #getUniswapPoolAddress()}. Returns this, for chaining. */
    public Zora20Token setUniswapPoolAddress(String uniswapPoolAddress) {
        this.uniswapPoolAddress = uniswapPoolAddress;
        return this;
    }

    @Override
    public String toString() {
        return "Zora20Token" + io.github.pgalyen1987.zora.internal.Json.toString(this);
    }
}
